//! Clamp kernels from `baracuda-kernels-sys`. Baracuda exposes clamp
//! as a *ternary* op `y = clamp(a, b, c)` where `b`/`c` are the lower
//! and upper bound tensors. Fuel's `OpKind::ClampElementwise` carries
//! scalar bounds in `OpParams::Clamp { min, max }`.
//!
//! ## Scalar → broadcast tensor adapter
//!
//! The wrapper allocates two 1-element device buffers (one per bound)
//! and invokes the strided variant with stride 0 on the bound tensors —
//! baracuda's strided ABI broadcasts cells with stride 0 across the
//! whole numel. The input is treated as rank-1 contig (Fuel's executor
//! Contiguizes non-contig consumers).

use std::sync::Arc;

use baracuda_kernels_sys as sys;
use fuel_core_types::{Error, Result};

use crate::byte_storage::CudaStorageBytes;

use super::scratch::Workspace;
use super::status::check;

type TernaryStridedRun = unsafe extern "C" fn(
    numel: i64,
    rank: i32,
    shape: *const i32,
    stride_a: *const i64,
    stride_b: *const i64,
    stride_c: *const i64,
    stride_y: *const i64,
    a: *const std::ffi::c_void,
    b: *const std::ffi::c_void,
    c: *const std::ffi::c_void,
    y: *mut std::ffi::c_void,
    workspace: *mut std::ffi::c_void,
    workspace_bytes: usize,
    stream: *mut std::ffi::c_void,
) -> i32;

/// Common driver for every dtype variant. Builds two 1-element bound
/// buffers + launches the strided ternary clamp with broadcast strides.
///
/// `lo_bytes` / `hi_bytes` are the on-host bytewise representation of
/// the lower / upper bound in the input's storage dtype — generated by
/// the per-dtype wrapper from Fuel's `(min: f64, max: f64)` params.
fn clamp_run(
    src: &CudaStorageBytes,
    lo_bytes: &[u8],
    hi_bytes: &[u8],
    dtype_size_bytes: usize,
    kernel: TernaryStridedRun,
    op_label: &'static str,
) -> Result<CudaStorageBytes> {
    if lo_bytes.len() != dtype_size_bytes || hi_bytes.len() != dtype_size_bytes {
        return Err(Error::Msg(format!(
            "{op_label}: bound buffer size mismatch (got lo={}, hi={}, want {})",
            lo_bytes.len(),
            hi_bytes.len(),
            dtype_size_bytes,
        ))
        .bt());
    }
    let device = src.device().clone();
    if src.len_bytes() % dtype_size_bytes != 0 {
        return Err(Error::Msg(format!(
            "{op_label}: src.len_bytes={} not a multiple of dtype size {}",
            src.len_bytes(),
            dtype_size_bytes,
        ))
        .bt());
    }
    let numel = (src.len_bytes() / dtype_size_bytes) as i64;
    if numel == 0 {
        return CudaStorageBytes::alloc(&device, 0);
    }
    let out_bytes = src.len_bytes();
    let out_buf = device.alloc_zeros::<u8>(out_bytes)?;
    let lo_buf = CudaStorageBytes::from_cpu_bytes(&device, lo_bytes)?;
    let hi_buf = CudaStorageBytes::from_cpu_bytes(&device, hi_bytes)?;
    let scratch = Workspace::alloc(&device, 0)?;
    let stream = device.stream().as_raw() as *mut std::ffi::c_void;

    let a_ptr = src.buffer().as_raw().0 as *const std::ffi::c_void;
    let b_ptr = lo_buf.buffer().as_raw().0 as *const std::ffi::c_void;
    let c_ptr = hi_buf.buffer().as_raw().0 as *const std::ffi::c_void;
    let y_ptr = out_buf.as_raw().0 as *mut std::ffi::c_void;

    // Rank-1 reshape: shape=[numel]; src + out are contig (stride 1),
    // bounds are broadcast (stride 0).
    let shape: [i32; 1] = [i32::try_from(numel as usize).map_err(|_| {
        Error::cuda(crate::error::CudaError::BaracudaShapeOverflow {
            op: op_label,
            dim_index: 0,
            dim_value: numel as usize,
        })
    })?];
    let stride_a: [i64; 1] = [1];
    let stride_b: [i64; 1] = [0];
    let stride_c: [i64; 1] = [0];
    let stride_y: [i64; 1] = [1];

    let status = unsafe {
        kernel(
            numel,
            1,
            shape.as_ptr(),
            stride_a.as_ptr(),
            stride_b.as_ptr(),
            stride_c.as_ptr(),
            stride_y.as_ptr(),
            a_ptr,
            b_ptr,
            c_ptr,
            y_ptr,
            scratch.as_raw(),
            scratch.bytes(),
            stream,
        )
    };
    check(status, op_label)?;
    device.synchronize()?;
    Ok(CudaStorageBytes::from_parts(
        Arc::new(out_buf),
        device,
        out_bytes,
    ))
}

pub fn clamp_f32(src: &CudaStorageBytes, min: f32, max: f32) -> Result<CudaStorageBytes> {
    clamp_run(
        src,
        &min.to_le_bytes(),
        &max.to_le_bytes(),
        4,
        sys::baracuda_kernels_ternary_clamp_f32_strided_run,
        "clamp_f32",
    )
}

pub fn clamp_f64(src: &CudaStorageBytes, min: f64, max: f64) -> Result<CudaStorageBytes> {
    clamp_run(
        src,
        &min.to_le_bytes(),
        &max.to_le_bytes(),
        8,
        sys::baracuda_kernels_ternary_clamp_f64_strided_run,
        "clamp_f64",
    )
}

pub fn clamp_f16(src: &CudaStorageBytes, min: f32, max: f32) -> Result<CudaStorageBytes> {
    // f16 is half_t — 2 bytes. Convert f32 bounds to f16 (lossy but
    // matches the storage's precision).
    let min_h = half::f16::from_f32(min);
    let max_h = half::f16::from_f32(max);
    clamp_run(
        src,
        &min_h.to_le_bytes(),
        &max_h.to_le_bytes(),
        2,
        sys::baracuda_kernels_ternary_clamp_f16_strided_run,
        "clamp_f16",
    )
}

pub fn clamp_bf16(src: &CudaStorageBytes, min: f32, max: f32) -> Result<CudaStorageBytes> {
    let min_b = half::bf16::from_f32(min);
    let max_b = half::bf16::from_f32(max);
    clamp_run(
        src,
        &min_b.to_le_bytes(),
        &max_b.to_le_bytes(),
        2,
        sys::baracuda_kernels_ternary_clamp_bf16_strided_run,
        "clamp_bf16",
    )
}
