//! Elementwise unary / binary / ternary / cmp / cast / affine kernels
//! from `baracuda-kernels-sys`. Each kernel becomes a public Rust
//! function with the `(src*, layout*) -> Result<CudaStorageBytes>`
//! shape Fuel's dispatch wrappers expect.
//!
//! ## Contiguous vs strided dispatch
//!
//! Baracuda ships two flavors per kernel:
//! - `<sym>_run(numel, x, y, workspace, workspace_bytes, stream)` —
//!   contiguous fast path. Used when `layout` reports
//!   `is_contiguous_zero_offset` (no strided walk needed).
//! - `<sym>_strided_run(numel, rank, shape, stride_x, stride_y, ...)` —
//!   strided path. Used when the layout isn't contiguous (broadcast,
//!   transpose, view, etc.).
//!
//! The dispatcher picks per-call; Fuel's executor pre-Contiguize pass
//! usually arrives with contig inputs but the strided fallback keeps
//! correctness under all input shapes.
//!
//! ## Macros
//!
//! [`unary_f32`] / [`unary_f16`] / [`unary_bf16`] / [`unary_f64`] are
//! the public entry functions per (kind, dtype) pair. They're
//! generated by `unary_kernel!` from the kernel manifest — adding a
//! new unary kind is one manifest line, not one hand-written wrapper.

use std::sync::Arc;

use baracuda_kernels_sys as sys;
use fuel_core_types::{DType, Layout, Result, Shape};

use crate::byte_storage::CudaStorageBytes;

use super::scratch::Workspace;
use super::shape_strides::ShapeStridesI32;
use super::status::check;

/// Function-pointer aliases for baracuda's unary contig + strided
/// `_run` entry points. Used by the kernel manifest below to bind one
/// FFI symbol per (kind, dtype) pair without re-declaring the FFI
/// shape at each call site.
type UnaryContigRun = unsafe extern "C" fn(
    numel: i64,
    x: *const std::ffi::c_void,
    y: *mut std::ffi::c_void,
    workspace: *mut std::ffi::c_void,
    workspace_bytes: usize,
    stream: *mut std::ffi::c_void,
) -> i32;

type UnaryStridedRun = unsafe extern "C" fn(
    numel: i64,
    rank: i32,
    shape: *const i32,
    stride_x: *const i64,
    stride_y: *const i64,
    x: *const std::ffi::c_void,
    y: *mut std::ffi::c_void,
    workspace: *mut std::ffi::c_void,
    workspace_bytes: usize,
    stream: *mut std::ffi::c_void,
) -> i32;

type WorkspaceSizeFn = unsafe extern "C" fn(numel: i64) -> usize;

/// Core unary-elementwise driver. Handles the contig-vs-strided pick,
/// workspace alloc, FFI launch, status check, and stream sync.
///
/// `op_label` is the static name used in error messages — typically
/// the FFI symbol stem (`"unary_neg_f32"`).
///
/// Allocates a fresh output `CudaStorageBytes` of the same byte count
/// as `src`. Output layout matches input layout's *shape* (which is
/// what Fuel's executor reads back); the output buffer itself is
/// contiguous regardless of input layout.
fn unary_run(
    src: &CudaStorageBytes,
    src_layout: Option<&Layout>,
    contig_run: UnaryContigRun,
    strided_run: UnaryStridedRun,
    workspace_size_fn: Option<WorkspaceSizeFn>,
    op_label: &'static str,
    dtype_size_bytes: usize,
) -> Result<CudaStorageBytes> {
    // When the caller supplies a layout, trust it. When they don't
    // (binding-table callers that haven't migrated to layout-passing),
    // derive a 1-D contiguous layout from the byte buffer's length —
    // matches the existing PTX wrappers' implicit assumption.
    let derived_layout;
    let layout = match src_layout {
        Some(l) => l,
        None => {
            let elems = src.len_bytes() / dtype_size_bytes.max(1);
            derived_layout = Layout::contiguous(Shape::from_dims(&[elems]));
            &derived_layout
        }
    };
    let numel: i64 = layout.shape().elem_count() as i64;
    let out_bytes = (numel as usize) * dtype_size_bytes;
    let device = src.device().clone();
    if out_bytes == 0 {
        return CudaStorageBytes::alloc(&device, 0);
    }
    let out_buf = device.alloc_zeros::<u8>(out_bytes)?;
    let workspace_bytes = match workspace_size_fn {
        Some(f) => unsafe { f(numel) },
        None => 0,
    };
    let scratch = Workspace::alloc(&device, workspace_bytes)?;
    let stream = device.stream().as_raw() as *mut std::ffi::c_void;
    let x_ptr = src.buffer().as_raw().0 as *const std::ffi::c_void;
    let y_ptr = out_buf.as_raw().0 as *mut std::ffi::c_void;

    let contig = is_contiguous_zero_offset(layout);
    let status = if contig {
        // SAFETY: pointers + lengths validated above; stream lives on
        // CudaDevice for the call's duration; workspace is null when
        // workspace_bytes == 0 (per Workspace::alloc contract).
        unsafe {
            contig_run(
                numel,
                x_ptr,
                y_ptr,
                scratch.as_raw(),
                scratch.bytes(),
                stream,
            )
        }
    } else {
        // Strided fallback: pass shape + per-input/output strides
        // (output strides match the contiguous output buffer's layout).
        let out_layout = Layout::contiguous(layout.shape());
        let s = ShapeStridesI32::from_two(layout, &out_layout, op_label)?;
        // SAFETY: shape / stride buffers are owned by `s` for the
        // duration of the call; pointers above.
        unsafe {
            strided_run(
                numel,
                s.rank,
                s.shape.as_ptr(),
                s.stride_x.as_ptr(),
                s.stride_y.as_ptr(),
                x_ptr,
                y_ptr,
                scratch.as_raw(),
                scratch.bytes(),
                stream,
            )
        }
    };
    check(status, op_label)?;
    device.synchronize()?;
    Ok(CudaStorageBytes::from_parts(
        Arc::new(out_buf),
        device,
        out_bytes,
    ))
}

/// True when `layout` represents a contiguous, zero-offset view over
/// its underlying storage — i.e., the storage bytes match the
/// canonical row-major shape order with no stride gaps. Used to pick
/// the contig kernel fast path.
fn is_contiguous_zero_offset(layout: &Layout) -> bool {
    layout.start_offset() == 0 && layout.is_contiguous()
}

/// In-place unary driver. Reuses the same baracuda kernel symbol as
/// the non-inplace cousin but passes the target's pointer for BOTH
/// `x` (read) and `y` (write). Elementwise unary kernels write index
/// `i` after reading index `i` with no cross-thread aliasing, so
/// same-pointer dispatch is safe.
///
/// No strided variant — the executor's `WorkItemKind::InplaceKernel`
/// arm rejects strided targets up front, so we only need the contig
/// kernel path.
fn unary_inplace_run(
    target: &mut CudaStorageBytes,
    contig_run: UnaryContigRun,
    op_label: &'static str,
    dtype_size_bytes: usize,
) -> Result<()> {
    let numel: i64 = (target.len_bytes() / dtype_size_bytes.max(1)) as i64;
    if numel == 0 {
        return Ok(());
    }
    let device = target.device().clone();
    let scratch = Workspace::alloc(&device, 0)?;
    let stream = device.stream().as_raw() as *mut std::ffi::c_void;
    let ptr_mut = target.buffer().as_raw().0 as *mut std::ffi::c_void;
    let ptr_const = ptr_mut as *const std::ffi::c_void;
    // SAFETY: same buffer for x + y is safe for elementwise unary
    // kernels (no cross-thread aliasing); pointers / stream / scratch
    // validated above.
    let status = unsafe {
        contig_run(
            numel,
            ptr_const,
            ptr_mut,
            scratch.as_raw(),
            scratch.bytes(),
            stream,
        )
    };
    check(status, op_label)?;
    device.synchronize()?;
    Ok(())
}

/// Manifest macro for one (kind, dtype) unary entry. Emits a public
/// `pub fn <name>(src: &CudaStorageBytes, layout: &Layout) ->
/// Result<CudaStorageBytes>` that binds the FFI triple
/// `(<sym>_run, <sym>_strided_run, <sym>_workspace_size)` and the
/// dtype's byte size.
///
/// The `$ws` arm is `Some(fn)` when the kernel exposes a workspace
/// query; `None` when its workspace is always zero (most elementwise
/// unary ops).
macro_rules! unary_kernel {
    ($name:ident, $sys_stem:ident, $dtype_size:expr, $op_label:expr $(,)?) => {
        ::paste::paste! {
            #[doc = concat!("Baracuda unary `", $op_label, "` kernel.")]
            pub fn $name(
                src: &CudaStorageBytes,
                layout: Option<&Layout>,
            ) -> Result<CudaStorageBytes> {
                unary_run(
                    src,
                    layout,
                    sys::[<baracuda_kernels_ $sys_stem _run>],
                    sys::[<baracuda_kernels_ $sys_stem _strided_run>],
                    None,
                    $op_label,
                    $dtype_size,
                )
            }
        }
    };
}

// ---------------------------------------------------------------------------
// F32 unary kernels.
//
// Each entry binds a (Fuel-side name, baracuda FFI stem) pair. Adding
// a new unary kind is one line here.
// ---------------------------------------------------------------------------

unary_kernel!(unary_neg_f32, unary_neg_f32, 4, "unary_neg_f32");
unary_kernel!(unary_abs_f32, unary_abs_f32, 4, "unary_abs_f32");
unary_kernel!(unary_sign_f32, unary_sign_f32, 4, "unary_sign_f32");
unary_kernel!(unary_sqr_f32, unary_square_f32, 4, "unary_square_f32");
unary_kernel!(unary_sqrt_f32, unary_sqrt_f32, 4, "unary_sqrt_f32");
unary_kernel!(unary_rsqrt_f32, unary_rsqrt_f32, 4, "unary_rsqrt_f32");
unary_kernel!(unary_recip_f32, unary_reciprocal_f32, 4, "unary_reciprocal_f32");
unary_kernel!(unary_exp_f32, unary_exp_f32, 4, "unary_exp_f32");
unary_kernel!(unary_log_f32, unary_log_f32, 4, "unary_log_f32");
unary_kernel!(unary_sin_f32, unary_sin_f32, 4, "unary_sin_f32");
unary_kernel!(unary_cos_f32, unary_cos_f32, 4, "unary_cos_f32");
unary_kernel!(unary_tanh_f32, unary_tanh_f32, 4, "unary_tanh_f32");
unary_kernel!(unary_relu_f32, unary_relu_f32, 4, "unary_relu_f32");
unary_kernel!(unary_gelu_f32, unary_gelu_f32, 4, "unary_gelu_f32");
unary_kernel!(unary_gelu_tanh_f32, unary_gelu_tanh_f32, 4, "unary_gelu_tanh_f32");
unary_kernel!(unary_silu_f32, unary_silu_f32, 4, "unary_silu_f32");
unary_kernel!(unary_sigmoid_f32, unary_sigmoid_f32, 4, "unary_sigmoid_f32");

// Heaviside step — baracuda's native `unary_step_*` (Phase 31)
// matches Fuel's `StepElementwise` contract exactly: `(x > 0) ? 1 : 0`
// with NaN → 0. The kernel shipped in alpha.66 without a
// baracuda-kernels facade wrapper, but the sys-level FFI symbols are
// all present, which is the layer this manifest binds anyway.
unary_kernel!(unary_step_f32, unary_step_f32, 4, "unary_step_f32");

/// Manifest macro for one (kind, dtype) in-place unary entry. Emits a
/// `pub fn <name>(target: &mut CudaStorageBytes) -> Result<()>` that
/// calls `unary_inplace_run` against the matching baracuda contig
/// symbol. No strided variant per the in-place ops infrastructure's
/// "v1 contract: target must be contiguous + zero-offset".
macro_rules! unary_inplace_kernel {
    ($name:ident, $sys_stem:ident, $dtype_size:expr, $op_label:expr $(,)?) => {
        ::paste::paste! {
            #[doc = concat!("In-place baracuda unary `", $op_label, "` kernel — mutates `target`.")]
            pub fn $name(target: &mut CudaStorageBytes) -> Result<()> {
                unary_inplace_run(
                    target,
                    sys::[<baracuda_kernels_ $sys_stem _run>],
                    $op_label,
                    $dtype_size,
                )
            }
        }
    };
}

// In-place unary kernels — Phase 3e of in-place ops. Starter set
// matches Op::ReluInplace / SiluInplace / GeluInplace / TanhInplace /
// SigmoidInplace (the activations most likely to want in-place
// mutation in real model code). Full 4-dtype coverage (f32/f64/bf16/
// f16) — baracuda exposes all 20 per-dtype symbols via its forward
// `unary_*_run` family which the `unary_inplace_kernel!` macro
// reuses with same-pointer dispatch.
//
// The `gelu` entries bind baracuda's `unary_gelu_tanh_*` stems:
// Fuel's `OpKind::GeluInplace` is contractually the tanh
// approximation, while baracuda's plain `unary_gelu_*` is
// erf-flavored (that family backs `GeluErfElementwise` /
// `GeluErfInplace` instead).
unary_inplace_kernel!(unary_inplace_relu_f32,    unary_relu_f32,    4, "unary_inplace_relu_f32");
unary_inplace_kernel!(unary_inplace_silu_f32,    unary_silu_f32,    4, "unary_inplace_silu_f32");
unary_inplace_kernel!(unary_inplace_gelu_f32,    unary_gelu_tanh_f32, 4, "unary_inplace_gelu_f32");
unary_inplace_kernel!(unary_inplace_tanh_f32,    unary_tanh_f32,    4, "unary_inplace_tanh_f32");
unary_inplace_kernel!(unary_inplace_sigmoid_f32, unary_sigmoid_f32, 4, "unary_inplace_sigmoid_f32");

unary_inplace_kernel!(unary_inplace_relu_f64,    unary_relu_f64,    8, "unary_inplace_relu_f64");
unary_inplace_kernel!(unary_inplace_silu_f64,    unary_silu_f64,    8, "unary_inplace_silu_f64");
unary_inplace_kernel!(unary_inplace_gelu_f64,    unary_gelu_tanh_f64, 8, "unary_inplace_gelu_f64");
unary_inplace_kernel!(unary_inplace_tanh_f64,    unary_tanh_f64,    8, "unary_inplace_tanh_f64");
unary_inplace_kernel!(unary_inplace_sigmoid_f64, unary_sigmoid_f64, 8, "unary_inplace_sigmoid_f64");

unary_inplace_kernel!(unary_inplace_relu_bf16,    unary_relu_bf16,    2, "unary_inplace_relu_bf16");
unary_inplace_kernel!(unary_inplace_silu_bf16,    unary_silu_bf16,    2, "unary_inplace_silu_bf16");
unary_inplace_kernel!(unary_inplace_gelu_bf16,    unary_gelu_tanh_bf16, 2, "unary_inplace_gelu_bf16");
unary_inplace_kernel!(unary_inplace_tanh_bf16,    unary_tanh_bf16,    2, "unary_inplace_tanh_bf16");
unary_inplace_kernel!(unary_inplace_sigmoid_bf16, unary_sigmoid_bf16, 2, "unary_inplace_sigmoid_bf16");

unary_inplace_kernel!(unary_inplace_relu_f16,    unary_relu_f16,    2, "unary_inplace_relu_f16");
unary_inplace_kernel!(unary_inplace_silu_f16,    unary_silu_f16,    2, "unary_inplace_silu_f16");
unary_inplace_kernel!(unary_inplace_gelu_f16,    unary_gelu_tanh_f16, 2, "unary_inplace_gelu_f16");
unary_inplace_kernel!(unary_inplace_tanh_f16,    unary_tanh_f16,    2, "unary_inplace_tanh_f16");
unary_inplace_kernel!(unary_inplace_sigmoid_f16, unary_sigmoid_f16, 2, "unary_inplace_sigmoid_f16");

// In-place unary op family expansion (2026-05-30) — 16 new ops × 4
// dtypes. Each entry reuses the matching baracuda forward symbol
// with same-pointer dispatch (safe for elementwise unary — each
// thread reads x[i] before writing y[i], no cross-thread aliasing).
// FFI stems for sqr/recip use baracuda's `square`/`reciprocal`
// internal naming; matches the forward `unary_kernel!` aliasing.
unary_inplace_kernel!(unary_inplace_neg_f32,  unary_neg_f32,  4, "unary_inplace_neg_f32");
unary_inplace_kernel!(unary_inplace_neg_f64,  unary_neg_f64,  8, "unary_inplace_neg_f64");
unary_inplace_kernel!(unary_inplace_neg_bf16, unary_neg_bf16, 2, "unary_inplace_neg_bf16");
unary_inplace_kernel!(unary_inplace_neg_f16,  unary_neg_f16,  2, "unary_inplace_neg_f16");

unary_inplace_kernel!(unary_inplace_abs_f32,  unary_abs_f32,  4, "unary_inplace_abs_f32");
unary_inplace_kernel!(unary_inplace_abs_f64,  unary_abs_f64,  8, "unary_inplace_abs_f64");
unary_inplace_kernel!(unary_inplace_abs_bf16, unary_abs_bf16, 2, "unary_inplace_abs_bf16");
unary_inplace_kernel!(unary_inplace_abs_f16,  unary_abs_f16,  2, "unary_inplace_abs_f16");

unary_inplace_kernel!(unary_inplace_sqr_f32,  unary_square_f32,  4, "unary_inplace_sqr_f32");
unary_inplace_kernel!(unary_inplace_sqr_f64,  unary_square_f64,  8, "unary_inplace_sqr_f64");
unary_inplace_kernel!(unary_inplace_sqr_bf16, unary_square_bf16, 2, "unary_inplace_sqr_bf16");
unary_inplace_kernel!(unary_inplace_sqr_f16,  unary_square_f16,  2, "unary_inplace_sqr_f16");

unary_inplace_kernel!(unary_inplace_sqrt_f32,  unary_sqrt_f32,  4, "unary_inplace_sqrt_f32");
unary_inplace_kernel!(unary_inplace_sqrt_f64,  unary_sqrt_f64,  8, "unary_inplace_sqrt_f64");
unary_inplace_kernel!(unary_inplace_sqrt_bf16, unary_sqrt_bf16, 2, "unary_inplace_sqrt_bf16");
unary_inplace_kernel!(unary_inplace_sqrt_f16,  unary_sqrt_f16,  2, "unary_inplace_sqrt_f16");

unary_inplace_kernel!(unary_inplace_rsqrt_f32,  unary_rsqrt_f32,  4, "unary_inplace_rsqrt_f32");
unary_inplace_kernel!(unary_inplace_rsqrt_f64,  unary_rsqrt_f64,  8, "unary_inplace_rsqrt_f64");
unary_inplace_kernel!(unary_inplace_rsqrt_bf16, unary_rsqrt_bf16, 2, "unary_inplace_rsqrt_bf16");
unary_inplace_kernel!(unary_inplace_rsqrt_f16,  unary_rsqrt_f16,  2, "unary_inplace_rsqrt_f16");

unary_inplace_kernel!(unary_inplace_recip_f32,  unary_reciprocal_f32,  4, "unary_inplace_recip_f32");
unary_inplace_kernel!(unary_inplace_recip_f64,  unary_reciprocal_f64,  8, "unary_inplace_recip_f64");
unary_inplace_kernel!(unary_inplace_recip_bf16, unary_reciprocal_bf16, 2, "unary_inplace_recip_bf16");
unary_inplace_kernel!(unary_inplace_recip_f16,  unary_reciprocal_f16,  2, "unary_inplace_recip_f16");

unary_inplace_kernel!(unary_inplace_exp_f32,  unary_exp_f32,  4, "unary_inplace_exp_f32");
unary_inplace_kernel!(unary_inplace_exp_f64,  unary_exp_f64,  8, "unary_inplace_exp_f64");
unary_inplace_kernel!(unary_inplace_exp_bf16, unary_exp_bf16, 2, "unary_inplace_exp_bf16");
unary_inplace_kernel!(unary_inplace_exp_f16,  unary_exp_f16,  2, "unary_inplace_exp_f16");

unary_inplace_kernel!(unary_inplace_log_f32,  unary_log_f32,  4, "unary_inplace_log_f32");
unary_inplace_kernel!(unary_inplace_log_f64,  unary_log_f64,  8, "unary_inplace_log_f64");
unary_inplace_kernel!(unary_inplace_log_bf16, unary_log_bf16, 2, "unary_inplace_log_bf16");
unary_inplace_kernel!(unary_inplace_log_f16,  unary_log_f16,  2, "unary_inplace_log_f16");

unary_inplace_kernel!(unary_inplace_sin_f32,  unary_sin_f32,  4, "unary_inplace_sin_f32");
unary_inplace_kernel!(unary_inplace_sin_f64,  unary_sin_f64,  8, "unary_inplace_sin_f64");
unary_inplace_kernel!(unary_inplace_sin_bf16, unary_sin_bf16, 2, "unary_inplace_sin_bf16");
unary_inplace_kernel!(unary_inplace_sin_f16,  unary_sin_f16,  2, "unary_inplace_sin_f16");

unary_inplace_kernel!(unary_inplace_cos_f32,  unary_cos_f32,  4, "unary_inplace_cos_f32");
unary_inplace_kernel!(unary_inplace_cos_f64,  unary_cos_f64,  8, "unary_inplace_cos_f64");
unary_inplace_kernel!(unary_inplace_cos_bf16, unary_cos_bf16, 2, "unary_inplace_cos_bf16");
unary_inplace_kernel!(unary_inplace_cos_f16,  unary_cos_f16,  2, "unary_inplace_cos_f16");

unary_inplace_kernel!(unary_inplace_sign_f32,  unary_sign_f32,  4, "unary_inplace_sign_f32");
unary_inplace_kernel!(unary_inplace_sign_f64,  unary_sign_f64,  8, "unary_inplace_sign_f64");
unary_inplace_kernel!(unary_inplace_sign_bf16, unary_sign_bf16, 2, "unary_inplace_sign_bf16");
unary_inplace_kernel!(unary_inplace_sign_f16,  unary_sign_f16,  2, "unary_inplace_sign_f16");

unary_inplace_kernel!(unary_inplace_floor_f32,  unary_floor_f32,  4, "unary_inplace_floor_f32");
unary_inplace_kernel!(unary_inplace_floor_f64,  unary_floor_f64,  8, "unary_inplace_floor_f64");
unary_inplace_kernel!(unary_inplace_floor_bf16, unary_floor_bf16, 2, "unary_inplace_floor_bf16");
unary_inplace_kernel!(unary_inplace_floor_f16,  unary_floor_f16,  2, "unary_inplace_floor_f16");

unary_inplace_kernel!(unary_inplace_ceil_f32,  unary_ceil_f32,  4, "unary_inplace_ceil_f32");
unary_inplace_kernel!(unary_inplace_ceil_f64,  unary_ceil_f64,  8, "unary_inplace_ceil_f64");
unary_inplace_kernel!(unary_inplace_ceil_bf16, unary_ceil_bf16, 2, "unary_inplace_ceil_bf16");
unary_inplace_kernel!(unary_inplace_ceil_f16,  unary_ceil_f16,  2, "unary_inplace_ceil_f16");

unary_inplace_kernel!(unary_inplace_round_f32,  unary_round_f32,  4, "unary_inplace_round_f32");
unary_inplace_kernel!(unary_inplace_round_f64,  unary_round_f64,  8, "unary_inplace_round_f64");
unary_inplace_kernel!(unary_inplace_round_bf16, unary_round_bf16, 2, "unary_inplace_round_bf16");
unary_inplace_kernel!(unary_inplace_round_f16,  unary_round_f16,  2, "unary_inplace_round_f16");

unary_inplace_kernel!(unary_inplace_erf_f32,  unary_erf_f32,  4, "unary_inplace_erf_f32");
unary_inplace_kernel!(unary_inplace_erf_f64,  unary_erf_f64,  8, "unary_inplace_erf_f64");
unary_inplace_kernel!(unary_inplace_erf_bf16, unary_erf_bf16, 2, "unary_inplace_erf_bf16");
unary_inplace_kernel!(unary_inplace_erf_f16,  unary_erf_f16,  2, "unary_inplace_erf_f16");

unary_inplace_kernel!(unary_inplace_gelu_erf_f32,  unary_gelu_erf_f32,  4, "unary_inplace_gelu_erf_f32");
unary_inplace_kernel!(unary_inplace_gelu_erf_f64,  unary_gelu_erf_f64,  8, "unary_inplace_gelu_erf_f64");
unary_inplace_kernel!(unary_inplace_gelu_erf_bf16, unary_gelu_erf_bf16, 2, "unary_inplace_gelu_erf_bf16");
unary_inplace_kernel!(unary_inplace_gelu_erf_f16,  unary_gelu_erf_f16,  2, "unary_inplace_gelu_erf_f16");

// ---------------------------------------------------------------------------
// F64 / F16 / BF16 unary kernels.
//
// Same kinds as F32 above; the baracuda surface mirrors the four FP
// dtypes 1:1.
// ---------------------------------------------------------------------------

unary_kernel!(unary_neg_f64, unary_neg_f64, 8, "unary_neg_f64");
unary_kernel!(unary_neg_f16, unary_neg_f16, 2, "unary_neg_f16");
unary_kernel!(unary_neg_bf16, unary_neg_bf16, 2, "unary_neg_bf16");

unary_kernel!(unary_abs_f64, unary_abs_f64, 8, "unary_abs_f64");
unary_kernel!(unary_abs_f16, unary_abs_f16, 2, "unary_abs_f16");
unary_kernel!(unary_abs_bf16, unary_abs_bf16, 2, "unary_abs_bf16");

unary_kernel!(unary_sin_f64, unary_sin_f64, 8, "unary_sin_f64");
unary_kernel!(unary_sin_f16, unary_sin_f16, 2, "unary_sin_f16");
unary_kernel!(unary_sin_bf16, unary_sin_bf16, 2, "unary_sin_bf16");

unary_kernel!(unary_cos_f64, unary_cos_f64, 8, "unary_cos_f64");
unary_kernel!(unary_cos_f16, unary_cos_f16, 2, "unary_cos_f16");
unary_kernel!(unary_cos_bf16, unary_cos_bf16, 2, "unary_cos_bf16");

unary_kernel!(unary_exp_f64, unary_exp_f64, 8, "unary_exp_f64");
unary_kernel!(unary_exp_f16, unary_exp_f16, 2, "unary_exp_f16");
unary_kernel!(unary_exp_bf16, unary_exp_bf16, 2, "unary_exp_bf16");

unary_kernel!(unary_log_f64, unary_log_f64, 8, "unary_log_f64");
unary_kernel!(unary_log_f16, unary_log_f16, 2, "unary_log_f16");
unary_kernel!(unary_log_bf16, unary_log_bf16, 2, "unary_log_bf16");

unary_kernel!(unary_tanh_f64, unary_tanh_f64, 8, "unary_tanh_f64");
unary_kernel!(unary_tanh_f16, unary_tanh_f16, 2, "unary_tanh_f16");
unary_kernel!(unary_tanh_bf16, unary_tanh_bf16, 2, "unary_tanh_bf16");

unary_kernel!(unary_relu_f64, unary_relu_f64, 8, "unary_relu_f64");
unary_kernel!(unary_relu_f16, unary_relu_f16, 2, "unary_relu_f16");
unary_kernel!(unary_relu_bf16, unary_relu_bf16, 2, "unary_relu_bf16");

unary_kernel!(unary_gelu_f64, unary_gelu_f64, 8, "unary_gelu_f64");
unary_kernel!(unary_gelu_f16, unary_gelu_f16, 2, "unary_gelu_f16");
unary_kernel!(unary_gelu_bf16, unary_gelu_bf16, 2, "unary_gelu_bf16");

unary_kernel!(unary_gelu_tanh_f64, unary_gelu_tanh_f64, 8, "unary_gelu_tanh_f64");
unary_kernel!(unary_gelu_tanh_f16, unary_gelu_tanh_f16, 2, "unary_gelu_tanh_f16");
unary_kernel!(unary_gelu_tanh_bf16, unary_gelu_tanh_bf16, 2, "unary_gelu_tanh_bf16");

unary_kernel!(unary_step_f64, unary_step_f64, 8, "unary_step_f64");
unary_kernel!(unary_step_f16, unary_step_f16, 2, "unary_step_f16");
unary_kernel!(unary_step_bf16, unary_step_bf16, 2, "unary_step_bf16");

unary_kernel!(unary_silu_f64, unary_silu_f64, 8, "unary_silu_f64");
unary_kernel!(unary_silu_f16, unary_silu_f16, 2, "unary_silu_f16");
unary_kernel!(unary_silu_bf16, unary_silu_bf16, 2, "unary_silu_bf16");

unary_kernel!(unary_sigmoid_f64, unary_sigmoid_f64, 8, "unary_sigmoid_f64");
unary_kernel!(unary_sigmoid_f16, unary_sigmoid_f16, 2, "unary_sigmoid_f16");
unary_kernel!(unary_sigmoid_bf16, unary_sigmoid_bf16, 2, "unary_sigmoid_bf16");

unary_kernel!(unary_recip_f64, unary_reciprocal_f64, 8, "unary_reciprocal_f64");
unary_kernel!(unary_recip_f16, unary_reciprocal_f16, 2, "unary_reciprocal_f16");
unary_kernel!(unary_recip_bf16, unary_reciprocal_bf16, 2, "unary_reciprocal_bf16");

unary_kernel!(unary_sqr_f64, unary_square_f64, 8, "unary_square_f64");
unary_kernel!(unary_sqr_f16, unary_square_f16, 2, "unary_square_f16");
unary_kernel!(unary_sqr_bf16, unary_square_bf16, 2, "unary_square_bf16");

unary_kernel!(unary_sqrt_f64, unary_sqrt_f64, 8, "unary_sqrt_f64");
unary_kernel!(unary_sqrt_f16, unary_sqrt_f16, 2, "unary_sqrt_f16");
unary_kernel!(unary_sqrt_bf16, unary_sqrt_bf16, 2, "unary_sqrt_bf16");

/// Byte-size lookup for the dtypes baracuda's unary kernels accept.
/// Used by the registration helper below to pick the right output
/// stride for a given (op, dtype) entry.
pub fn dtype_byte_size(dt: DType) -> usize {
    match dt {
        DType::F32 => 4,
        DType::F64 => 8,
        DType::F16 | DType::BF16 => 2,
        _ => 0, // unsupported by this surface — caller validates.
    }
}
