// SPDX-License-Identifier: MIT OR Apache-2.0
//! GAP-335 detector: no CUDA `QMatMul` dispatcher binding exists.
//!
//! So a lazy `qmatmul` realized on a CUDA device never reaches a CUDA quantized
//! kernel (`CudaStorage::matmul_q4_0`, or the batched MMVQ runners). Registry
//! text once reasoned from the opposite assumption (GAP-154, GAP-031, and the
//! old wording of `fuel-core/tests/gap029_step0_q4_0_cuda_prefill_probe.rs`).
//! This test fails the day a binding is added, so that assumption can only
//! become true on purpose.
//!
//! Both arms are host-only, so every CI leg runs them. A binding-table read
//! would need `--features cuda`, which no CI leg builds.
//!
//! 1. CONTRACTS. Every `docs/kernel-contracts/**/*.fkc.md` in the git index is
//!    parsed, and no kernel whose effective backend is `Cuda` may name
//!    `QMatMul` or `QMATMUL`. Control: Metal's contract does name `QMatMul`.
//! 2. SOURCE. Every `fuel-dispatch/src/**/*.rs` in the git index is scanned for
//!    a non-comment `OpKind::QMatMul` or `FusedOps::QMATMUL` that is CUDA-gated:
//!    either the file is `#![cfg(feature = "cuda")]`, or `BackendId::Cuda`
//!    appears within a few lines. Controls: the predicate is checked on
//!    constructed input, and the scan reaches `baracuda_dispatch.rs`, the file
//!    that loads the CUDA contracts, and recognises its gate and includes.
//!
//! Blind spots: arm 2 cannot see a registration generated by a macro or spelled
//! through an aliased path, and arm 1 cannot see a CUDA contract kept outside
//! `docs/kernel-contracts`.

use std::path::{Path, PathBuf};
use std::process::Command;

use fuel_dispatch::fkc::parse_file;

const ON_FAILURE: &str = "a CUDA QMatMul binding now exists. GAP-335 is no longer true: \
     update it, re-open GAP-154 (the m>1 CUDA route now exists and needs its \
     numerical audit), re-point fuel-core/tests/gap029_step0_q4_0_cuda_prefill_probe.rs \
     at the new path, and recalibrate that test's tolerance for it";

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("fuel-dispatch sits one level below the repo root")
        .to_path_buf()
}

/// Files under `dir` in the git index, filtered by `suffix`. Enumerating the
/// index (not the disk) keeps other worktrees and build output out of scope.
fn indexed(dir: &str, suffix: &str) -> Vec<PathBuf> {
    let root = repo_root();
    let out = Command::new("git")
        .args(["ls-files", "--", dir])
        .current_dir(&root)
        .output()
        .expect("git must be available to enumerate the index");
    assert!(
        out.status.success(),
        "git ls-files failed: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8(out.stdout)
        .expect("git ls-files output is utf-8")
        .lines()
        .filter(|p| p.ends_with(suffix))
        .map(|p| root.join(p))
        .collect()
}

fn names_qmatmul(kind: Option<&str>) -> bool {
    matches!(kind, Some("QMatMul") | Some("QMATMUL"))
}

#[test]
fn no_kernel_contract_binds_qmatmul_on_cuda() {
    let files = indexed("docs/kernel-contracts", ".fkc.md");
    assert!(
        files.len() > 50,
        "only {} contract files found",
        files.len()
    );

    let mut cuda_kernels = 0;
    let mut metal_qmatmul = 0;
    let mut offenders = Vec::new();
    for path in &files {
        let text = std::fs::read_to_string(path).expect("read contract");
        let file = parse_file(&text).unwrap_or_else(|e| {
            panic!(
                "{} does not parse, so it cannot be checked: {e}",
                path.display()
            )
        });
        for k in &file.kernels {
            let backend = k
                .backend
                .as_deref()
                .unwrap_or(&file.front_matter.provider.backend);
            let qmatmul =
                names_qmatmul(k.op_kind.as_deref()) || names_qmatmul(k.fused_op.as_deref());
            match backend {
                "Cuda" => {
                    cuda_kernels += 1;
                    if qmatmul {
                        offenders.push(path.display().to_string());
                    }
                }
                "Metal" if qmatmul => metal_qmatmul += 1,
                _ => {}
            }
        }
    }
    // Controls: the arm can see CUDA kernels at all, and can see a QMatMul kernel.
    assert!(cuda_kernels > 0, "no CUDA kernel contracts were parsed");
    assert!(metal_qmatmul > 0, "the Metal QMatMul contract was not seen");
    assert!(offenders.is_empty(), "{ON_FAILURE}: {offenders:?}");
}

/// The text of `line` before any `//` comment.
fn code_part(line: &str) -> &str {
    line.split("//").next().unwrap_or("")
}

/// How many lines either side of a `QMatMul` mention to look for `BackendId::Cuda`.
const NEAR: usize = 12;

/// 1-based lines of `text` that mention `QMatMul` in code and are CUDA-gated:
/// the whole file is `#![cfg(feature = "cuda")]`, or `BackendId::Cuda` appears
/// in code within `NEAR` lines.
fn cuda_qmatmul_lines(text: &str) -> Vec<usize> {
    let code: Vec<&str> = text.lines().map(code_part).collect();
    let file_gated = text
        .lines()
        .any(|l| l.trim() == "#![cfg(feature = \"cuda\")]");
    (0..code.len())
        .filter(|&i| code[i].contains("OpKind::QMatMul") || code[i].contains("FusedOps::QMATMUL"))
        .filter(|&i| {
            let near = &code[i.saturating_sub(NEAR)..(i + NEAR + 1).min(code.len())];
            file_gated || near.iter().any(|l| l.contains("BackendId::Cuda"))
        })
        .map(|i| i + 1)
        .collect()
}

/// The predicate on constructed input: a CUDA registration is flagged, a
/// Vulkan one is not, and a comment does not count.
#[test]
fn the_source_predicate_flags_only_cuda_qmatmul() {
    let cuda =
        "fn reg(t: &mut T) {\n    t.register(OpKind::QMatMul, &[F32], BackendId::Cuda, k);\n}\n";
    assert_eq!(cuda_qmatmul_lines(cuda), vec![2]);
    let gated = "#![cfg(feature = \"cuda\")]\nfn f() { let _ = OpKind::QMatMul; }\n";
    assert_eq!(cuda_qmatmul_lines(gated), vec![2]);
    let vulkan = "t.register(OpKind::QMatMul, &[F32], BackendId::Vulkan, k);\n";
    assert!(cuda_qmatmul_lines(vulkan).is_empty());
    let comment = "// OpKind::QMatMul on BackendId::Cuda\n";
    assert!(cuda_qmatmul_lines(comment).is_empty());
}

#[test]
fn no_cuda_gated_source_registers_qmatmul() {
    let files = indexed("fuel-dispatch/src", ".rs");
    assert!(files.len() > 50, "only {} source files found", files.len());

    let mut saw_cuda_registration_file = false;
    let mut offenders = Vec::new();
    for path in &files {
        let text = std::fs::read_to_string(path).expect("read source");
        if path.ends_with("baracuda_dispatch.rs") {
            saw_cuda_registration_file = text
                .lines()
                .any(|l| l.trim() == "#![cfg(feature = \"cuda\")]")
                && text.contains("include_str!(\"../../docs/kernel-contracts/cuda/");
        }
        for line in cuda_qmatmul_lines(&text) {
            offenders.push(format!("{}:{line}", path.display()));
        }
    }
    // Control: the scan reached the CUDA registration file and recognised it.
    assert!(
        saw_cuda_registration_file,
        "the scan did not recognise baracuda_dispatch.rs as the CUDA registration file"
    );
    assert!(offenders.is_empty(), "{ON_FAILURE}: {offenders:?}");
}
