#[cfg(feature = "mkl")]
extern crate intel_mkl_src;

#[cfg(feature = "accelerate")]
extern crate accelerate_src;

use anyhow::{Error as E, Result};
use clap::{Parser, ValueEnum};
use std::io::Write;
use tokenizers::Tokenizer;

use fuel::lazy_quantized_qwen2::QuantizedQwen2Model;
use fuel::lazy_qwen2::Qwen2Config;

use fuel_examples::token_output_stream::TokenOutputStream;

const DEFAULT_PROMPT: &str = "Write a function to count prime numbers up to N. ";

#[derive(Clone, Debug, Copy, PartialEq, Eq, ValueEnum)]
enum Which {
    #[value(name = "0.5b")]
    W2_0_5b,
    #[value(name = "1.5b")]
    W2_1_5b,
    #[value(name = "7b")]
    W2_7b,
    #[value(name = "72b")]
    W2_72b,
    #[value(name = "deepseekr1-qwen7b")]
    DeepseekR1Qwen7B,
}

#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None)]
struct Args {
    /// GGUF file to load, typically a .gguf file generated by the quantize command from llama.cpp
    #[arg(long)]
    model: Option<String>,

    /// The initial prompt, use 'interactive' for entering multiple prompts in an interactive way
    /// and 'chat' for an interactive model where history of previous prompts and generated tokens
    /// is preserved.
    #[arg(long)]
    prompt: Option<String>,

    /// The length of the sample to generate (in tokens).
    #[arg(short = 'n', long, default_value_t = 1000)]
    sample_len: usize,

    /// The tokenizer config in json format.
    #[arg(long)]
    tokenizer: Option<String>,

    /// The temperature used to generate samples, use 0 for greedy sampling.
    #[arg(long, default_value_t = 0.8)]
    temperature: f64,

    /// Nucleus sampling probability cutoff.
    #[arg(long)]
    top_p: Option<f64>,

    /// Only sample among the top K samples.
    #[arg(long)]
    top_k: Option<usize>,

    /// The seed to use when generating random samples.
    #[arg(long, default_value_t = 299792458)]
    seed: u64,

    /// Enable tracing (generates a trace-timestamp.json file).
    #[arg(long)]
    tracing: bool,

    /// Run on CPU rather than GPU even if a GPU is available.
    #[arg(long)]
    cpu: bool,

    /// Penalty to be applied for repeating tokens, 1. means no penalty.
    #[arg(long, default_value_t = 1.1)]
    repeat_penalty: f32,

    /// The context size to consider for the repeat penalty.
    #[arg(long, default_value_t = 64)]
    repeat_last_n: usize,

    /// The model size to use.
    #[arg(long, default_value = "0.5b")]
    which: Which,
}

impl Args {
    fn tokenizer(&self) -> anyhow::Result<Tokenizer> {
        let tokenizer_path = match &self.tokenizer {
            Some(config) => std::path::PathBuf::from(config),
            None => {
                let api = hf_hub::api::sync::Api::new()?;
                let repo = match self.which {
                    Which::W2_0_5b => "Qwen/Qwen2-0.5B-Instruct",
                    Which::W2_1_5b => "Qwen/Qwen2-1.5B-Instruct",
                    Which::W2_7b => "Qwen/Qwen2-7B-Instruct",
                    Which::W2_72b => "Qwen/Qwen2-72B-Instruct",
                    Which::DeepseekR1Qwen7B => "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
                };
                let api = api.model(repo.to_string());
                api.get("tokenizer.json")?
            }
        };
        Tokenizer::from_file(tokenizer_path).map_err(anyhow::Error::msg)
    }

    fn model(&self) -> anyhow::Result<std::path::PathBuf> {
        let model_path = match &self.model {
            Some(config) => std::path::PathBuf::from(config),
            None => {
                let (repo, filename, revision) = match self.which {
                    Which::W2_0_5b => (
                        "Qwen/Qwen2-0.5B-Instruct-GGUF",
                        "qwen2-0_5b-instruct-q4_0.gguf",
                        "main",
                    ),
                    Which::W2_1_5b => (
                        "Qwen/Qwen2-1.5B-Instruct-GGUF",
                        "qwen2-1_5b-instruct-q4_0.gguf",
                        "main",
                    ),
                    Which::W2_7b => (
                        "Qwen/Qwen2-7B-Instruct-GGUF",
                        "qwen2-7b-instruct-q4_0.gguf",
                        "main",
                    ),
                    Which::W2_72b => (
                        "Qwen/Qwen2-72B-Instruct-GGUF",
                        "qwen2-72b-instruct-q4_0.gguf",
                        "main",
                    ),
                    Which::DeepseekR1Qwen7B => (
                        "unsloth/DeepSeek-R1-Distill-Qwen-7B-GGUF",
                        "DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf",
                        "main",
                    ),
                };
                let api = hf_hub::api::sync::Api::new()?;
                api.repo(hf_hub::Repo::with_revision(
                    repo.to_string(),
                    hf_hub::RepoType::Model,
                    revision.to_string(),
                ))
                .get(filename)?
            }
        };
        Ok(model_path)
    }
}

fn format_size(size_in_bytes: usize) -> String {
    if size_in_bytes < 1_000 {
        format!("{size_in_bytes}B")
    } else if size_in_bytes < 1_000_000 {
        format!("{:.2}KB", size_in_bytes as f64 / 1e3)
    } else if size_in_bytes < 1_000_000_000 {
        format!("{:.2}MB", size_in_bytes as f64 / 1e6)
    } else {
        format!("{:.2}GB", size_in_bytes as f64 / 1e9)
    }
}

/// Build a `Qwen2Config` by reading the GGUF metadata. Mirrors the
/// keys read by the eager `quantized_qwen2::ModelWeights::from_gguf`
/// path: `qwen2.*`. Some fields not present in the GGUF (vocab_size,
/// intermediate_size, sliding-window switches, tie_word_embeddings)
/// are derived from tensor shapes / file-presence.
fn qwen2_cfg_from_gguf(mc: &fuel::quantized::gguf_mmap::MmapedContent) -> Result<Qwen2Config> {
    let content = mc.content();
    let md = &content.metadata;
    let md_get = |s: &str| -> Result<&fuel::quantized::gguf_file::Value> {
        md.get(s).ok_or_else(|| E::msg(format!("missing GGUF metadata key {s:?}")))
    };

    let num_attention_heads =
        md_get("qwen2.attention.head_count")?.to_u32().map_err(E::msg)? as usize;
    let num_key_value_heads =
        md_get("qwen2.attention.head_count_kv")?.to_u32().map_err(E::msg)? as usize;
    let hidden_size =
        md_get("qwen2.embedding_length")?.to_u32().map_err(E::msg)? as usize;
    let max_position_embeddings =
        md_get("qwen2.context_length")?.to_u32().map_err(E::msg)? as usize;
    let num_hidden_layers =
        md_get("qwen2.block_count")?.to_u32().map_err(E::msg)? as usize;
    let rms_norm_eps = md_get("qwen2.attention.layer_norm_rms_epsilon")?
        .to_f32()
        .map_err(E::msg)? as f64;
    let rope_theta = md
        .get("qwen2.rope.freq_base")
        .and_then(|m| m.to_f32().ok())
        .unwrap_or(10_000.0_f32) as f64;
    let intermediate_size = match md
        .get("qwen2.feed_forward_length")
        .and_then(|m| m.to_u32().ok())
    {
        Some(v) => v as usize,
        None => {
            // Fall back to the ffn_gate.weight tensor shape:
            // [intermediate_size, hidden_size] in GGUF.
            let info = content
                .tensor_infos
                .get("blk.0.ffn_gate.weight")
                .ok_or_else(|| {
                    E::msg("missing blk.0.ffn_gate.weight to infer intermediate_size")
                })?;
            info.shape.dims()[0]
        }
    };

    // Derive vocab_size from token_embd.weight shape: [vocab_size, hidden].
    let vocab_size = {
        let info = content
            .tensor_infos
            .get("token_embd.weight")
            .ok_or_else(|| E::msg("missing token_embd.weight"))?;
        let dims = info.shape.dims();
        if dims.len() != 2 || dims[1] != hidden_size {
            return Err(E::msg(format!(
                "token_embd.weight has unexpected shape {dims:?}; expected [vocab_size, {hidden_size}]"
            )));
        }
        dims[0]
    };

    // Qwen2 GGUF releases don't enable sliding-window attention by
    // default — the field exists in HF configs but llama.cpp tracks it
    // separately. Mirror the eager path and leave the window disabled.
    let sliding_window = max_position_embeddings;
    let max_window_layers = num_hidden_layers;
    let use_sliding_window = false;

    // Tied embeddings: if there is no explicit `output.weight` in the
    // GGUF, the model ties lm_head to token_embd (Qwen2-0.5B / 1.5B do
    // this). Larger variants ship a separate `output.weight`.
    let tie_word_embeddings = !content.tensor_infos.contains_key("output.weight");

    Ok(Qwen2Config {
        vocab_size,
        hidden_size,
        intermediate_size,
        num_hidden_layers,
        num_attention_heads,
        num_key_value_heads,
        max_position_embeddings,
        sliding_window,
        max_window_layers,
        use_sliding_window,
        rope_theta,
        rms_norm_eps,
        tie_word_embeddings,
    })
}

fn main() -> anyhow::Result<()> {
    use tracing_chrome::ChromeLayerBuilder;
    use tracing_subscriber::prelude::*;

    let args = Args::parse();
    let _guard = if args.tracing {
        let (chrome_layer, guard) = ChromeLayerBuilder::new().build();
        tracing_subscriber::registry().with(chrome_layer).init();
        Some(guard)
    } else {
        None
    };

    println!(
        "avx: {}, neon: {}, simd128: {}, f16c: {}",
        fuel::utils::with_avx(),
        fuel::utils::with_neon(),
        fuel::utils::with_simd128(),
        fuel::utils::with_f16c()
    );
    println!(
        "temp: {:.2} repeat-penalty: {:.2} repeat-last-n: {}",
        args.temperature, args.repeat_penalty, args.repeat_last_n
    );

    let model_path = args.model()?;
    let start = std::time::Instant::now();
    let _device = fuel_examples::device(args.cpu)?;

    // First open: read GGUF metadata + tensor table so we can build the
    // Qwen2Config. `QuantizedQwen2Model::from_gguf` reopens the file
    // internally with its own mmap.
    let mmaped = fuel::quantized::gguf_mmap::MmapedContent::from_path(&model_path)
        .map_err(|e| e.with_path(&model_path))?;
    let header_done = start.elapsed();
    let mut total_size_in_bytes = 0;
    for (_, tensor) in mmaped.content().tensor_infos.iter() {
        let elem_count = tensor.shape.elem_count();
        total_size_in_bytes +=
            elem_count * tensor.ggml_dtype.type_size() / tensor.ggml_dtype.block_size();
    }
    println!(
        "mmapped {:?} tensors ({}); header in {:.2}s",
        mmaped.content().tensor_infos.len(),
        &format_size(total_size_in_bytes),
        header_done.as_secs_f32(),
    );

    let cfg = qwen2_cfg_from_gguf(&mmaped)?;
    drop(mmaped);

    let model = QuantizedQwen2Model::from_gguf(&model_path, &cfg)
        .map_err(|e| E::msg(format!("from_gguf: {e}")))?;
    println!("model built in {:.2}s total", start.elapsed().as_secs_f32());

    let tokenizer = args.tokenizer()?;
    let mut tos = TokenOutputStream::new(tokenizer);
    let prompt_str = args
        .prompt
        .clone()
        .unwrap_or_else(|| DEFAULT_PROMPT.to_string());

    let prompt_str = match args.which {
        Which::DeepseekR1Qwen7B => format!("<｜User｜>{prompt_str}<｜Assistant｜>"),
        _ => format!("<|im_start|>user\n{prompt_str}<|im_end|>\n<|im_start|>assistant\n"),
    };
    print!("formatted instruct prompt: {}", &prompt_str);
    let tokens = tos
        .tokenizer()
        .encode(prompt_str, true)
        .map_err(anyhow::Error::msg)?;
    let tokens = tokens.get_ids().to_vec();
    let to_sample = args.sample_len.saturating_sub(1);
    let mut all_tokens: Vec<u32> = vec![];

    let start_prompt_processing = std::time::Instant::now();
    // Prompt prefill: feed the full prompt in a single forward, take
    // the last position's logits, and sample.
    let mut next_token = {
        let logits_lazy = model
            .forward(&tokens, 0)
            .map_err(|e| E::msg(format!("forward (prompt): {e}")))?;
        let logits_flat = logits_lazy.realize_f32();
        let vocab = cfg.vocab_size;
        let seq = tokens.len();
        let last_off = (seq - 1) * vocab;
        let last_logits: Vec<f32> = logits_flat[last_off..last_off + vocab].to_vec();
        sample(
            &last_logits,
            args.temperature as f32,
            args.top_k,
            args.top_p.map(|p| p as f32),
            args.seed,
        )
    };
    let prompt_dt = start_prompt_processing.elapsed();
    all_tokens.push(next_token);
    if let Some(t) = tos.next_token(next_token)? {
        print!("{t}");
        std::io::stdout().flush()?;
    }

    let eos_token = match args.which {
        Which::DeepseekR1Qwen7B => "<｜end▁of▁sentence｜>",
        _ => "<|im_end|>",
    };

    let eos_token = *tos.tokenizer().get_vocab(true).get(eos_token).unwrap();
    let start_post_prompt = std::time::Instant::now();
    let mut sampled = 0;
    // Generation loop: build the full token sequence (prompt + so-far
    // generated) and forward over it on each step. `start_pos = 0`
    // because the lazy model does not yet thread an external KV cache.
    let mut full_tokens: Vec<u32> = tokens.clone();
    full_tokens.push(next_token);
    for index in 0..to_sample {
        let logits_lazy = model
            .forward(&full_tokens, 0)
            .map_err(|e| E::msg(format!("forward (gen): {e}")))?;
        let logits_flat = logits_lazy.realize_f32();
        let vocab = cfg.vocab_size;
        let seq = full_tokens.len();
        let last_off = (seq - 1) * vocab;
        let mut last_logits: Vec<f32> = logits_flat[last_off..last_off + vocab].to_vec();
        if args.repeat_penalty != 1.0 {
            let start_at = all_tokens.len().saturating_sub(args.repeat_last_n);
            apply_repeat_penalty(&mut last_logits, args.repeat_penalty, &all_tokens[start_at..]);
        }
        next_token = sample(
            &last_logits,
            args.temperature as f32,
            args.top_k,
            args.top_p.map(|p| p as f32),
            args.seed.wrapping_add(index as u64 + 1),
        );
        all_tokens.push(next_token);
        full_tokens.push(next_token);
        if let Some(t) = tos.next_token(next_token)? {
            print!("{t}");
            std::io::stdout().flush()?;
        }
        sampled += 1;
        if next_token == eos_token {
            break;
        };
    }
    if let Some(rest) = tos.decode_rest().map_err(fuel::Error::msg)? {
        print!("{rest}");
    }
    std::io::stdout().flush()?;
    let dt = start_post_prompt.elapsed();
    println!(
        "\n\n{:4} prompt tokens processed: {:.2} token/s",
        tokens.len(),
        tokens.len() as f64 / prompt_dt.as_secs_f64(),
    );
    println!(
        "{sampled:4} tokens generated: {:.2} token/s",
        sampled as f64 / dt.as_secs_f64(),
    );
    Ok(())
}

fn apply_repeat_penalty(logits: &mut [f32], penalty: f32, context: &[u32]) {
    let mut seen = std::collections::HashSet::new();
    for &t in context {
        if !seen.insert(t) {
            continue;
        }
        let idx = t as usize;
        if idx < logits.len() {
            let v = logits[idx];
            logits[idx] = if v >= 0.0 { v / penalty } else { v * penalty };
        }
    }
}

fn sample(
    logits: &[f32],
    temperature: f32,
    top_k: Option<usize>,
    top_p: Option<f32>,
    seed: u64,
) -> u32 {
    if temperature <= 0.0 {
        let mut best_i = 0usize;
        let mut best = logits[0];
        for (i, &v) in logits.iter().enumerate().skip(1) {
            if v > best {
                best = v;
                best_i = i;
            }
        }
        return best_i as u32;
    }
    let max_l = logits.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
    let inv_t = 1.0 / temperature.max(1e-6);
    let mut probs: Vec<f32> = logits.iter().map(|&x| ((x - max_l) * inv_t).exp()).collect();
    let sum: f32 = probs.iter().sum();
    for p in &mut probs {
        *p /= sum.max(1e-30);
    }
    let mut idx: Vec<usize> = (0..probs.len()).collect();
    idx.sort_unstable_by(|&a, &b| probs[b].partial_cmp(&probs[a]).unwrap());
    let mut keep_mask: Vec<bool> = vec![true; probs.len()];
    if let Some(k) = top_k {
        for &i in idx.iter().skip(k) {
            keep_mask[i] = false;
        }
    }
    if let Some(p_cut) = top_p {
        let mut cum2 = 0.0;
        let mut allow = true;
        for &i in &idx {
            if !keep_mask[i] {
                continue;
            }
            if !allow {
                keep_mask[i] = false;
                continue;
            }
            cum2 += probs[i];
            if cum2 >= p_cut {
                allow = false;
            }
        }
    }
    let mut filtered: Vec<f32> = probs
        .iter()
        .enumerate()
        .map(|(i, p)| if keep_mask[i] { *p } else { 0.0 })
        .collect();
    let s: f32 = filtered.iter().sum();
    if s > 0.0 {
        for v in &mut filtered {
            *v /= s;
        }
    } else {
        return 0;
    }
    let mut state = seed.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
    state ^= state >> 33;
    state = state.wrapping_mul(0xff51_afd7_ed55_8ccd);
    state ^= state >> 33;
    let r = (state as f32) / (u64::MAX as f32);
    let mut cum = 0.0;
    for (i, p) in filtered.iter().enumerate() {
        cum += *p;
        if r <= cum {
            return i as u32;
        }
    }
    (filtered.len() - 1) as u32
}
