//! FlashAttn backward — produces dQ, dK, dV given (Q, K, V, dO, [alibi]).
//!
//! Three separate FusedOpId variants (FLASH_ATTN_BACKWARD_Q/K/V) share
//! one `FusedOpParams::FlashAttnBackward` payload. Each variant's
//! output shape matches the corresponding forward input's shape:
//!   Q-backward → Q-shape, K-backward → K-shape, V-backward → V-shape.
//!
//! v1 design: each backward variant recomputes the softmax state
//! independently. A single-launch / multi-output variant that shares
//! the recompute pass across all three gradients is a follow-up; the
//! current design wins on Op-IR-additivity (no multi-output enum
//! infrastructure) at the cost of 3× recompute on the math-definition
//! CPU reference. GPU kernels can fuse the recompute when they ship.
//!
//! Pattern recognition is `SubgraphPattern::None` — no autogenerated
//! lowering rule fires this op family from primitives; autograd emits
//! it directly when computing gradients through a FlashAttn forward.

use crate::registry::{
    BackwardKind, FusedOpEntry, FusedOpFamily, FusedOpParams, FusedOps,
    PatternMatch, SubgraphPattern,
};
use crate::{Graph, NodeId};
use fuel_ir::{DType, Shape};

/// Metadata-side registry entry for FlashAttnBackwardQ.
pub fn entry_q() -> FusedOpEntry {
    FusedOpEntry {
        id:         FusedOps::FLASH_ATTN_BACKWARD_Q,
        name:       "FlashAttnBackwardQ",
        family:     FusedOpFamily::Attention,
        pattern:    SubgraphPattern::Callable(no_pattern),
        decompose:  no_decompose,
        backward:   BackwardKind::NotDifferentiable,
        shape_rule: shape_rule_q,
        dtype_rule,
        output_views: None,
    }
}

/// Metadata-side registry entry for FlashAttnBackwardK.
pub fn entry_k() -> FusedOpEntry {
    FusedOpEntry {
        id:         FusedOps::FLASH_ATTN_BACKWARD_K,
        name:       "FlashAttnBackwardK",
        family:     FusedOpFamily::Attention,
        pattern:    SubgraphPattern::Callable(no_pattern),
        decompose:  no_decompose,
        backward:   BackwardKind::NotDifferentiable,
        shape_rule: shape_rule_k,
        dtype_rule,
        output_views: None,
    }
}

/// Metadata-side registry entry for FlashAttnBackwardV.
pub fn entry_v() -> FusedOpEntry {
    FusedOpEntry {
        id:         FusedOps::FLASH_ATTN_BACKWARD_V,
        name:       "FlashAttnBackwardV",
        family:     FusedOpFamily::Attention,
        pattern:    SubgraphPattern::Callable(no_pattern),
        decompose:  no_decompose,
        backward:   BackwardKind::NotDifferentiable,
        shape_rule: shape_rule_v,
        dtype_rule,
        output_views: None,
    }
}

/// Shape rule for dQ: matches input 0 (Q).
fn shape_rule_q(input_shapes: &[Shape], _params: &FusedOpParams) -> Shape {
    debug_assert!(
        input_shapes.len() == 4 || input_shapes.len() == 5,
        "FlashAttnBackwardQ takes 4-5 inputs (q, k, v, do, [alibi])",
    );
    input_shapes[0].clone()
}

/// Shape rule for dK: matches input 1 (K).
fn shape_rule_k(input_shapes: &[Shape], _params: &FusedOpParams) -> Shape {
    debug_assert!(
        input_shapes.len() == 4 || input_shapes.len() == 5,
        "FlashAttnBackwardK takes 4-5 inputs (q, k, v, do, [alibi])",
    );
    input_shapes[1].clone()
}

/// Shape rule for dV: matches input 2 (V).
fn shape_rule_v(input_shapes: &[Shape], _params: &FusedOpParams) -> Shape {
    debug_assert!(
        input_shapes.len() == 4 || input_shapes.len() == 5,
        "FlashAttnBackwardV takes 4-5 inputs (q, k, v, do, [alibi])",
    );
    input_shapes[2].clone()
}

/// Dtype rule: gradients preserve the forward dtype. All inputs share
/// dtype; output matches input 0 (Q).
fn dtype_rule(input_dtypes: &[DType], _params: &FusedOpParams) -> DType {
    debug_assert!(
        input_dtypes.len() == 4 || input_dtypes.len() == 5,
        "FlashAttnBackward* takes 4-5 inputs",
    );
    input_dtypes[0]
}

/// No pattern recognition — autograd emits these ops directly.
fn no_pattern(_g: &Graph, _root: NodeId) -> Option<PatternMatch> {
    None
}

/// No primitive decomposition. FlashAttn backward as a sum of
/// primitive ops would re-materialize the [Sq, Sk] score matrix the
/// fused form exists to avoid.
fn no_decompose(_g: &mut Graph, id: NodeId, _params: &FusedOpParams) -> NodeId {
    panic!(
        "FlashAttnBackward* has no primitive decomposition (node {id:?}); \
         every backend must register a kernel for these ops.",
    );
}
