#[cfg(feature = "mkl")]
extern crate intel_mkl_src;

#[cfg(feature = "accelerate")]
extern crate accelerate_src;

use anyhow::{Error as E, Result};
use clap::{Parser, ValueEnum};
use std::io::Write;
use tokenizers::Tokenizer;

use fuel::lazy_quantized_qwen3_moe::QuantizedQwen3MoeModel;
use fuel::lazy_qwen3_moe::Qwen3MoeConfig;
use fuel::Tensor;
use fuel::DType;
use fuel_transformers::generation::{LogitsProcessor, Sampling};

use fuel_examples::token_output_stream::TokenOutputStream;

const DEFAULT_PROMPT: &str = "Write a Rust function to calculate the factorial of a given number.";

#[derive(Clone, Debug, Copy, PartialEq, Eq, ValueEnum)]
enum Which {
    #[value(name = "16b_q2k")]
    W3_16bQ2K,
    #[value(name = "16b_q4k")]
    W3_16bQ4K,
    #[value(name = "16b_q6k")]
    W3_16bQ6K,
    #[value(name = "16b_q80")]
    W3_16bQ80,
    #[value(name = "32b_q2k")]
    W3_32bQ2K,
    #[value(name = "32b_q4k")]
    W3_32bQ4K,
    #[value(name = "32b_q6k")]
    W3_32bQ6K,
    #[value(name = "32b_q80")]
    W3_32bQ80,
}

#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None)]
struct Args {
    /// GGUF file to load, typically a .gguf file generated by the quantize command from llama.cpp
    #[arg(long)]
    model: Option<String>,

    /// The initial prompt, use 'interactive' for entering multiple prompts in an interactive way
    /// and 'chat' for an interactive model where history of previous prompts and generated tokens
    /// is preserved.
    #[arg(long)]
    prompt: Option<String>,

    /// The length of the sample to generate (in tokens).
    #[arg(short = 'n', long, default_value_t = 1000)]
    sample_len: usize,

    /// The tokenizer config in json format.
    #[arg(long)]
    tokenizer: Option<String>,

    /// The temperature used to generate samples, use 0 for greedy sampling.
    #[arg(long, default_value_t = 0.8)]
    temperature: f64,

    /// Nucleus sampling probability cutoff.
    #[arg(long)]
    top_p: Option<f64>,

    /// Only sample among the top K samples.
    #[arg(long)]
    top_k: Option<usize>,

    /// The seed to use when generating random samples.
    #[arg(long, default_value_t = 299792458)]
    seed: u64,

    /// Enable tracing (generates a trace-timestamp.json file).
    #[arg(long)]
    tracing: bool,

    /// Process prompt elements separately.
    #[arg(long)]
    split_prompt: bool,

    /// Run on CPU rather than GPU even if a GPU is available.
    #[arg(long)]
    cpu: bool,

    /// Penalty to be applied for repeating tokens, 1. means no penalty.
    #[arg(long, default_value_t = 1.1)]
    repeat_penalty: f32,

    /// The context size to consider for the repeat penalty.
    #[arg(long, default_value_t = 64)]
    repeat_last_n: usize,

    /// The model size to use.
    #[arg(long, default_value = "16b_q2k")]
    which: Which,

    #[arg(long, default_value = "bf16")]
    dtype: String,
}

impl Args {
    fn tokenizer(&self) -> anyhow::Result<Tokenizer> {
        let tokenizer_path = match &self.tokenizer {
            Some(config) => std::path::PathBuf::from(config),
            None => {
                let api = hf_hub::api::sync::Api::new()?;
                let repo = "Qwen/Qwen3-30B-A3B-Instruct-2507";
                let api = api.model(repo.to_string());
                api.get("tokenizer.json")?
            }
        };
        Tokenizer::from_file(tokenizer_path).map_err(anyhow::Error::msg)
    }

    fn model(&self) -> anyhow::Result<std::path::PathBuf> {
        let model_path = match &self.model {
            Some(config) => std::path::PathBuf::from(config),
            None => {
                let (repo, filename, revision) = match self.which {
                    Which::W3_16bQ2K => (
                        "unsloth/Qwen3-16B-A3B-GGUF",
                        "Qwen3-16B-A3B-Q2_K.gguf",
                        "main",
                    ),
                    Which::W3_16bQ4K => (
                        "unsloth/Qwen3-16B-A3B-GGUF",
                        "Qwen3-16B-A3B-Q4_K_M.gguf",
                        "main",
                    ),
                    Which::W3_16bQ6K => (
                        "unsloth/Qwen3-16B-A3B-GGUF",
                        "Qwen3-16B-A3B-Q6_K.gguf",
                        "main",
                    ),
                    Which::W3_16bQ80 => (
                        "unsloth/Qwen3-16B-A3B-GGUF",
                        "Qwen3-16B-A3B-Q8_0.gguf",
                        "main",
                    ),

                    Which::W3_32bQ2K => (
                        "unsloth/Qwen3-30B-A3B-Instruct-2507-GGUF",
                        "Qwen3-30B-A3B-Instruct-2507-Q2_K.gguf",
                        "main",
                    ),
                    Which::W3_32bQ4K => (
                        "unsloth/Qwen3-30B-A3B-Instruct-2507-GGUF",
                        "Qwen3-30B-A3B-Instruct-2507-Q4_K_M.gguf",
                        "main",
                    ),
                    Which::W3_32bQ6K => (
                        "unsloth/Qwen3-30B-A3B-Instruct-2507-GGUF",
                        "Qwen3-30B-A3B-Instruct-2507-Q6_K.gguf",
                        "main",
                    ),
                    Which::W3_32bQ80 => (
                        "unsloth/Qwen3-30B-A3B-Instruct-2507-GGUF",
                        "Qwen3-30B-A3B-Instruct-2507-Q8_0.gguf",
                        "main",
                    ),
                };
                let api = hf_hub::api::sync::Api::new()?;
                api.repo(hf_hub::Repo::with_revision(
                    repo.to_string(),
                    hf_hub::RepoType::Model,
                    revision.to_string(),
                ))
                .get(filename)?
            }
        };
        Ok(model_path)
    }
}

fn format_size(size_in_bytes: usize) -> String {
    if size_in_bytes < 1_000 {
        format!("{size_in_bytes}B")
    } else if size_in_bytes < 1_000_000 {
        format!("{:.2}KB", size_in_bytes as f64 / 1e3)
    } else if size_in_bytes < 1_000_000_000 {
        format!("{:.2}MB", size_in_bytes as f64 / 1e6)
    } else {
        format!("{:.2}GB", size_in_bytes as f64 / 1e9)
    }
}

/// Build a [`Qwen3MoeConfig`] from the GGUF metadata. Mirrors the eager
/// `GGUFQWenMoE::from_gguf` config-parse but emits the lazy config type.
fn qwen3_moe_config_from_gguf(
    mc: &fuel::quantized::gguf_mmap::MmapedContent,
) -> anyhow::Result<Qwen3MoeConfig> {
    let md = mc.metadata();
    let md_get = |s: &str| -> anyhow::Result<&fuel::quantized::gguf_file::Value> {
        md.get(s).ok_or_else(|| E::msg(format!("missing gguf metadata {s:?}")))
    };
    let arch = md_get("general.architecture")?
        .to_string()
        .map_err(|e| E::msg(format!("general.architecture: {e}")))?
        .clone();

    let num_attention_heads = md_get(&format!("{arch}.attention.head_count"))?
        .to_u32()
        .map_err(|e| E::msg(format!("{arch}.attention.head_count: {e}")))? as usize;
    let num_key_value_heads = md_get(&format!("{arch}.attention.head_count_kv"))?
        .to_u32()
        .map_err(|e| E::msg(format!("{arch}.attention.head_count_kv: {e}")))? as usize;
    let hidden_size = md_get(&format!("{arch}.embedding_length"))?
        .to_u32()
        .map_err(|e| E::msg(format!("{arch}.embedding_length: {e}")))? as usize;
    let head_dim = match md.get(&format!("{arch}.attention.key_length")) {
        Some(v) => v
            .to_u32()
            .map_err(|e| E::msg(format!("{arch}.attention.key_length: {e}")))?
            as usize,
        None => hidden_size / num_attention_heads,
    };
    let max_position_embeddings = md_get(&format!("{arch}.context_length"))?
        .to_u32()
        .map_err(|e| E::msg(format!("{arch}.context_length: {e}")))? as usize;
    let num_hidden_layers = md_get(&format!("{arch}.block_count"))?
        .to_u32()
        .map_err(|e| E::msg(format!("{arch}.block_count: {e}")))? as usize;
    let rms_norm_eps = md_get(&format!("{arch}.attention.layer_norm_rms_epsilon"))?
        .to_f32()
        .map_err(|e| E::msg(format!("{arch}.attention.layer_norm_rms_epsilon: {e}")))?
        as f64;
    let rope_theta = md
        .get(&format!("{arch}.rope.freq_base"))
        .and_then(|v| v.to_f32().ok())
        .unwrap_or(10_000.0) as f64;

    let moe_intermediate_size = md_get(&format!("{arch}.expert_feed_forward_length"))?
        .to_u32()
        .map_err(|e| E::msg(format!("{arch}.expert_feed_forward_length: {e}")))?
        as usize;
    let num_experts = md_get(&format!("{arch}.expert_count"))?
        .to_u32()
        .map_err(|e| E::msg(format!("{arch}.expert_count: {e}")))? as usize;
    let num_experts_per_tok = md_get(&format!("{arch}.expert_used_count"))?
        .to_u32()
        .map_err(|e| E::msg(format!("{arch}.expert_used_count: {e}")))? as usize;
    let intermediate_size = md
        .get(&format!("{arch}.feed_forward_length"))
        .and_then(|v| v.to_u32().ok())
        .map(|x| x as usize)
        .unwrap_or(moe_intermediate_size);

    // vocab_size: inferred from the token_embd.weight shape ([vocab, hidden]).
    let vocab_size = {
        let info = mc.content().tensor_infos.get("token_embd.weight").ok_or_else(
            || E::msg("missing tensor token_embd.weight in GGUF for vocab_size inference"),
        )?;
        let dims = info.shape.dims();
        if dims.len() < 2 {
            anyhow::bail!(
                "token_embd.weight has rank {}, expected at least 2 for vocab_size inference",
                dims.len()
            );
        }
        // llama.cpp convention: token_embd.weight is [hidden_size, vocab_size]
        // in dimensions order; vocab_size is the last dim.
        dims[dims.len() - 1]
    };

    // Qwen3 ships attention biases in the base config; the GGUF
    // exporter typically writes them under `blk.{i}.attn_q.bias` etc.
    // Probe one tensor name to decide.
    let attention_bias = mc
        .content()
        .tensor_infos
        .contains_key("blk.0.attn_q.bias");

    Ok(Qwen3MoeConfig {
        vocab_size,
        hidden_size,
        intermediate_size,
        num_hidden_layers,
        num_attention_heads,
        head_dim,
        attention_bias,
        num_key_value_heads,
        max_position_embeddings,
        sliding_window: None,
        max_window_layers: 0,
        use_sliding_window: false,
        rope_theta,
        rms_norm_eps,
        // GGUF Qwen3-MoE releases generally use every-layer-MoE
        // (decoder_sparse_step = 1). The eager path defaults to the
        // same fallback.
        decoder_sparse_step: 1,
        moe_intermediate_size,
        num_experts,
        num_experts_per_tok,
    })
}

fn main() -> anyhow::Result<()> {
    use tracing_chrome::ChromeLayerBuilder;
    use tracing_subscriber::prelude::*;

    let args = Args::parse();
    let _guard = if args.tracing {
        let (chrome_layer, guard) = ChromeLayerBuilder::new().build();
        tracing_subscriber::registry().with(chrome_layer).init();
        Some(guard)
    } else {
        None
    };

    println!(
        "avx: {}, neon: {}, simd128: {}, f16c: {}",
        fuel::utils::with_avx(),
        fuel::utils::with_neon(),
        fuel::utils::with_simd128(),
        fuel::utils::with_f16c()
    );
    println!(
        "temp: {:.2} repeat-penalty: {:.2} repeat-last-n: {}",
        args.temperature, args.repeat_penalty, args.repeat_last_n
    );

    // The lazy port is f32 throughout; honor --dtype only to keep CLI
    // parity with the eager binary.
    let _ = match args.dtype.as_str() {
        "bf16" => DType::BF16,
        "f16" => DType::F16,
        _ => anyhow::bail!("Not supported dtype!"),
    };

    let model_path = args.model()?;
    let start = std::time::Instant::now();
    let _device = fuel_examples::device(args.cpu)?;

    let mmaped = fuel::quantized::gguf_mmap::MmapedContent::from_path(&model_path)
        .map_err(|e| E::msg(format!("mmap {}: {e}", model_path.display())))?;
    let header_done = start.elapsed();
    let mut total_size_in_bytes = 0;
    for (_, tensor) in mmaped.content().tensor_infos.iter() {
        let elem_count = tensor.shape.elem_count();
        total_size_in_bytes +=
            elem_count * tensor.ggml_dtype.type_size() / tensor.ggml_dtype.block_size();
    }
    println!(
        "mmapped {:?} tensors ({}); header in {:.2}s",
        mmaped.content().tensor_infos.len(),
        &format_size(total_size_in_bytes),
        header_done.as_secs_f32(),
    );

    let cfg = qwen3_moe_config_from_gguf(&mmaped)?;
    drop(mmaped); // released; from_gguf will re-mmap the file
    let model = QuantizedQwen3MoeModel::from_gguf(&model_path, &cfg)
        .map_err(|e| E::msg(format!("from_gguf: {e}")))?;
    println!("model built in {:.2}s total", start.elapsed().as_secs_f32());

    let tokenizer = args.tokenizer()?;
    let mut tos = TokenOutputStream::new(tokenizer);
    let prompt_str = args
        .prompt
        .clone()
        .unwrap_or_else(|| DEFAULT_PROMPT.to_string());

    let prompt_str = format!("<|im_start|>user\n{prompt_str}<|im_end|>\n<|im_start|>assistant\n");
    print!("formatted prompt: {}", &prompt_str);

    let tokens = tos
        .tokenizer()
        .encode(prompt_str, true)
        .map_err(anyhow::Error::msg)?;

    let tokens = tokens.get_ids().to_vec();

    let to_sample = args.sample_len.saturating_sub(1);

    let mut all_tokens = vec![];

    let mut logits_processor = {
        let temperature = args.temperature;
        let sampling = if temperature <= 0. {
            Sampling::ArgMax
        } else {
            match (args.top_k, args.top_p) {
                (None, None) => Sampling::All { temperature },
                (Some(k), None) => Sampling::TopK { k, temperature },
                (None, Some(p)) => Sampling::TopP { p, temperature },
                (Some(k), Some(p)) => Sampling::TopKThenTopP { k, p, temperature },
            }
        };
        LogitsProcessor::from_sampling(args.seed, sampling)
    };

    // Pick the last position's logits from a (1, seq, vocab) flat realize.
    let last_logits_tensor = |flat: &[f32], seq: usize, vocab: usize| -> Result<Tensor> {
        let off = (seq - 1) * vocab;
        let v: Vec<f32> = flat[off..off + vocab].to_vec();
        Tensor::new(v, &fuel::Device::cpu()).map_err(|e| E::msg(format!("logits tensor: {e}")))
    };

    let start_prompt_processing = std::time::Instant::now();

    let mut next_token = if !args.split_prompt {
        let logits_lazy = model
            .forward(&tokens, 0)
            .map_err(|e| E::msg(format!("forward: {e}")))?;
        let flat = logits_lazy.realize_f32();
        let logits = last_logits_tensor(&flat, tokens.len(), cfg.vocab_size)?;
        logits_processor.sample(&logits)?
    } else {
        let mut next_token = 0;
        for (pos, token) in tokens.iter().enumerate() {
            let logits_lazy = model
                .forward(&[*token], pos)
                .map_err(|e| E::msg(format!("forward: {e}")))?;
            let flat = logits_lazy.realize_f32();
            let logits = last_logits_tensor(&flat, 1, cfg.vocab_size)?;
            next_token = logits_processor.sample(&logits)?
        }
        next_token
    };

    let prompt_dt = start_prompt_processing.elapsed();

    all_tokens.push(next_token);

    if let Some(t) = tos.next_token(next_token)? {
        print!("{t}");
        std::io::stdout().flush()?;
    }

    let eos_token = *tos.tokenizer().get_vocab(true).get("<|im_end|>").unwrap();

    let start_post_prompt = std::time::Instant::now();

    let mut sampled = 0;
    for index in 0..to_sample {
        let logits_lazy = model
            .forward(&[next_token], tokens.len() + index)
            .map_err(|e| E::msg(format!("forward: {e}")))?;
        let flat = logits_lazy.realize_f32();
        let logits = last_logits_tensor(&flat, 1, cfg.vocab_size)?;
        let logits = if args.repeat_penalty == 1. {
            logits
        } else {
            let start_at = all_tokens.len().saturating_sub(args.repeat_last_n);
            fuel_transformers::utils::apply_repeat_penalty(
                &logits,
                args.repeat_penalty,
                &all_tokens[start_at..],
            )?
        };
        next_token = logits_processor.sample(&logits)?;
        all_tokens.push(next_token);
        if let Some(t) = tos.next_token(next_token)? {
            print!("{t}");
            std::io::stdout().flush()?;
        }
        sampled += 1;
        if next_token == eos_token {
            break;
        };
    }

    if let Some(rest) = tos.decode_rest().map_err(fuel::Error::msg)? {
        print!("{rest}");
    }

    std::io::stdout().flush()?;
    let dt = start_post_prompt.elapsed();
    println!(
        "\n\n{:4} prompt tokens processed: {:.2} token/s",
        tokens.len(),
        tokens.len() as f64 / prompt_dt.as_secs_f64(),
    );
    println!(
        "{sampled:4} tokens generated: {:.2} token/s",
        sampled as f64 / dt.as_secs_f64(),
    );
    Ok(())
}
