//! Dispatch wrappers + registration for baracuda-kernels-sys-backed
//! kernels. Sibling to `dispatch::register_cuda_kernels` (PTX path) —
//! each kernel here registers as an alternative at the same
//! `(op_kind, dtypes, BackendId::Cuda)` key. Phase 7.6 step 9a's
//! append-on-register semantics keep them composable; step 9b's
//! route picker ranks by `PrecisionGuarantee` + telemetry.
//!
//! The boilerplate-explosion in this file (50+ unary kinds × 4
//! dtypes, plus binary / ternary / etc.) is generated by per-family
//! macros — adding a new (op, dtype) entry is one manifest line
//! here + one matching line in `fuel-cuda-backend::baracuda`.

#![cfg(feature = "cuda")]

use std::sync::{Arc, RwLock};

use fuel_core_types::{Layout, Error, Result, probe::BackendId};
use fuel_core_types::dispatch::OpKind;
use fuel_core_types::DType;

use crate::kernel::{KernelBindingTable, OpParams};
use crate::Storage;

// Re-use the storage-helpers from dispatch.rs so we read/write
// CudaStorageBytes the same way the PTX wrappers do.
use crate::dispatch::{cuda_input, cuda_output, read_storage, write_storage};

/// Generate one CUDA unary dispatch wrapper that adapts a baracuda
/// `fn(&CudaStorageBytes, Option<&Layout>) -> Result<CudaStorageBytes>`
/// kernel into the `KernelRef` signature the binding table expects.
///
/// Arguments:
/// - `$wrapper_name` — the function symbol to emit.
/// - `$baracuda_fn` — fully-qualified path to the baracuda kernel
///   function (e.g. `fuel_cuda_backend::baracuda::elementwise::unary_neg_f32`).
macro_rules! cuda_unary_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            layouts: &[Layout],
            _params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input, got {}"),
                    inputs.len(),
                ))
                .bt());
            }
            if outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 output, got {}"),
                    outputs.len(),
                ))
                .bt());
            }
            let layout = layouts.first();
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, layout)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

/// Generate one CUDA binary dispatch wrapper.
macro_rules! cuda_binary_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            layouts: &[Layout],
            _params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 2 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 2 inputs, got {}"),
                    inputs.len(),
                ))
                .bt());
            }
            if outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 output, got {}"),
                    outputs.len(),
                ))
                .bt());
            }
            let lhs_layout = layouts.first();
            let rhs_layout = layouts.get(1);
            let lhs_guard = read_storage(&inputs[0])?;
            let rhs_guard = read_storage(&inputs[1])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let lhs_cuda = cuda_input(&lhs_guard)?;
            let rhs_cuda = cuda_input(&rhs_guard)?;
            let result = $baracuda_fn(lhs_cuda, rhs_cuda, lhs_layout, rhs_layout)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

/// Generate a CUDA RoPE dispatch wrapper that pulls
/// `(outer_count, seq, head_dim)` from `OpParams::Rope` and
/// forwards to a baracuda RoPE kernel.
macro_rules! cuda_rope_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(
                        stringify!($wrapper_name),
                        ": expected 1 input + 1 output, got {} + {}",
                    ),
                    inputs.len(), outputs.len(),
                ))
                .bt());
            }
            let (outer_count, seq, head_dim) = match params {
                OpParams::Rope { outer_count, seq, head_dim } => {
                    (*outer_count, *seq, *head_dim)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(
                            stringify!($wrapper_name),
                            ": expected OpParams::Rope, got {:?}",
                        ),
                        other,
                    ))
                    .bt());
                }
            };
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, outer_count, seq, head_dim)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

/// Generate a CUDA index_select dispatch wrapper. Two inputs
/// `(src, indices)`; pulls the shape params from
/// `OpParams::IndexSelect`.
macro_rules! cuda_index_select_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 2 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(
                        stringify!($wrapper_name),
                        ": expected 2 inputs + 1 output, got {} + {}",
                    ),
                    inputs.len(), outputs.len(),
                ))
                .bt());
            }
            let (outer_count, source_dim_size, n_indices, inner_count) = match params {
                OpParams::IndexSelect { outer_count, source_dim_size, n_indices, inner_count } => {
                    (*outer_count, *source_dim_size, *n_indices, *inner_count)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(
                            stringify!($wrapper_name),
                            ": expected OpParams::IndexSelect, got {:?}",
                        ),
                        other,
                    ))
                    .bt());
                }
            };
            let src_guard = read_storage(&inputs[0])?;
            let idx_guard = read_storage(&inputs[1])?;
            if idx_guard.dtype != DType::U32 {
                return Err(Error::Msg(format!(
                    concat!(
                        stringify!($wrapper_name),
                        ": indices must be U32, got {:?}",
                    ),
                    idx_guard.dtype,
                ))
                .bt());
            }
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&src_guard)?;
            let idx_cuda = cuda_input(&idx_guard)?;
            let result = $baracuda_fn(
                src_cuda, idx_cuda, outer_count, source_dim_size, n_indices, inner_count,
            )?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

// ===========================================================================
// Indexing — IndexSelect wrappers
// ===========================================================================

macro_rules! cuda_gather_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 2 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 2 inputs + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let (source_shape, output_shape, dim) = match params {
                OpParams::Gather { source_shape, output_shape, dim } => {
                    (source_shape.clone(), output_shape.clone(), *dim)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::Gather, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let src_guard = read_storage(&inputs[0])?;
            let idx_guard = read_storage(&inputs[1])?;
            if idx_guard.dtype != DType::U32 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": indices must be U32, got {:?}"),
                    idx_guard.dtype,
                )).bt());
            }
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&src_guard)?;
            let idx_cuda = cuda_input(&idx_guard)?;
            let result = $baracuda_fn(src_cuda, idx_cuda, &source_shape, &output_shape, dim)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

macro_rules! cuda_scatter_add_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 3 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 3 inputs + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let (base_shape, src_shape, dim) = match params {
                OpParams::ScatterAdd { base_shape, src_shape, dim } => {
                    (base_shape.clone(), src_shape.clone(), *dim)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::ScatterAdd, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let base_guard = read_storage(&inputs[0])?;
            let idx_guard = read_storage(&inputs[1])?;
            if idx_guard.dtype != DType::U32 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": indices must be U32, got {:?}"),
                    idx_guard.dtype,
                )).bt());
            }
            let src_guard = read_storage(&inputs[2])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let base_cuda = cuda_input(&base_guard)?;
            let idx_cuda = cuda_input(&idx_guard)?;
            let src_cuda = cuda_input(&src_guard)?;
            let result = $baracuda_fn(base_cuda, idx_cuda, src_cuda, &base_shape, &src_shape, dim)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

macro_rules! cuda_masked_fill_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 2 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 2 inputs + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let fill_bytes = match params {
                OpParams::MaskedFill { fill_bytes } => fill_bytes.clone(),
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::MaskedFill, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let src_guard = read_storage(&inputs[0])?;
            let mask_guard = read_storage(&inputs[1])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&src_guard)?;
            let mask_cuda = cuda_input(&mask_guard)?;
            let result = $baracuda_fn(src_cuda, mask_cuda, &fill_bytes)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

pub mod indexing {
    use super::*;
    use fuel_cuda_backend::baracuda::indexing as bk;

    cuda_index_select_baracuda_wrapper!(index_select_f32, bk::index_select_f32);
    cuda_index_select_baracuda_wrapper!(index_select_f64, bk::index_select_f64);
    cuda_index_select_baracuda_wrapper!(index_select_i32, bk::index_select_i32);

    cuda_gather_baracuda_wrapper!(gather_f32, bk::gather_f32);
    cuda_gather_baracuda_wrapper!(gather_f64, bk::gather_f64);
    cuda_gather_baracuda_wrapper!(gather_i32, bk::gather_i32);

    cuda_scatter_add_baracuda_wrapper!(scatter_add_f32, bk::scatter_add_f32);
    cuda_scatter_add_baracuda_wrapper!(scatter_add_f64, bk::scatter_add_f64);

    cuda_masked_fill_baracuda_wrapper!(masked_fill_f32, bk::masked_fill_f32);
    cuda_masked_fill_baracuda_wrapper!(masked_fill_f64, bk::masked_fill_f64);
    cuda_masked_fill_baracuda_wrapper!(masked_fill_i32, bk::masked_fill_i32);
}

// ===========================================================================
// Int-GEMM — S8/U8 RRR Identity (W8A8 phase 1)
// ===========================================================================
//
// Baracuda's `gemm_{s8,u8}_rrr_sm80_run` are RRR-layout (row-major ×
// row-major → row-major), Identity-epilogue Int8 tensor-core GEMM.
// Mirror `Op::MatMul`'s shape contract directly — registering at
// `(MatMul, [I8, I8, I8], Cuda)` and `[U8, U8, U8]` keys, so the
// existing `OpParams::Matmul { m, n, k, lhs/rhs_batch_dims }` flows
// through unchanged.
//
// Bias / BiasRelu / BiasGelu / BiasSilu epilogues are not yet wired
// — those need a `FusedLinearInt` op (or extending FusedLinear with
// int dtypes), which is a separate session.

macro_rules! cuda_gemm_int_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path $(,)?) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 2 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(
                        stringify!($wrapper_name),
                        ": expected 2 inputs + 1 output, got {} + {}",
                    ),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let (lhs_batch_dims, rhs_batch_dims, m, n, k) = match params {
                OpParams::Matmul { lhs_batch_dims, rhs_batch_dims, m, n, k } => {
                    (lhs_batch_dims.clone(), rhs_batch_dims.clone(), *m, *n, *k)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::Matmul, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let lhs_guard = read_storage(&inputs[0])?;
            let rhs_guard = read_storage(&inputs[1])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let lhs_cuda = cuda_input(&lhs_guard)?;
            let rhs_cuda = cuda_input(&rhs_guard)?;
            let result = $baracuda_fn(
                lhs_cuda, rhs_cuda, &lhs_batch_dims, &rhs_batch_dims, m, n, k,
            )?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

pub mod gemm_int {
    use super::*;
    use fuel_cuda_backend::baracuda::gemm_int as bk;

    cuda_gemm_int_baracuda_wrapper!(gemm_s8_rrr, bk::gemm_s8_rrr);
    cuda_gemm_int_baracuda_wrapper!(gemm_u8_rrr, bk::gemm_u8_rrr);
}

// ===========================================================================
// ArgMaxDim / ArgMinDim — U32-output variants (alpha.28)
// ===========================================================================
//
// Pulls `dim` from `OpParams::Reduce { dims, keepdim: _ }` with the
// single-dim constraint Fuel's PTX argmax/argmin paths enforce.
// Output is U32 indices in the squeezed (rank N-1) shape.

macro_rules! cuda_arg_reduce_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path $(,)?) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let dim = match params {
                OpParams::Reduce { dims, keepdim: _ } => {
                    if dims.len() != 1 {
                        return Err(Error::Msg(format!(
                            concat!(stringify!($wrapper_name), ": expected a single reduce dim, got {:?}"),
                            dims,
                        )).bt());
                    }
                    dims[0]
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::Reduce, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let layout = layouts.first().ok_or_else(|| {
                Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": layouts empty"),
                )).bt()
            })?;
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, layout, dim)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

pub mod arg_reduce {
    use super::*;
    use fuel_cuda_backend::baracuda::arg_reduce as bk;

    cuda_arg_reduce_baracuda_wrapper!(argmax_dim_u32_f32, bk::argmax_dim_u32_f32);
    cuda_arg_reduce_baracuda_wrapper!(argmin_dim_u32_f32, bk::argmin_dim_u32_f32);
    cuda_arg_reduce_baracuda_wrapper!(argmax_dim_u32_f64, bk::argmax_dim_u32_f64);
    cuda_arg_reduce_baracuda_wrapper!(argmin_dim_u32_f64, bk::argmin_dim_u32_f64);
    cuda_arg_reduce_baracuda_wrapper!(argmax_dim_u32_f16, bk::argmax_dim_u32_f16);
    cuda_arg_reduce_baracuda_wrapper!(argmin_dim_u32_f16, bk::argmin_dim_u32_f16);
    cuda_arg_reduce_baracuda_wrapper!(argmax_dim_u32_bf16, bk::argmax_dim_u32_bf16);
    cuda_arg_reduce_baracuda_wrapper!(argmin_dim_u32_bf16, bk::argmin_dim_u32_bf16);
}

// ===========================================================================
// PowI — `y = x^n` with integer exponent (OpParams::PowI { exp })
// ===========================================================================
//
// Alpha.28 added `unary_powi_<dtype>_run` over f32/f64/f16/bf16 plus
// matching backward kernels. Power-by-squaring on device — correct on
// negative bases, no `pow(x, n as f32)` shim needed. Exponent ships
// via `p0: f32` (round-trips exactly for |n| ≤ 2^24).

macro_rules! cuda_powi_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path $(,)?) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let exp = match params {
                OpParams::PowI { exp } => *exp,
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::PowI, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, exp)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

pub mod powi {
    use super::*;
    use fuel_cuda_backend::baracuda::powi as bk;

    cuda_powi_baracuda_wrapper!(powi_f32, bk::powi_f32);
    cuda_powi_baracuda_wrapper!(powi_f64, bk::powi_f64);
    cuda_powi_baracuda_wrapper!(powi_f16, bk::powi_f16);
    cuda_powi_baracuda_wrapper!(powi_bf16, bk::powi_bf16);
}

// ===========================================================================
// Clamp — scalar (min, max) → broadcast-tensor ternary clamp
// ===========================================================================
//
// Fuel's `OpKind::ClampElementwise` carries `(min, max)` in
// `OpParams::Clamp`; baracuda's `ternary_clamp` accepts two bound
// tensors. The per-dtype wrapper allocates two 1-element device
// buffers (one per bound) inside the kernel module and invokes the
// strided variant with stride 0 on the bound axis.

macro_rules! cuda_clamp_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path, $scalar_ty:ty $(,)?) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let (min_f64, max_f64) = match params {
                OpParams::Clamp { min, max } => (*min, *max),
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::Clamp, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, min_f64 as $scalar_ty, max_f64 as $scalar_ty)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

pub mod clamp {
    use super::*;
    use fuel_cuda_backend::baracuda::clamp as bk;

    cuda_clamp_baracuda_wrapper!(clamp_f32, bk::clamp_f32, f32);
    cuda_clamp_baracuda_wrapper!(clamp_f64, bk::clamp_f64, f64);
    cuda_clamp_baracuda_wrapper!(clamp_f16, bk::clamp_f16, f32);
    cuda_clamp_baracuda_wrapper!(clamp_bf16, bk::clamp_bf16, f32);
}

// ===========================================================================
// Concat — N-ary via N-1 chained baracuda concat2 calls
// ===========================================================================
//
// Baracuda only ships binary `concat2`. The wrapper chains N-1 calls
// to cover Fuel's `OpKind::Concat` N-input semantics. The route
// picker / Judge will tend to prefer the PTX 1-launch path for N > 2
// in practice; baracuda still wins on N == 2 where there's no
// launch-count tax.

macro_rules! cuda_concat_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path $(,)?) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.is_empty() {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": at least 1 input required"),
                )).bt());
            }
            if outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 output, got {}"),
                    outputs.len(),
                )).bt());
            }
            let (outer_count, input_dim_sizes, inner_count) = match params {
                OpParams::Concat { outer_count, input_dim_sizes, inner_count } => {
                    (*outer_count, input_dim_sizes.clone(), *inner_count)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::Concat, got {:?}"),
                        other,
                    )).bt());
                }
            };
            if input_dim_sizes.len() != inputs.len() {
                return Err(Error::Msg(format!(
                    concat!(
                        stringify!($wrapper_name),
                        ": OpParams declares {} inputs but the work item carries {}",
                    ),
                    input_dim_sizes.len(),
                    inputs.len(),
                )).bt());
            }
            let in_guards: Vec<_> = inputs
                .iter()
                .map(read_storage)
                .collect::<Result<Vec<_>>>()?;
            let mut in_cudas: Vec<&fuel_cuda_backend::CudaStorageBytes> =
                Vec::with_capacity(in_guards.len());
            for g in &in_guards {
                in_cudas.push(cuda_input(g)?);
            }
            let mut out_guard = write_storage(&outputs[0])?;
            let result = $baracuda_fn(&in_cudas, outer_count, &input_dim_sizes, inner_count)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

pub mod concat {
    use super::*;
    use fuel_cuda_backend::baracuda::concat as bk;

    cuda_concat_baracuda_wrapper!(concat_f32, bk::concat_f32);
    cuda_concat_baracuda_wrapper!(concat_f64, bk::concat_f64);
    cuda_concat_baracuda_wrapper!(concat_f16, bk::concat_f16);
    cuda_concat_baracuda_wrapper!(concat_bf16, bk::concat_bf16);
}

// ===========================================================================
// Affine — `y = mul * x + add` with scalar (mul, add) per OpParams::Affine
// ===========================================================================
//
// Per-dtype wrappers; baracuda's FFI carries (a, b) in the natural
// per-dtype arithmetic type (f32 for f16/bf16 storage; f64 for f64
// storage; per-element int type for i32/i64/u8). The wrappers cast
// Fuel's `(f64, f64)` OpParams down to the right type at the FFI
// boundary.

macro_rules! cuda_affine_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path, $scalar_cast:expr $(,)?) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let (mul_f64, add_f64) = match params {
                OpParams::Affine { mul, add } => (*mul, *add),
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::Affine, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let cast = $scalar_cast;
            let mul = cast(mul_f64);
            let add = cast(add_f64);
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, mul, add)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

pub mod affine {
    use super::*;
    use fuel_cuda_backend::baracuda::affine as bk;

    cuda_affine_baracuda_wrapper!(affine_f32, bk::affine_f32, |v: f64| v as f32);
    cuda_affine_baracuda_wrapper!(affine_f64, bk::affine_f64, |v: f64| v);
    cuda_affine_baracuda_wrapper!(affine_f16, bk::affine_f16, |v: f64| v as f32);
    cuda_affine_baracuda_wrapper!(affine_bf16, bk::affine_bf16, |v: f64| v as f32);
    cuda_affine_baracuda_wrapper!(affine_i32, bk::affine_i32, |v: f64| v as i32);
    cuda_affine_baracuda_wrapper!(affine_i64, bk::affine_i64, |v: f64| v as i64);
    cuda_affine_baracuda_wrapper!(affine_u8, bk::affine_u8, |v: f64| v as u8);
}

// ===========================================================================
// Cast — single wrapper across every (src_dt, dst_dt) pair baracuda exposes
// ===========================================================================
//
// Cast's binding-table key is `[src_dt, dst_dt]` (two dtypes, not the
// usual unary `[dt, dt]`). The wrapper reads both dtypes from the
// input/output Storage and dispatches into
// `fuel_cuda_backend::baracuda::cast::dispatch`, which picks the right
// FFI symbol from the 8×8 baracuda surface. One wrapper, many
// (per-pair) binding-table entries — same pattern as the PTX-backed
// `cast_cuda_wrapper` in [`crate::dispatch`].

pub mod cast {
    use super::*;
    use fuel_cuda_backend::baracuda::cast as bk;

    pub fn cast_baracuda_wrapper(
        inputs: &[Arc<RwLock<Storage>>],
        outputs: &mut [Arc<RwLock<Storage>>],
        _layouts: &[Layout],
        _params: &OpParams,
    ) -> Result<()> {
        if inputs.len() != 1 || outputs.len() != 1 {
            return Err(Error::Msg(format!(
                "cast_baracuda_wrapper: expected 1 input + 1 output, got {} + {}",
                inputs.len(),
                outputs.len(),
            ))
            .bt());
        }
        let in_guard = read_storage(&inputs[0])?;
        let mut out_guard = write_storage(&outputs[0])?;
        let src_dtype = in_guard.dtype;
        let dst_dtype = out_guard.dtype;
        let src_cuda = cuda_input(&in_guard)?;
        let result = bk::dispatch(src_cuda, src_dtype, dst_dtype)?;
        let out_cuda = cuda_output(&mut out_guard)?;
        *out_cuda = result;
        Ok(())
    }
}

/// Generate a CUDA softmax-last-dim dispatch wrapper that pulls
/// `(outer_count, last_dim)` from `OpParams::SoftmaxLastDim`
/// (or `LogSoftmaxLastDim`) and forwards to a baracuda softmax
/// kernel.
macro_rules! cuda_softmax_last_dim_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(
                        stringify!($wrapper_name),
                        ": expected 1 input + 1 output, got {} + {}",
                    ),
                    inputs.len(), outputs.len(),
                ))
                .bt());
            }
            let (outer_count, last_dim) = match params {
                OpParams::SoftmaxLastDim { outer_count, last_dim } => {
                    (*outer_count, *last_dim)
                }
                OpParams::LogSoftmaxLastDim { outer_count, last_dim } => {
                    (*outer_count, *last_dim)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(
                            stringify!($wrapper_name),
                            ": expected OpParams::SoftmaxLastDim/LogSoftmaxLastDim, got {:?}",
                        ),
                        other,
                    ))
                    .bt());
                }
            };
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, outer_count, last_dim)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

// ===========================================================================
// Softmax wrappers (Softmax + LogSoftmax LastDim)
// ===========================================================================

pub mod softmax {
    use super::*;
    use fuel_cuda_backend::baracuda::softmax as bk;

    cuda_softmax_last_dim_baracuda_wrapper!(softmax_f32, bk::softmax_last_dim_f32);
    cuda_softmax_last_dim_baracuda_wrapper!(softmax_f16, bk::softmax_last_dim_f16);
    cuda_softmax_last_dim_baracuda_wrapper!(softmax_bf16, bk::softmax_last_dim_bf16);
    cuda_softmax_last_dim_baracuda_wrapper!(softmax_f64, bk::softmax_last_dim_f64);

    cuda_softmax_last_dim_baracuda_wrapper!(log_softmax_f32, bk::log_softmax_last_dim_f32);
    cuda_softmax_last_dim_baracuda_wrapper!(log_softmax_f16, bk::log_softmax_last_dim_f16);
    cuda_softmax_last_dim_baracuda_wrapper!(log_softmax_bf16, bk::log_softmax_last_dim_bf16);
    cuda_softmax_last_dim_baracuda_wrapper!(log_softmax_f64, bk::log_softmax_last_dim_f64);
}

// ===========================================================================
// Attention — RoPE wrappers
// ===========================================================================

pub mod attention {
    use super::*;
    use fuel_cuda_backend::baracuda::attention as bk;

    cuda_rope_baracuda_wrapper!(rope_f32, bk::rope_f32);
    cuda_rope_baracuda_wrapper!(rope_f16, bk::rope_f16);
    cuda_rope_baracuda_wrapper!(rope_bf16, bk::rope_bf16);
    cuda_rope_baracuda_wrapper!(rope_f64, bk::rope_f64);
}

/// Generate a CUDA norm-last-dim dispatch wrapper that pulls
/// `(outer_count, last_dim, eps)` from `OpParams::NormLastDim`
/// and forwards to a baracuda last-dim norm kernel.
macro_rules! cuda_norm_last_dim_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(
                        stringify!($wrapper_name),
                        ": expected 1 input + 1 output, got {} + {}",
                    ),
                    inputs.len(), outputs.len(),
                ))
                .bt());
            }
            let (outer_count, last_dim, eps) = match params {
                OpParams::NormLastDim { outer_count, last_dim, eps } => {
                    (*outer_count, *last_dim, *eps)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(
                            stringify!($wrapper_name),
                            ": expected OpParams::NormLastDim, got {:?}",
                        ),
                        other,
                    ))
                    .bt());
                }
            };
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, outer_count, last_dim, eps)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

// ===========================================================================
// Norm-last-dim wrappers (RmsNorm + LayerNorm)
// ===========================================================================

pub mod norm {
    use super::*;
    use fuel_cuda_backend::baracuda::norm as bk;

    cuda_norm_last_dim_baracuda_wrapper!(rms_f32, bk::rms_norm_last_dim_f32);
    cuda_norm_last_dim_baracuda_wrapper!(rms_f16, bk::rms_norm_last_dim_f16);
    cuda_norm_last_dim_baracuda_wrapper!(rms_bf16, bk::rms_norm_last_dim_bf16);
    cuda_norm_last_dim_baracuda_wrapper!(rms_f64, bk::rms_norm_last_dim_f64);

    cuda_norm_last_dim_baracuda_wrapper!(layer_f32, bk::layer_norm_last_dim_f32);
    cuda_norm_last_dim_baracuda_wrapper!(layer_f16, bk::layer_norm_last_dim_f16);
    cuda_norm_last_dim_baracuda_wrapper!(layer_bf16, bk::layer_norm_last_dim_bf16);
    cuda_norm_last_dim_baracuda_wrapper!(layer_f64, bk::layer_norm_last_dim_f64);
}

/// Generate one CUDA reduce dispatch wrapper. Reduce wrappers
/// destructure `OpParams::Reduce { dims, keepdim }` and forward
/// to the baracuda multi-axis driver.
macro_rules! cuda_reduce_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input, got {}"),
                    inputs.len(),
                ))
                .bt());
            }
            if outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 output, got {}"),
                    outputs.len(),
                ))
                .bt());
            }
            let (dims, keepdim) = match params {
                OpParams::Reduce { dims, keepdim } => (dims.clone(), *keepdim),
                other => {
                    return Err(Error::Msg(format!(
                        concat!(
                            stringify!($wrapper_name),
                            ": expected OpParams::Reduce, got {:?}",
                        ),
                        other,
                    ))
                    .bt());
                }
            };
            let layout = layouts.first().ok_or_else(|| {
                Error::Msg(format!(
                    concat!(
                        stringify!($wrapper_name),
                        ": reduce requires an input layout (call with layouts[0])",
                    ),
                ))
                .bt()
            })?;
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, layout, &dims, keepdim)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

// ===========================================================================
// Reduce wrappers
// ===========================================================================

pub mod reduce {
    use super::*;
    use fuel_cuda_backend::baracuda::reduce as bk;

    cuda_reduce_baracuda_wrapper!(sum_f32, bk::reduce_sum_f32);
    cuda_reduce_baracuda_wrapper!(max_f32, bk::reduce_max_f32);
    cuda_reduce_baracuda_wrapper!(min_f32, bk::reduce_min_f32);
    cuda_reduce_baracuda_wrapper!(mean_f32, bk::reduce_mean_f32);

    cuda_reduce_baracuda_wrapper!(sum_f16, bk::reduce_sum_f16);
    cuda_reduce_baracuda_wrapper!(max_f16, bk::reduce_max_f16);
    cuda_reduce_baracuda_wrapper!(min_f16, bk::reduce_min_f16);
    cuda_reduce_baracuda_wrapper!(mean_f16, bk::reduce_mean_f16);

    cuda_reduce_baracuda_wrapper!(sum_bf16, bk::reduce_sum_bf16);
    cuda_reduce_baracuda_wrapper!(max_bf16, bk::reduce_max_bf16);
    cuda_reduce_baracuda_wrapper!(min_bf16, bk::reduce_min_bf16);
    cuda_reduce_baracuda_wrapper!(mean_bf16, bk::reduce_mean_bf16);

    cuda_reduce_baracuda_wrapper!(sum_f64, bk::reduce_sum_f64);
    cuda_reduce_baracuda_wrapper!(max_f64, bk::reduce_max_f64);
    cuda_reduce_baracuda_wrapper!(min_f64, bk::reduce_min_f64);
    cuda_reduce_baracuda_wrapper!(mean_f64, bk::reduce_mean_f64);
}

// ===========================================================================
// Elementwise binary wrappers
// ===========================================================================

pub mod binary {
    use super::*;
    use fuel_cuda_backend::baracuda::binary as bk;

    cuda_binary_baracuda_wrapper!(add_f32, bk::binary_add_f32);
    cuda_binary_baracuda_wrapper!(sub_f32, bk::binary_sub_f32);
    cuda_binary_baracuda_wrapper!(mul_f32, bk::binary_mul_f32);
    cuda_binary_baracuda_wrapper!(div_f32, bk::binary_div_f32);
    cuda_binary_baracuda_wrapper!(maximum_f32, bk::binary_maximum_f32);
    cuda_binary_baracuda_wrapper!(minimum_f32, bk::binary_minimum_f32);

    cuda_binary_baracuda_wrapper!(add_f16, bk::binary_add_f16);
    cuda_binary_baracuda_wrapper!(sub_f16, bk::binary_sub_f16);
    cuda_binary_baracuda_wrapper!(mul_f16, bk::binary_mul_f16);
    cuda_binary_baracuda_wrapper!(div_f16, bk::binary_div_f16);
    cuda_binary_baracuda_wrapper!(maximum_f16, bk::binary_maximum_f16);
    cuda_binary_baracuda_wrapper!(minimum_f16, bk::binary_minimum_f16);

    cuda_binary_baracuda_wrapper!(add_bf16, bk::binary_add_bf16);
    cuda_binary_baracuda_wrapper!(sub_bf16, bk::binary_sub_bf16);
    cuda_binary_baracuda_wrapper!(mul_bf16, bk::binary_mul_bf16);
    cuda_binary_baracuda_wrapper!(div_bf16, bk::binary_div_bf16);
    cuda_binary_baracuda_wrapper!(maximum_bf16, bk::binary_maximum_bf16);
    cuda_binary_baracuda_wrapper!(minimum_bf16, bk::binary_minimum_bf16);

    cuda_binary_baracuda_wrapper!(add_f64, bk::binary_add_f64);
    cuda_binary_baracuda_wrapper!(sub_f64, bk::binary_sub_f64);
    cuda_binary_baracuda_wrapper!(mul_f64, bk::binary_mul_f64);
    cuda_binary_baracuda_wrapper!(div_f64, bk::binary_div_f64);
    cuda_binary_baracuda_wrapper!(maximum_f64, bk::binary_maximum_f64);
    cuda_binary_baracuda_wrapper!(minimum_f64, bk::binary_minimum_f64);
}

// ===========================================================================
// Elementwise unary wrappers
// ===========================================================================
//
// Manifest: one line per (op, dtype) pair. Both halves of the
// `(*_wrapper, *_kernel)` mapping live here so the file is the single
// source of truth for "baracuda's coverage of Fuel's binding table."

pub mod unary {
    use super::*;
    use fuel_cuda_backend::baracuda::elementwise as bk;

    // f32 surface
    cuda_unary_baracuda_wrapper!(neg_f32, bk::unary_neg_f32);
    cuda_unary_baracuda_wrapper!(abs_f32, bk::unary_abs_f32);
    cuda_unary_baracuda_wrapper!(sign_f32, bk::unary_sign_f32);
    cuda_unary_baracuda_wrapper!(sqr_f32, bk::unary_sqr_f32);
    cuda_unary_baracuda_wrapper!(sqrt_f32, bk::unary_sqrt_f32);
    cuda_unary_baracuda_wrapper!(rsqrt_f32, bk::unary_rsqrt_f32);
    cuda_unary_baracuda_wrapper!(recip_f32, bk::unary_recip_f32);
    cuda_unary_baracuda_wrapper!(exp_f32, bk::unary_exp_f32);
    cuda_unary_baracuda_wrapper!(log_f32, bk::unary_log_f32);
    cuda_unary_baracuda_wrapper!(sin_f32, bk::unary_sin_f32);
    cuda_unary_baracuda_wrapper!(cos_f32, bk::unary_cos_f32);
    cuda_unary_baracuda_wrapper!(tanh_f32, bk::unary_tanh_f32);
    cuda_unary_baracuda_wrapper!(relu_f32, bk::unary_relu_f32);
    cuda_unary_baracuda_wrapper!(gelu_f32, bk::unary_gelu_f32);
    cuda_unary_baracuda_wrapper!(silu_f32, bk::unary_silu_f32);
    cuda_unary_baracuda_wrapper!(sigmoid_f32, bk::unary_sigmoid_f32);

    // f16
    cuda_unary_baracuda_wrapper!(neg_f16, bk::unary_neg_f16);
    cuda_unary_baracuda_wrapper!(abs_f16, bk::unary_abs_f16);
    cuda_unary_baracuda_wrapper!(sqr_f16, bk::unary_sqr_f16);
    cuda_unary_baracuda_wrapper!(sqrt_f16, bk::unary_sqrt_f16);
    cuda_unary_baracuda_wrapper!(recip_f16, bk::unary_recip_f16);
    cuda_unary_baracuda_wrapper!(exp_f16, bk::unary_exp_f16);
    cuda_unary_baracuda_wrapper!(log_f16, bk::unary_log_f16);
    cuda_unary_baracuda_wrapper!(sin_f16, bk::unary_sin_f16);
    cuda_unary_baracuda_wrapper!(cos_f16, bk::unary_cos_f16);
    cuda_unary_baracuda_wrapper!(tanh_f16, bk::unary_tanh_f16);
    cuda_unary_baracuda_wrapper!(relu_f16, bk::unary_relu_f16);
    cuda_unary_baracuda_wrapper!(gelu_f16, bk::unary_gelu_f16);
    cuda_unary_baracuda_wrapper!(silu_f16, bk::unary_silu_f16);
    cuda_unary_baracuda_wrapper!(sigmoid_f16, bk::unary_sigmoid_f16);

    // bf16
    cuda_unary_baracuda_wrapper!(neg_bf16, bk::unary_neg_bf16);
    cuda_unary_baracuda_wrapper!(abs_bf16, bk::unary_abs_bf16);
    cuda_unary_baracuda_wrapper!(sqr_bf16, bk::unary_sqr_bf16);
    cuda_unary_baracuda_wrapper!(sqrt_bf16, bk::unary_sqrt_bf16);
    cuda_unary_baracuda_wrapper!(recip_bf16, bk::unary_recip_bf16);
    cuda_unary_baracuda_wrapper!(exp_bf16, bk::unary_exp_bf16);
    cuda_unary_baracuda_wrapper!(log_bf16, bk::unary_log_bf16);
    cuda_unary_baracuda_wrapper!(sin_bf16, bk::unary_sin_bf16);
    cuda_unary_baracuda_wrapper!(cos_bf16, bk::unary_cos_bf16);
    cuda_unary_baracuda_wrapper!(tanh_bf16, bk::unary_tanh_bf16);
    cuda_unary_baracuda_wrapper!(relu_bf16, bk::unary_relu_bf16);
    cuda_unary_baracuda_wrapper!(gelu_bf16, bk::unary_gelu_bf16);
    cuda_unary_baracuda_wrapper!(silu_bf16, bk::unary_silu_bf16);
    cuda_unary_baracuda_wrapper!(sigmoid_bf16, bk::unary_sigmoid_bf16);

    // f64
    cuda_unary_baracuda_wrapper!(neg_f64, bk::unary_neg_f64);
    cuda_unary_baracuda_wrapper!(abs_f64, bk::unary_abs_f64);
    cuda_unary_baracuda_wrapper!(sqr_f64, bk::unary_sqr_f64);
    cuda_unary_baracuda_wrapper!(sqrt_f64, bk::unary_sqrt_f64);
    cuda_unary_baracuda_wrapper!(recip_f64, bk::unary_recip_f64);
    cuda_unary_baracuda_wrapper!(exp_f64, bk::unary_exp_f64);
    cuda_unary_baracuda_wrapper!(log_f64, bk::unary_log_f64);
    cuda_unary_baracuda_wrapper!(sin_f64, bk::unary_sin_f64);
    cuda_unary_baracuda_wrapper!(cos_f64, bk::unary_cos_f64);
    cuda_unary_baracuda_wrapper!(tanh_f64, bk::unary_tanh_f64);
    cuda_unary_baracuda_wrapper!(relu_f64, bk::unary_relu_f64);
    cuda_unary_baracuda_wrapper!(gelu_f64, bk::unary_gelu_f64);
    cuda_unary_baracuda_wrapper!(silu_f64, bk::unary_silu_f64);
    cuda_unary_baracuda_wrapper!(sigmoid_f64, bk::unary_sigmoid_f64);

    // Wrappers are `pub fn` (per the macro); accessible as
    // `unary::<name>` from `register_baracuda_cuda_kernels` below.
}

/// Register every baracuda-backed CUDA kernel into the binding table
/// as an alternative at its `(OpKind, dtypes, Cuda)` decision point.
/// Sits alongside the PTX-backed `register_cuda_kernels` — both can
/// be called on the same table; step 9a's append-on-register makes
/// them coexist.
///
/// Coverage today: 53 unary entries across F32/F16/BF16/F64.
/// Subsequent commits fan out to binary / ternary / norm / softmax /
/// attention / GGUF / MoE / int-GEMM / etc.
pub fn register_baracuda_cuda_kernels(table: &mut KernelBindingTable) {
    use OpKind::*;
    let cuda = BackendId::Cuda;
    let u = |t: DType| [t, t];
    let b = |t: DType| [t, t, t];

    let f32 = DType::F32;
    let f16 = DType::F16;
    let bf16 = DType::BF16;
    let f64 = DType::F64;

    // ----- F32 binary -----
    table.register(AddElementwise,     &b(f32), cuda, binary::add_f32);
    table.register(SubElementwise,     &b(f32), cuda, binary::sub_f32);
    table.register(MulElementwise,     &b(f32), cuda, binary::mul_f32);
    table.register(DivElementwise,     &b(f32), cuda, binary::div_f32);
    table.register(MaximumElementwise, &b(f32), cuda, binary::maximum_f32);
    table.register(MinimumElementwise, &b(f32), cuda, binary::minimum_f32);

    // ----- F16 / BF16 / F64 binary (net-new dtype coverage on CUDA) -----
    table.register(AddElementwise,     &b(f16), cuda, binary::add_f16);
    table.register(SubElementwise,     &b(f16), cuda, binary::sub_f16);
    table.register(MulElementwise,     &b(f16), cuda, binary::mul_f16);
    table.register(DivElementwise,     &b(f16), cuda, binary::div_f16);
    table.register(MaximumElementwise, &b(f16), cuda, binary::maximum_f16);
    table.register(MinimumElementwise, &b(f16), cuda, binary::minimum_f16);

    table.register(AddElementwise,     &b(bf16), cuda, binary::add_bf16);
    table.register(SubElementwise,     &b(bf16), cuda, binary::sub_bf16);
    table.register(MulElementwise,     &b(bf16), cuda, binary::mul_bf16);
    table.register(DivElementwise,     &b(bf16), cuda, binary::div_bf16);
    table.register(MaximumElementwise, &b(bf16), cuda, binary::maximum_bf16);
    table.register(MinimumElementwise, &b(bf16), cuda, binary::minimum_bf16);

    table.register(AddElementwise,     &b(f64), cuda, binary::add_f64);
    table.register(SubElementwise,     &b(f64), cuda, binary::sub_f64);
    table.register(MulElementwise,     &b(f64), cuda, binary::mul_f64);
    table.register(DivElementwise,     &b(f64), cuda, binary::div_f64);
    table.register(MaximumElementwise, &b(f64), cuda, binary::maximum_f64);
    table.register(MinimumElementwise, &b(f64), cuda, binary::minimum_f64);

    // ----- Reduce (single dispatch covers all axis configurations;
    //       the wrapper destructures OpParams::Reduce { dims, keepdim }) -----
    table.register(SumReduce,  &u(f32),  cuda, reduce::sum_f32);
    table.register(MaxReduce,  &u(f32),  cuda, reduce::max_f32);
    table.register(MinReduce,  &u(f32),  cuda, reduce::min_f32);
    table.register(MeanReduce, &u(f32),  cuda, reduce::mean_f32);

    table.register(SumReduce,  &u(f16),  cuda, reduce::sum_f16);
    table.register(MaxReduce,  &u(f16),  cuda, reduce::max_f16);
    table.register(MinReduce,  &u(f16),  cuda, reduce::min_f16);
    table.register(MeanReduce, &u(f16),  cuda, reduce::mean_f16);

    table.register(SumReduce,  &u(bf16), cuda, reduce::sum_bf16);
    table.register(MaxReduce,  &u(bf16), cuda, reduce::max_bf16);
    table.register(MinReduce,  &u(bf16), cuda, reduce::min_bf16);
    table.register(MeanReduce, &u(bf16), cuda, reduce::mean_bf16);

    table.register(SumReduce,  &u(f64),  cuda, reduce::sum_f64);
    table.register(MaxReduce,  &u(f64),  cuda, reduce::max_f64);
    table.register(MinReduce,  &u(f64),  cuda, reduce::min_f64);
    table.register(MeanReduce, &u(f64),  cuda, reduce::mean_f64);

    // ----- Norm LastDim (RmsNorm + LayerNorm) -----
    table.register(RmsNormLastDim,   &u(f32),  cuda, norm::rms_f32);
    table.register(RmsNormLastDim,   &u(f16),  cuda, norm::rms_f16);
    table.register(RmsNormLastDim,   &u(bf16), cuda, norm::rms_bf16);
    table.register(RmsNormLastDim,   &u(f64),  cuda, norm::rms_f64);

    table.register(LayerNormLastDim, &u(f32),  cuda, norm::layer_f32);
    table.register(LayerNormLastDim, &u(f16),  cuda, norm::layer_f16);
    table.register(LayerNormLastDim, &u(bf16), cuda, norm::layer_bf16);
    table.register(LayerNormLastDim, &u(f64),  cuda, norm::layer_f64);

    // ----- Attention — RoPE -----
    table.register(Rope, &u(f32),  cuda, attention::rope_f32);
    table.register(Rope, &u(f16),  cuda, attention::rope_f16);
    table.register(Rope, &u(bf16), cuda, attention::rope_bf16);
    table.register(Rope, &u(f64),  cuda, attention::rope_f64);

    // ----- Softmax + LogSoftmax LastDim -----
    table.register(SoftmaxLastDim,    &u(f32),  cuda, softmax::softmax_f32);
    table.register(SoftmaxLastDim,    &u(f16),  cuda, softmax::softmax_f16);
    table.register(SoftmaxLastDim,    &u(bf16), cuda, softmax::softmax_bf16);
    table.register(SoftmaxLastDim,    &u(f64),  cuda, softmax::softmax_f64);

    table.register(LogSoftmaxLastDim, &u(f32),  cuda, softmax::log_softmax_f32);
    table.register(LogSoftmaxLastDim, &u(f16),  cuda, softmax::log_softmax_f16);
    table.register(LogSoftmaxLastDim, &u(bf16), cuda, softmax::log_softmax_bf16);
    table.register(LogSoftmaxLastDim, &u(f64),  cuda, softmax::log_softmax_f64);

    // ----- IndexSelect / Gather / MaskedFill / ScatterAdd
    // Dtype keys mirror the existing CPU registrations:
    //   IndexSelect: [data, U32, data]
    //   Gather:      [data, U32, data]
    //   MaskedFill:  [data, U8,  data]
    //   ScatterAdd:  [data, U32, data, data] (base, idx, src, out — Fuel folds out into the table's per-key shape)
    let u32_dt = DType::U32;
    let u8_dt = DType::U8;
    let i32_dt = DType::I32;
    let index_select_dts = |dt: DType| [dt, u32_dt, dt];
    let gather_dts = |dt: DType| [dt, u32_dt, dt];
    let masked_dts = |dt: DType| [dt, u8_dt, dt];
    let scatter_dts = |dt: DType| [dt, u32_dt, dt, dt];

    table.register(IndexSelect, &index_select_dts(f32), cuda, indexing::index_select_f32);
    table.register(IndexSelect, &index_select_dts(f64), cuda, indexing::index_select_f64);
    table.register(IndexSelect, &index_select_dts(i32_dt), cuda, indexing::index_select_i32);

    table.register(Gather, &gather_dts(f32), cuda, indexing::gather_f32);
    table.register(Gather, &gather_dts(f64), cuda, indexing::gather_f64);
    table.register(Gather, &gather_dts(i32_dt), cuda, indexing::gather_i32);

    table.register(MaskedFill, &masked_dts(f32), cuda, indexing::masked_fill_f32);
    table.register(MaskedFill, &masked_dts(f64), cuda, indexing::masked_fill_f64);
    table.register(MaskedFill, &masked_dts(i32_dt), cuda, indexing::masked_fill_i32);

    table.register(ScatterAdd, &scatter_dts(f32), cuda, indexing::scatter_add_f32);
    table.register(ScatterAdd, &scatter_dts(f64), cuda, indexing::scatter_add_f64);

    // ----- Int-GEMM — S8/U8 RRR Identity (alpha.28; W8A8 phase 1).
    // Registers at the MatMul OpKind with the [int, int, int] key.
    let i8_dt = DType::I8;
    let u8_dt = DType::U8;
    table.register(MatMul, &[i8_dt, i8_dt, i8_dt], cuda, gemm_int::gemm_s8_rrr);
    table.register(MatMul, &[u8_dt, u8_dt, u8_dt], cuda, gemm_int::gemm_u8_rrr);

    // ----- ArgMaxDim / ArgMinDim — U32 output (alpha.28 added u32/i32 outputs).
    // Net-new dtype coverage on CUDA: PTX path is F32-only.
    let u32_dt = DType::U32;
    let arg_dts = |dt: DType| [dt, u32_dt];
    table.register(ArgMaxDim, &arg_dts(f32),  cuda, arg_reduce::argmax_dim_u32_f32);
    table.register(ArgMinDim, &arg_dts(f32),  cuda, arg_reduce::argmin_dim_u32_f32);
    table.register(ArgMaxDim, &arg_dts(f64),  cuda, arg_reduce::argmax_dim_u32_f64);
    table.register(ArgMinDim, &arg_dts(f64),  cuda, arg_reduce::argmin_dim_u32_f64);
    table.register(ArgMaxDim, &arg_dts(f16),  cuda, arg_reduce::argmax_dim_u32_f16);
    table.register(ArgMinDim, &arg_dts(f16),  cuda, arg_reduce::argmin_dim_u32_f16);
    table.register(ArgMaxDim, &arg_dts(bf16), cuda, arg_reduce::argmax_dim_u32_bf16);
    table.register(ArgMinDim, &arg_dts(bf16), cuda, arg_reduce::argmin_dim_u32_bf16);

    // ----- PowI — integer-exponent power (alpha.28).
    // Net-new dtype coverage on CUDA for F64/F16/BF16; F32 is a sibling.
    table.register(PowIElementwise, &u(f32),  cuda, powi::powi_f32);
    table.register(PowIElementwise, &u(f64),  cuda, powi::powi_f64);
    table.register(PowIElementwise, &u(f16),  cuda, powi::powi_f16);
    table.register(PowIElementwise, &u(bf16), cuda, powi::powi_bf16);

    // ----- Clamp — scalar bounds → broadcast-tensor ternary clamp.
    // Net-new dtype coverage on CUDA for F64/F16/BF16; F32 is a sibling.
    table.register(ClampElementwise, &u(f32),  cuda, clamp::clamp_f32);
    table.register(ClampElementwise, &u(f64),  cuda, clamp::clamp_f64);
    table.register(ClampElementwise, &u(f16),  cuda, clamp::clamp_f16);
    table.register(ClampElementwise, &u(bf16), cuda, clamp::clamp_bf16);

    // ----- Concat — N-ary via chained baracuda concat2.
    // Net-new dtype coverage on CUDA for F64/F16/BF16; F32 is a sibling.
    table.register(Concat, &u(f32),  cuda, concat::concat_f32);
    table.register(Concat, &u(f64),  cuda, concat::concat_f64);
    table.register(Concat, &u(f16),  cuda, concat::concat_f16);
    table.register(Concat, &u(bf16), cuda, concat::concat_bf16);

    // ----- Affine — `y = mul * x + add` (scalar in OpParams::Affine).
    // Net-new dtype coverage on CUDA: PTX path is f32 only.
    table.register(Affine, &u(f32),  cuda, affine::affine_f32);
    table.register(Affine, &u(f64),  cuda, affine::affine_f64);
    table.register(Affine, &u(f16),  cuda, affine::affine_f16);
    table.register(Affine, &u(bf16), cuda, affine::affine_bf16);
    table.register(Affine, &u(DType::I32), cuda, affine::affine_i32);
    table.register(Affine, &u(DType::I64), cuda, affine::affine_i64);
    table.register(Affine, &u(DType::U8),  cuda, affine::affine_u8);

    // ----- Cast — 8×8 baracuda surface less I8/I16/F8/F4 (not in Fuel).
    // U32 collapses to baracuda i32 at the FFI level (bit-identical for
    // non-negative values — same trick as IndexSelect's index dtype).
    // Mirrors the pairs Fuel's PTX cast_cuda_wrapper already registers,
    // plus a few extras (e.g. F16↔I64, BF16↔I64) that baracuda exposes.
    let cast_dtypes = [
        DType::F32, DType::F64, DType::F16, DType::BF16,
        DType::I32, DType::U32, DType::I64, DType::U8,
    ];
    for &src in &cast_dtypes {
        for &dst in &cast_dtypes {
            table.register(Cast, &[src, dst], cuda, cast::cast_baracuda_wrapper);
        }
    }

    // ----- F32 unary -----
    table.register(NegElementwise,    &u(f32), cuda, unary::neg_f32);
    table.register(AbsElementwise,    &u(f32), cuda, unary::abs_f32);
    table.register(SignElementwise,   &u(f32), cuda, unary::sign_f32);
    table.register(SqrElementwise,    &u(f32), cuda, unary::sqr_f32);
    table.register(SqrtElementwise,   &u(f32), cuda, unary::sqrt_f32);
    table.register(RecipElementwise,  &u(f32), cuda, unary::recip_f32);
    table.register(ExpElementwise,    &u(f32), cuda, unary::exp_f32);
    table.register(LogElementwise,    &u(f32), cuda, unary::log_f32);
    table.register(SinElementwise,    &u(f32), cuda, unary::sin_f32);
    table.register(CosElementwise,    &u(f32), cuda, unary::cos_f32);
    table.register(TanhElementwise,   &u(f32), cuda, unary::tanh_f32);
    table.register(ReluElementwise,   &u(f32), cuda, unary::relu_f32);
    table.register(GeluElementwise,   &u(f32), cuda, unary::gelu_f32);
    table.register(SiluElementwise,   &u(f32), cuda, unary::silu_f32);
    table.register(SigmoidElementwise, &u(f32), cuda, unary::sigmoid_f32);

    // ----- F16 unary (net-new dtype coverage for CUDA — PTX path is
    //       f32-only today) -----
    table.register(NegElementwise,    &u(f16), cuda, unary::neg_f16);
    table.register(AbsElementwise,    &u(f16), cuda, unary::abs_f16);
    table.register(SqrElementwise,    &u(f16), cuda, unary::sqr_f16);
    table.register(SqrtElementwise,   &u(f16), cuda, unary::sqrt_f16);
    table.register(RecipElementwise,  &u(f16), cuda, unary::recip_f16);
    table.register(ExpElementwise,    &u(f16), cuda, unary::exp_f16);
    table.register(LogElementwise,    &u(f16), cuda, unary::log_f16);
    table.register(SinElementwise,    &u(f16), cuda, unary::sin_f16);
    table.register(CosElementwise,    &u(f16), cuda, unary::cos_f16);
    table.register(TanhElementwise,   &u(f16), cuda, unary::tanh_f16);
    table.register(ReluElementwise,   &u(f16), cuda, unary::relu_f16);
    table.register(GeluElementwise,   &u(f16), cuda, unary::gelu_f16);
    table.register(SiluElementwise,   &u(f16), cuda, unary::silu_f16);
    table.register(SigmoidElementwise, &u(f16), cuda, unary::sigmoid_f16);

    // ----- BF16 unary -----
    table.register(NegElementwise,    &u(bf16), cuda, unary::neg_bf16);
    table.register(AbsElementwise,    &u(bf16), cuda, unary::abs_bf16);
    table.register(SqrElementwise,    &u(bf16), cuda, unary::sqr_bf16);
    table.register(SqrtElementwise,   &u(bf16), cuda, unary::sqrt_bf16);
    table.register(RecipElementwise,  &u(bf16), cuda, unary::recip_bf16);
    table.register(ExpElementwise,    &u(bf16), cuda, unary::exp_bf16);
    table.register(LogElementwise,    &u(bf16), cuda, unary::log_bf16);
    table.register(SinElementwise,    &u(bf16), cuda, unary::sin_bf16);
    table.register(CosElementwise,    &u(bf16), cuda, unary::cos_bf16);
    table.register(TanhElementwise,   &u(bf16), cuda, unary::tanh_bf16);
    table.register(ReluElementwise,   &u(bf16), cuda, unary::relu_bf16);
    table.register(GeluElementwise,   &u(bf16), cuda, unary::gelu_bf16);
    table.register(SiluElementwise,   &u(bf16), cuda, unary::silu_bf16);
    table.register(SigmoidElementwise, &u(bf16), cuda, unary::sigmoid_bf16);

    // ----- F64 unary -----
    table.register(NegElementwise,    &u(f64), cuda, unary::neg_f64);
    table.register(AbsElementwise,    &u(f64), cuda, unary::abs_f64);
    table.register(SqrElementwise,    &u(f64), cuda, unary::sqr_f64);
    table.register(SqrtElementwise,   &u(f64), cuda, unary::sqrt_f64);
    table.register(RecipElementwise,  &u(f64), cuda, unary::recip_f64);
    table.register(ExpElementwise,    &u(f64), cuda, unary::exp_f64);
    table.register(LogElementwise,    &u(f64), cuda, unary::log_f64);
    table.register(SinElementwise,    &u(f64), cuda, unary::sin_f64);
    table.register(CosElementwise,    &u(f64), cuda, unary::cos_f64);
    table.register(TanhElementwise,   &u(f64), cuda, unary::tanh_f64);
    table.register(ReluElementwise,   &u(f64), cuda, unary::relu_f64);
    table.register(GeluElementwise,   &u(f64), cuda, unary::gelu_f64);
    table.register(SiluElementwise,   &u(f64), cuda, unary::silu_f64);
    table.register(SigmoidElementwise, &u(f64), cuda, unary::sigmoid_f64);
}
