//! Dispatch wrappers + registration for baracuda-kernels-sys-backed
//! kernels. Sibling to `dispatch::register_cuda_kernels` (PTX path) —
//! each kernel here registers as an alternative at the same
//! `(op_kind, dtypes, BackendId::Cuda)` key. Phase 7.6 step 9a's
//! append-on-register semantics keep them composable; step 9b's
//! route picker ranks by `PrecisionGuarantee` + telemetry.
//!
//! The boilerplate-explosion in this file (50+ unary kinds × 4
//! dtypes, plus binary / ternary / etc.) is generated by per-family
//! macros — adding a new (op, dtype) entry is one manifest line
//! here + one matching line in `fuel-cuda-backend::baracuda`.

#![cfg(feature = "cuda")]

use std::sync::{Arc, RwLock};

use fuel_core_types::{Layout, Error, Result, probe::BackendId};
use fuel_core_types::dispatch::OpKind;
use fuel_core_types::DType;

use crate::kernel::{KernelBindingTable, KernelCaps, OpParams};
use crate::Storage;

// Re-use the storage-helpers from dispatch.rs so we read/write
// CudaStorageBytes the same way the PTX wrappers do.
use crate::dispatch::{cuda_input, cuda_output, read_storage, write_storage};

/// Generate one CUDA unary dispatch wrapper that adapts a baracuda
/// `fn(&CudaStorageBytes, Option<&Layout>) -> Result<CudaStorageBytes>`
/// kernel into the `KernelRef` signature the binding table expects.
///
/// Arguments:
/// - `$wrapper_name` — the function symbol to emit.
/// - `$baracuda_fn` — fully-qualified path to the baracuda kernel
///   function (e.g. `fuel_cuda_backend::baracuda::elementwise::unary_neg_f32`).
macro_rules! cuda_unary_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            layouts: &[Layout],
            _params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input, got {}"),
                    inputs.len(),
                ))
                .bt());
            }
            if outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 output, got {}"),
                    outputs.len(),
                ))
                .bt());
            }
            let layout = layouts.first();
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, layout)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

/// Generate one CUDA binary dispatch wrapper.
macro_rules! cuda_binary_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            layouts: &[Layout],
            _params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 2 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 2 inputs, got {}"),
                    inputs.len(),
                ))
                .bt());
            }
            if outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 output, got {}"),
                    outputs.len(),
                ))
                .bt());
            }
            let lhs_layout = layouts.first();
            let rhs_layout = layouts.get(1);
            let lhs_guard = read_storage(&inputs[0])?;
            let rhs_guard = read_storage(&inputs[1])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let lhs_cuda = cuda_input(&lhs_guard)?;
            let rhs_cuda = cuda_input(&rhs_guard)?;
            let result = $baracuda_fn(lhs_cuda, rhs_cuda, lhs_layout, rhs_layout)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

/// Generate a CUDA RoPE dispatch wrapper that pulls
/// `(outer_count, seq, head_dim)` from `OpParams::Rope` and
/// forwards to a baracuda RoPE kernel.
macro_rules! cuda_rope_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(
                        stringify!($wrapper_name),
                        ": expected 1 input + 1 output, got {} + {}",
                    ),
                    inputs.len(), outputs.len(),
                ))
                .bt());
            }
            let (outer_count, seq, head_dim) = match params {
                OpParams::Rope { outer_count, seq, head_dim } => {
                    (*outer_count, *seq, *head_dim)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(
                            stringify!($wrapper_name),
                            ": expected OpParams::Rope, got {:?}",
                        ),
                        other,
                    ))
                    .bt());
                }
            };
            let layout = layouts.first();
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, layout, outer_count, seq, head_dim)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

/// Generate a CUDA index_select dispatch wrapper. Two inputs
/// `(src, indices)`; pulls the shape params from
/// `OpParams::IndexSelect`.
macro_rules! cuda_index_select_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 2 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(
                        stringify!($wrapper_name),
                        ": expected 2 inputs + 1 output, got {} + {}",
                    ),
                    inputs.len(), outputs.len(),
                ))
                .bt());
            }
            let (outer_count, source_dim_size, n_indices, inner_count) = match params {
                OpParams::IndexSelect { outer_count, source_dim_size, n_indices, inner_count } => {
                    (*outer_count, *source_dim_size, *n_indices, *inner_count)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(
                            stringify!($wrapper_name),
                            ": expected OpParams::IndexSelect, got {:?}",
                        ),
                        other,
                    ))
                    .bt());
                }
            };
            let src_guard = read_storage(&inputs[0])?;
            let idx_guard = read_storage(&inputs[1])?;
            if idx_guard.dtype != DType::U32 {
                return Err(Error::Msg(format!(
                    concat!(
                        stringify!($wrapper_name),
                        ": indices must be U32, got {:?}",
                    ),
                    idx_guard.dtype,
                ))
                .bt());
            }
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&src_guard)?;
            let idx_cuda = cuda_input(&idx_guard)?;
            let result = $baracuda_fn(
                src_cuda, idx_cuda, outer_count, source_dim_size, n_indices, inner_count,
            )?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

// ===========================================================================
// Indexing — IndexSelect wrappers
// ===========================================================================

macro_rules! cuda_gather_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 2 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 2 inputs + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let (source_shape, output_shape, dim) = match params {
                OpParams::Gather { source_shape, output_shape, dim } => {
                    (source_shape.clone(), output_shape.clone(), *dim)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::Gather, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let src_guard = read_storage(&inputs[0])?;
            let idx_guard = read_storage(&inputs[1])?;
            if idx_guard.dtype != DType::U32 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": indices must be U32, got {:?}"),
                    idx_guard.dtype,
                )).bt());
            }
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&src_guard)?;
            let idx_cuda = cuda_input(&idx_guard)?;
            let result = $baracuda_fn(src_cuda, idx_cuda, &source_shape, &output_shape, dim)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

macro_rules! cuda_scatter_add_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 3 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 3 inputs + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let (base_shape, src_shape, dim) = match params {
                OpParams::ScatterAdd { base_shape, src_shape, dim } => {
                    (base_shape.clone(), src_shape.clone(), *dim)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::ScatterAdd, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let base_guard = read_storage(&inputs[0])?;
            let idx_guard = read_storage(&inputs[1])?;
            if idx_guard.dtype != DType::U32 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": indices must be U32, got {:?}"),
                    idx_guard.dtype,
                )).bt());
            }
            let src_guard = read_storage(&inputs[2])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let base_cuda = cuda_input(&base_guard)?;
            let idx_cuda = cuda_input(&idx_guard)?;
            let src_cuda = cuda_input(&src_guard)?;
            let result = $baracuda_fn(base_cuda, idx_cuda, src_cuda, &base_shape, &src_shape, dim)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

macro_rules! cuda_masked_fill_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 2 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 2 inputs + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let fill_bytes = match params {
                OpParams::MaskedFill { fill_bytes } => fill_bytes.clone(),
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::MaskedFill, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let src_guard = read_storage(&inputs[0])?;
            let mask_guard = read_storage(&inputs[1])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&src_guard)?;
            let mask_cuda = cuda_input(&mask_guard)?;
            let result = $baracuda_fn(src_cuda, mask_cuda, &fill_bytes)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

pub mod indexing {
    use super::*;
    use fuel_cuda_backend::baracuda::indexing as bk;

    cuda_index_select_baracuda_wrapper!(index_select_f32, bk::index_select_f32);
    cuda_index_select_baracuda_wrapper!(index_select_f64, bk::index_select_f64);
    cuda_index_select_baracuda_wrapper!(index_select_i32, bk::index_select_i32);

    cuda_gather_baracuda_wrapper!(gather_f32, bk::gather_f32);
    cuda_gather_baracuda_wrapper!(gather_f64, bk::gather_f64);
    cuda_gather_baracuda_wrapper!(gather_i32, bk::gather_i32);

    cuda_scatter_add_baracuda_wrapper!(scatter_add_f32, bk::scatter_add_f32);
    cuda_scatter_add_baracuda_wrapper!(scatter_add_f64, bk::scatter_add_f64);

    cuda_masked_fill_baracuda_wrapper!(masked_fill_f32, bk::masked_fill_f32);
    cuda_masked_fill_baracuda_wrapper!(masked_fill_f64, bk::masked_fill_f64);
    cuda_masked_fill_baracuda_wrapper!(masked_fill_i32, bk::masked_fill_i32);
}

// ===========================================================================
// Int-GEMM — S8/U8 RRR Identity (W8A8 phase 1)
// ===========================================================================
//
// Baracuda's `gemm_{s8,u8}_rrr_sm80_run` are RRR-layout (row-major ×
// row-major → row-major), Identity-epilogue Int8 tensor-core GEMM.
// Mirror `Op::MatMul`'s shape contract directly — registering at
// `(MatMul, [I8, I8, I8], Cuda)` and `[U8, U8, U8]` keys, so the
// existing `OpParams::Matmul { m, n, k, lhs/rhs_batch_dims }` flows
// through unchanged.
//
// Bias / BiasRelu / BiasGelu / BiasSilu epilogues are not yet wired
// — those need a `FusedLinearInt` op (or extending FusedLinear with
// int dtypes), which is a separate session.

macro_rules! cuda_gemm_int_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path $(,)?) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 2 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(
                        stringify!($wrapper_name),
                        ": expected 2 inputs + 1 output, got {} + {}",
                    ),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let (lhs_batch_dims, rhs_batch_dims, m, n, k) = match params {
                OpParams::Matmul { lhs_batch_dims, rhs_batch_dims, m, n, k } => {
                    (lhs_batch_dims.clone(), rhs_batch_dims.clone(), *m, *n, *k)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::Matmul, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let lhs_guard = read_storage(&inputs[0])?;
            let rhs_guard = read_storage(&inputs[1])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let lhs_cuda = cuda_input(&lhs_guard)?;
            let rhs_cuda = cuda_input(&rhs_guard)?;
            let result = $baracuda_fn(
                lhs_cuda, rhs_cuda, &lhs_batch_dims, &rhs_batch_dims, m, n, k,
            )?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

pub mod gemm_int {
    use super::*;
    use fuel_cuda_backend::baracuda::gemm_int as bk;

    cuda_gemm_int_baracuda_wrapper!(gemm_s8_rrr, bk::gemm_s8_rrr);
    cuda_gemm_int_baracuda_wrapper!(gemm_u8_rrr, bk::gemm_u8_rrr);
}

// ===========================================================================
// ArgMaxDim / ArgMinDim — U32-output variants (alpha.28)
// ===========================================================================
//
// Pulls `dim` from `OpParams::Reduce { dims, keepdim: _ }` with the
// single-dim constraint Fuel's PTX argmax/argmin paths enforce.
// Output is U32 indices in the squeezed (rank N-1) shape.

macro_rules! cuda_arg_reduce_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path $(,)?) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let dim = match params {
                OpParams::Reduce { dims, keepdim: _ } => {
                    if dims.len() != 1 {
                        return Err(Error::Msg(format!(
                            concat!(stringify!($wrapper_name), ": expected a single reduce dim, got {:?}"),
                            dims,
                        )).bt());
                    }
                    dims[0]
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::Reduce, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let layout = layouts.first().ok_or_else(|| {
                Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": layouts empty"),
                )).bt()
            })?;
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, layout, dim)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

pub mod arg_reduce {
    use super::*;
    use fuel_cuda_backend::baracuda::arg_reduce as bk;

    cuda_arg_reduce_baracuda_wrapper!(argmax_dim_u32_f32, bk::argmax_dim_u32_f32);
    cuda_arg_reduce_baracuda_wrapper!(argmin_dim_u32_f32, bk::argmin_dim_u32_f32);
    cuda_arg_reduce_baracuda_wrapper!(argmax_dim_u32_f64, bk::argmax_dim_u32_f64);
    cuda_arg_reduce_baracuda_wrapper!(argmin_dim_u32_f64, bk::argmin_dim_u32_f64);
    cuda_arg_reduce_baracuda_wrapper!(argmax_dim_u32_f16, bk::argmax_dim_u32_f16);
    cuda_arg_reduce_baracuda_wrapper!(argmin_dim_u32_f16, bk::argmin_dim_u32_f16);
    cuda_arg_reduce_baracuda_wrapper!(argmax_dim_u32_bf16, bk::argmax_dim_u32_bf16);
    cuda_arg_reduce_baracuda_wrapper!(argmin_dim_u32_bf16, bk::argmin_dim_u32_bf16);
}

// ===========================================================================
// PowI — `y = x^n` with integer exponent (OpParams::PowI { exp })
// ===========================================================================
//
// Alpha.28 added `unary_powi_<dtype>_run` over f32/f64/f16/bf16 plus
// matching backward kernels. Power-by-squaring on device — correct on
// negative bases, no `pow(x, n as f32)` shim needed. Exponent ships
// via `p0: f32` (round-trips exactly for |n| ≤ 2^24).

macro_rules! cuda_powi_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path $(,)?) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let exp = match params {
                OpParams::PowI { exp } => *exp,
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::PowI, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let layout = layouts.first();
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, layout, exp)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

pub mod powi {
    use super::*;
    use fuel_cuda_backend::baracuda::powi as bk;

    cuda_powi_baracuda_wrapper!(powi_f32, bk::powi_f32);
    cuda_powi_baracuda_wrapper!(powi_f64, bk::powi_f64);
    cuda_powi_baracuda_wrapper!(powi_f16, bk::powi_f16);
    cuda_powi_baracuda_wrapper!(powi_bf16, bk::powi_bf16);
}

// ===========================================================================
// Clamp — scalar (min, max) → broadcast-tensor ternary clamp
// ===========================================================================
//
// Fuel's `OpKind::ClampElementwise` carries `(min, max)` in
// `OpParams::Clamp`; baracuda's `ternary_clamp` accepts two bound
// tensors. The per-dtype wrapper allocates two 1-element device
// buffers (one per bound) inside the kernel module and invokes the
// strided variant with stride 0 on the bound axis.

macro_rules! cuda_clamp_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path, $scalar_ty:ty $(,)?) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let (min_f64, max_f64) = match params {
                OpParams::Clamp { min, max } => (*min, *max),
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::Clamp, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let layout = layouts.first().ok_or_else(|| {
                Error::Msg(concat!(
                    stringify!($wrapper_name),
                    ": Clamp requires an input layout (call with layouts[0])",
                ).to_string()).bt()
            })?;
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, layout, min_f64 as $scalar_ty, max_f64 as $scalar_ty)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

pub mod clamp {
    use super::*;
    use fuel_cuda_backend::baracuda::clamp as bk;

    cuda_clamp_baracuda_wrapper!(clamp_f32, bk::clamp_f32, f32);
    cuda_clamp_baracuda_wrapper!(clamp_f64, bk::clamp_f64, f64);
    cuda_clamp_baracuda_wrapper!(clamp_f16, bk::clamp_f16, f32);
    cuda_clamp_baracuda_wrapper!(clamp_bf16, bk::clamp_bf16, f32);
}

// ===========================================================================
// Concat — N-ary via N-1 chained baracuda concat2 calls
// ===========================================================================
//
// Baracuda only ships binary `concat2`. The wrapper chains N-1 calls
// to cover Fuel's `OpKind::Concat` N-input semantics. The route
// picker / Judge will tend to prefer the PTX 1-launch path for N > 2
// in practice; baracuda still wins on N == 2 where there's no
// launch-count tax.

macro_rules! cuda_concat_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path $(,)?) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.is_empty() {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": at least 1 input required"),
                )).bt());
            }
            if outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 output, got {}"),
                    outputs.len(),
                )).bt());
            }
            let (outer_count, input_dim_sizes, inner_count) = match params {
                OpParams::Concat { outer_count, input_dim_sizes, inner_count } => {
                    (*outer_count, input_dim_sizes.clone(), *inner_count)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::Concat, got {:?}"),
                        other,
                    )).bt());
                }
            };
            if input_dim_sizes.len() != inputs.len() {
                return Err(Error::Msg(format!(
                    concat!(
                        stringify!($wrapper_name),
                        ": OpParams declares {} inputs but the work item carries {}",
                    ),
                    input_dim_sizes.len(),
                    inputs.len(),
                )).bt());
            }
            let in_guards: Vec<_> = inputs
                .iter()
                .map(read_storage)
                .collect::<Result<Vec<_>>>()?;
            let mut in_cudas: Vec<&fuel_cuda_backend::CudaStorageBytes> =
                Vec::with_capacity(in_guards.len());
            for g in &in_guards {
                in_cudas.push(cuda_input(g)?);
            }
            let mut out_guard = write_storage(&outputs[0])?;
            let result = $baracuda_fn(&in_cudas, outer_count, &input_dim_sizes, inner_count)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

pub mod concat {
    use super::*;
    use fuel_cuda_backend::baracuda::concat as bk;

    cuda_concat_baracuda_wrapper!(concat_f32, bk::concat_f32);
    cuda_concat_baracuda_wrapper!(concat_f64, bk::concat_f64);
    cuda_concat_baracuda_wrapper!(concat_f16, bk::concat_f16);
    cuda_concat_baracuda_wrapper!(concat_bf16, bk::concat_bf16);
}

// ===========================================================================
// WriteSlice — in-place rectangular slab assignment (Phase 7.6 step 9c E.3.2)
// ===========================================================================
//
// The pipelined executor's WorkItemKind::WriteSlice branch wires
// `inputs=[source]` and `outputs=[dest_arc]` where outputs[0]'s Arc IS
// the destination's Storage Arc (zero-copy in-place adoption). The
// wrapper holds a write lock on outputs[0] and a read lock on inputs[0],
// then asks baracuda's byte-width-dispatched kernel to mutate dest in
// place.
//
// Byte-width-keyed (not dtype-keyed): both source and dest dtype are
// uniform (canonicalized to `[T_src, T_out]` by build_lookup_dtypes),
// and the kernel only cares about element size — there's no arithmetic.
// One wrapper per byte width covers all aligned-element dtypes.

macro_rules! cuda_write_slice_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let (dest_shape, ranges) = match params {
                OpParams::WriteSlice { dest_shape, ranges } => (dest_shape, ranges),
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::WriteSlice, got {:?}"),
                        other,
                    )).bt());
                }
            };
            // Derive source_shape + range_start from the ranges. The
            // executor has already validated rank + bounds at compile
            // time; this is the kernel's last-line input shaping.
            let rank = dest_shape.len();
            let mut source_shape = Vec::with_capacity(rank);
            let mut range_start = Vec::with_capacity(rank);
            for &(start, end) in ranges.iter() {
                source_shape.push(end - start);
                range_start.push(start);
            }

            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let dest_cuda = cuda_output(&mut out_guard)?;
            $baracuda_fn(dest_cuda, src_cuda, dest_shape, &source_shape, &range_start)
        }
    };
}

pub mod write_slice {
    use super::*;
    use fuel_cuda_backend::baracuda::write_slice as bk;

    cuda_write_slice_baracuda_wrapper!(write_slice_b1,  bk::write_slice_b1);
    cuda_write_slice_baracuda_wrapper!(write_slice_b2,  bk::write_slice_b2);
    cuda_write_slice_baracuda_wrapper!(write_slice_b4,  bk::write_slice_b4);
    cuda_write_slice_baracuda_wrapper!(write_slice_b8,  bk::write_slice_b8);
    cuda_write_slice_baracuda_wrapper!(write_slice_b16, bk::write_slice_b16);
}

// ===========================================================================
// Triu / Tril — upper / lower triangular mask (Phase 7.6 step 9c E.3.2.4)
// ===========================================================================
//
// Per-dtype kernels (7 dtypes: f16/bf16/f32/f64/i32/i64/bool). Wrappers
// destructure OpParams::Triangular { batch_count, rows, cols, diagonal }
// and call the matching baracuda symbol. The kernel allocates a fresh
// output buffer (no in-place semantics).

macro_rules! cuda_triangular_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let (batch, rows, cols, diag) = match params {
                OpParams::Triangular { batch_count, rows, cols, diagonal } => {
                    (*batch_count, *rows, *cols, *diagonal)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::Triangular, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let layout = layouts.first();
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, layout, batch, rows, cols, diag)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

pub mod triangular {
    use super::*;
    use fuel_cuda_backend::baracuda::triangular as bk;

    // Triu
    cuda_triangular_baracuda_wrapper!(triu_f32,  bk::triu_f32);
    cuda_triangular_baracuda_wrapper!(triu_f64,  bk::triu_f64);
    cuda_triangular_baracuda_wrapper!(triu_f16,  bk::triu_f16);
    cuda_triangular_baracuda_wrapper!(triu_bf16, bk::triu_bf16);
    cuda_triangular_baracuda_wrapper!(triu_i32,  bk::triu_i32);
    cuda_triangular_baracuda_wrapper!(triu_i64,  bk::triu_i64);
    cuda_triangular_baracuda_wrapper!(triu_bool, bk::triu_bool);

    // Tril
    cuda_triangular_baracuda_wrapper!(tril_f32,  bk::tril_f32);
    cuda_triangular_baracuda_wrapper!(tril_f64,  bk::tril_f64);
    cuda_triangular_baracuda_wrapper!(tril_f16,  bk::tril_f16);
    cuda_triangular_baracuda_wrapper!(tril_bf16, bk::tril_bf16);
    cuda_triangular_baracuda_wrapper!(tril_i32,  bk::tril_i32);
    cuda_triangular_baracuda_wrapper!(tril_i64,  bk::tril_i64);
    cuda_triangular_baracuda_wrapper!(tril_bool, bk::tril_bool);
}

// ===========================================================================
// Flip — single-axis reverse (baracuda alpha.27, integrated alpha.29)
// ===========================================================================

macro_rules! cuda_flip_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let (outer, dim_size, inner) = match params {
                OpParams::Flip { outer_count, dim_size, inner_count } => {
                    (*outer_count, *dim_size, *inner_count)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::Flip, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, outer, dim_size, inner)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

pub mod flip {
    use super::*;
    use fuel_cuda_backend::baracuda::flip as bk;

    cuda_flip_baracuda_wrapper!(flip_f32,  bk::flip_f32);
    cuda_flip_baracuda_wrapper!(flip_f64,  bk::flip_f64);
    cuda_flip_baracuda_wrapper!(flip_f16,  bk::flip_f16);
    cuda_flip_baracuda_wrapper!(flip_bf16, bk::flip_bf16);
}

// ===========================================================================
// Roll — single-axis cyclic shift (baracuda alpha.27, integrated alpha.29)
// ===========================================================================

macro_rules! cuda_roll_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let (outer, dim_size, inner, shift) = match params {
                OpParams::Roll { outer_count, dim_size, inner_count, shift } => {
                    (*outer_count, *dim_size, *inner_count, *shift)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::Roll, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, outer, dim_size, inner, shift)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

pub mod roll {
    use super::*;
    use fuel_cuda_backend::baracuda::roll as bk;

    cuda_roll_baracuda_wrapper!(roll_f32,  bk::roll_f32);
    cuda_roll_baracuda_wrapper!(roll_f64,  bk::roll_f64);
    cuda_roll_baracuda_wrapper!(roll_f16,  bk::roll_f16);
    cuda_roll_baracuda_wrapper!(roll_bf16, bk::roll_bf16);
}

// ===========================================================================
// CumSum — inclusive prefix sum along one axis (baracuda alpha.27,
//          integrated alpha.29).
// ===========================================================================

macro_rules! cuda_cumsum_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let (outer, dim_size, inner) = match params {
                OpParams::CumSum { outer_count, dim_size, inner_count } => {
                    (*outer_count, *dim_size, *inner_count)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::CumSum, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, outer, dim_size, inner)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

pub mod cumsum {
    use super::*;
    use fuel_cuda_backend::baracuda::cumsum as bk;

    cuda_cumsum_baracuda_wrapper!(cumsum_f32,  bk::cumsum_f32);
    cuda_cumsum_baracuda_wrapper!(cumsum_f64,  bk::cumsum_f64);
    cuda_cumsum_baracuda_wrapper!(cumsum_f16,  bk::cumsum_f16);
    cuda_cumsum_baracuda_wrapper!(cumsum_bf16, bk::cumsum_bf16);
}

// ===========================================================================
// Pad — multi-dim padding with Constant/Reflect/Replicate modes
//       (baracuda alpha.29; Circular mode exists in baracuda but
//        fuel-graph's IR doesn't emit it yet).
// ===========================================================================

/// Decode the pre-encoded `fill_bytes` to a typed value. Constant-mode
/// Pad's OpParams carries fill_bytes already in the output's dtype
/// (encode_value_to_bytes does that at op_to_op_params time). Here we
/// reinterpret the bytes back to the matching scalar type.
fn decode_fill_f32(b: &[u8]) -> Result<f32> {
    if b.len() != 4 {
        return Err(Error::Msg(format!(
            "pad_constant_f32: fill_bytes.len()={} != 4", b.len(),
        )).bt());
    }
    Ok(f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
}
fn decode_fill_f64(b: &[u8]) -> Result<f64> {
    if b.len() != 8 {
        return Err(Error::Msg(format!(
            "pad_constant_f64: fill_bytes.len()={} != 8", b.len(),
        )).bt());
    }
    Ok(f64::from_le_bytes([b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7]]))
}
fn decode_fill_f16(b: &[u8]) -> Result<half::f16> {
    if b.len() != 2 {
        return Err(Error::Msg(format!(
            "pad_constant_f16: fill_bytes.len()={} != 2", b.len(),
        )).bt());
    }
    Ok(half::f16::from_le_bytes([b[0], b[1]]))
}
fn decode_fill_bf16(b: &[u8]) -> Result<half::bf16> {
    if b.len() != 2 {
        return Err(Error::Msg(format!(
            "pad_constant_bf16: fill_bytes.len()={} != 2", b.len(),
        )).bt());
    }
    Ok(half::bf16::from_le_bytes([b[0], b[1]]))
}

/// Generate per-dtype Pad-forward wrapper. Reads `OpParams::Pad`,
/// dispatches on `mode_tag` (0=Constant, 1=Reflect, 2=Replicate);
/// returns Unsupported for any other tag (baracuda has Circular but
/// fuel-graph doesn't emit it today).
macro_rules! cuda_pad_baracuda_wrapper {
    ($wrapper_name:ident, $const_fn:path, $reflect_fn:path, $replicate_fn:path, $decode_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let (in_shape, out_shape, padding, mode_tag, fill_bytes) = match params {
                OpParams::Pad { in_shape, out_shape, padding, mode_tag, fill_bytes } => {
                    (in_shape, out_shape, padding, *mode_tag, fill_bytes)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::Pad, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = match mode_tag {
                0 => {
                    let value = $decode_fn(fill_bytes)?;
                    $const_fn(src_cuda, in_shape, out_shape, padding, value)?
                }
                1 => $reflect_fn(src_cuda, in_shape, out_shape, padding)?,
                2 => $replicate_fn(src_cuda, in_shape, out_shape, padding)?,
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": mode_tag {} not supported \
                         (Constant=0, Reflect=1, Replicate=2; Circular=3 not yet)"),
                        other,
                    )).bt());
                }
            };
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

/// Generate per-dtype PadBackward wrapper. Only Constant-mode backward
/// is supported (the other modes' backwards aren't shipped in baracuda
/// alpha.29; the CPU path remains the only target for them).
macro_rules! cuda_pad_backward_baracuda_wrapper {
    ($wrapper_name:ident, $bw_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            _layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let (in_shape, out_shape, padding, mode_tag) = match params {
                OpParams::PadBackward { in_shape, out_shape, padding, mode_tag } => {
                    (in_shape, out_shape, padding, *mode_tag)
                }
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::PadBackward, got {:?}"),
                        other,
                    )).bt());
                }
            };
            if mode_tag != 0 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": only Constant-mode backward (tag 0) supported \
                     on CUDA today, got mode_tag {}"),
                    mode_tag,
                )).bt());
            }
            // OpParams::PadBackward layout: in_shape = forward x shape
            // (= dx shape), out_shape = forward y shape (= dy shape).
            // baracuda's pad_constant_backward takes input_shape (= dx
            // shape) and pad_low; dy_shape is implied. We pass both
            // through to fuel-cuda's pad_backward wrapper so its stride
            // arrays are computed correctly.
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let dy_cuda = cuda_input(&in_guard)?;
            let result = $bw_fn(dy_cuda, in_shape, out_shape, padding)?;
            let dx_cuda = cuda_output(&mut out_guard)?;
            *dx_cuda = result;
            Ok(())
        }
    };
}

pub mod pad {
    use super::*;
    use fuel_cuda_backend::baracuda::pad as bk;

    cuda_pad_baracuda_wrapper!(
        pad_f32,
        bk::pad_constant_f32, bk::pad_reflect_f32, bk::pad_replicate_f32,
        super::decode_fill_f32
    );
    cuda_pad_baracuda_wrapper!(
        pad_f64,
        bk::pad_constant_f64, bk::pad_reflect_f64, bk::pad_replicate_f64,
        super::decode_fill_f64
    );
    cuda_pad_baracuda_wrapper!(
        pad_f16,
        bk::pad_constant_f16, bk::pad_reflect_f16, bk::pad_replicate_f16,
        super::decode_fill_f16
    );
    cuda_pad_baracuda_wrapper!(
        pad_bf16,
        bk::pad_constant_bf16, bk::pad_reflect_bf16, bk::pad_replicate_bf16,
        super::decode_fill_bf16
    );

    cuda_pad_backward_baracuda_wrapper!(pad_backward_f32,  bk::pad_backward_f32);
    cuda_pad_backward_baracuda_wrapper!(pad_backward_f64,  bk::pad_backward_f64);
    cuda_pad_backward_baracuda_wrapper!(pad_backward_f16,  bk::pad_backward_f16);
    cuda_pad_backward_baracuda_wrapper!(pad_backward_bf16, bk::pad_backward_bf16);
}

// ===========================================================================
// Affine — `y = mul * x + add` with scalar (mul, add) per OpParams::Affine
// ===========================================================================
//
// Per-dtype wrappers; baracuda's FFI carries (a, b) in the natural
// per-dtype arithmetic type (f32 for f16/bf16 storage; f64 for f64
// storage; per-element int type for i32/i64/u8). The wrappers cast
// Fuel's `(f64, f64)` OpParams down to the right type at the FFI
// boundary.

macro_rules! cuda_affine_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path, $scalar_cast:expr $(,)?) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input + 1 output, got {} + {}"),
                    inputs.len(), outputs.len(),
                )).bt());
            }
            let (mul_f64, add_f64) = match params {
                OpParams::Affine { mul, add } => (*mul, *add),
                other => {
                    return Err(Error::Msg(format!(
                        concat!(stringify!($wrapper_name), ": expected OpParams::Affine, got {:?}"),
                        other,
                    )).bt());
                }
            };
            let cast = $scalar_cast;
            let mul = cast(mul_f64);
            let add = cast(add_f64);
            let layout = layouts.first();
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, layout, mul, add)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

pub mod affine {
    use super::*;
    use fuel_cuda_backend::baracuda::affine as bk;

    cuda_affine_baracuda_wrapper!(affine_f32, bk::affine_f32, |v: f64| v as f32);
    cuda_affine_baracuda_wrapper!(affine_f64, bk::affine_f64, |v: f64| v);
    cuda_affine_baracuda_wrapper!(affine_f16, bk::affine_f16, |v: f64| v as f32);
    cuda_affine_baracuda_wrapper!(affine_bf16, bk::affine_bf16, |v: f64| v as f32);
    cuda_affine_baracuda_wrapper!(affine_i32, bk::affine_i32, |v: f64| v as i32);
    cuda_affine_baracuda_wrapper!(affine_i64, bk::affine_i64, |v: f64| v as i64);
    cuda_affine_baracuda_wrapper!(affine_u8, bk::affine_u8, |v: f64| v as u8);
}

// ===========================================================================
// Cast — single wrapper across every (src_dt, dst_dt) pair baracuda exposes
// ===========================================================================
//
// Cast's binding-table key is `[src_dt, dst_dt]` (two dtypes, not the
// usual unary `[dt, dt]`). The wrapper reads both dtypes from the
// input/output Storage and dispatches into
// `fuel_cuda_backend::baracuda::cast::dispatch`, which picks the right
// FFI symbol from the 8×8 baracuda surface. One wrapper, many
// (per-pair) binding-table entries — same pattern as the PTX-backed
// `cast_cuda_wrapper` in [`crate::dispatch`].

pub mod cast {
    use super::*;
    use fuel_cuda_backend::baracuda::cast as bk;

    pub fn cast_baracuda_wrapper(
        inputs: &[Arc<RwLock<Storage>>],
        outputs: &mut [Arc<RwLock<Storage>>],
        _layouts: &[Layout],
        _params: &OpParams,
    ) -> Result<()> {
        if inputs.len() != 1 || outputs.len() != 1 {
            return Err(Error::Msg(format!(
                "cast_baracuda_wrapper: expected 1 input + 1 output, got {} + {}",
                inputs.len(),
                outputs.len(),
            ))
            .bt());
        }
        let in_guard = read_storage(&inputs[0])?;
        let mut out_guard = write_storage(&outputs[0])?;
        let src_dtype = in_guard.dtype;
        let dst_dtype = out_guard.dtype;
        let src_cuda = cuda_input(&in_guard)?;
        let result = bk::dispatch(src_cuda, src_dtype, dst_dtype)?;
        let out_cuda = cuda_output(&mut out_guard)?;
        *out_cuda = result;
        Ok(())
    }
}

/// Generate a CUDA softmax-last-dim dispatch wrapper that pulls
/// `(outer_count, last_dim)` from `OpParams::SoftmaxLastDim`
/// (or `LogSoftmaxLastDim`) and forwards to a baracuda softmax
/// kernel.
macro_rules! cuda_softmax_last_dim_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(
                        stringify!($wrapper_name),
                        ": expected 1 input + 1 output, got {} + {}",
                    ),
                    inputs.len(), outputs.len(),
                ))
                .bt());
            }
            // Validate params shape (outer_count + last_dim are now
            // implicit in the layout — the wrapper consumes only the
            // discriminant to confirm we got the expected OpKind).
            match params {
                OpParams::SoftmaxLastDim { .. } | OpParams::LogSoftmaxLastDim { .. } => {}
                other => {
                    return Err(Error::Msg(format!(
                        concat!(
                            stringify!($wrapper_name),
                            ": expected OpParams::SoftmaxLastDim/LogSoftmaxLastDim, got {:?}",
                        ),
                        other,
                    ))
                    .bt());
                }
            }
            let layout = layouts.first().ok_or_else(|| {
                Error::Msg(concat!(
                    stringify!($wrapper_name),
                    ": SoftmaxLastDim requires an input layout (call with layouts[0])",
                ).to_string()).bt()
            })?;
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, layout)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

// ===========================================================================
// Softmax wrappers (Softmax + LogSoftmax LastDim)
// ===========================================================================

pub mod softmax {
    use super::*;
    use fuel_cuda_backend::baracuda::softmax as bk;

    cuda_softmax_last_dim_baracuda_wrapper!(softmax_f32, bk::softmax_last_dim_f32);
    cuda_softmax_last_dim_baracuda_wrapper!(softmax_f16, bk::softmax_last_dim_f16);
    cuda_softmax_last_dim_baracuda_wrapper!(softmax_bf16, bk::softmax_last_dim_bf16);
    cuda_softmax_last_dim_baracuda_wrapper!(softmax_f64, bk::softmax_last_dim_f64);

    cuda_softmax_last_dim_baracuda_wrapper!(log_softmax_f32, bk::log_softmax_last_dim_f32);
    cuda_softmax_last_dim_baracuda_wrapper!(log_softmax_f16, bk::log_softmax_last_dim_f16);
    cuda_softmax_last_dim_baracuda_wrapper!(log_softmax_bf16, bk::log_softmax_last_dim_bf16);
    cuda_softmax_last_dim_baracuda_wrapper!(log_softmax_f64, bk::log_softmax_last_dim_f64);
}

// ===========================================================================
// Attention — RoPE wrappers
// ===========================================================================

pub mod attention {
    use super::*;
    use fuel_cuda_backend::baracuda::attention as bk;

    cuda_rope_baracuda_wrapper!(rope_f32, bk::rope_f32);
    cuda_rope_baracuda_wrapper!(rope_f16, bk::rope_f16);
    cuda_rope_baracuda_wrapper!(rope_bf16, bk::rope_bf16);
    cuda_rope_baracuda_wrapper!(rope_f64, bk::rope_f64);
}

/// Generate a CUDA norm-last-dim dispatch wrapper that pulls
/// `(outer_count, last_dim, eps)` from `OpParams::NormLastDim`
/// and forwards to a baracuda last-dim norm kernel.
macro_rules! cuda_norm_last_dim_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 || outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(
                        stringify!($wrapper_name),
                        ": expected 1 input + 1 output, got {} + {}",
                    ),
                    inputs.len(), outputs.len(),
                ))
                .bt());
            }
            let eps = match params {
                OpParams::NormLastDim { eps, .. } => *eps,
                other => {
                    return Err(Error::Msg(format!(
                        concat!(
                            stringify!($wrapper_name),
                            ": expected OpParams::NormLastDim, got {:?}",
                        ),
                        other,
                    ))
                    .bt());
                }
            };
            let layout = layouts.first().ok_or_else(|| {
                Error::Msg(concat!(
                    stringify!($wrapper_name),
                    ": NormLastDim requires an input layout (call with layouts[0])",
                ).to_string()).bt()
            })?;
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, layout, eps)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

// ===========================================================================
// Norm-last-dim wrappers (RmsNorm + LayerNorm)
// ===========================================================================

pub mod norm {
    use super::*;
    use fuel_cuda_backend::baracuda::norm as bk;

    cuda_norm_last_dim_baracuda_wrapper!(rms_f32, bk::rms_norm_last_dim_f32);
    cuda_norm_last_dim_baracuda_wrapper!(rms_f16, bk::rms_norm_last_dim_f16);
    cuda_norm_last_dim_baracuda_wrapper!(rms_bf16, bk::rms_norm_last_dim_bf16);
    cuda_norm_last_dim_baracuda_wrapper!(rms_f64, bk::rms_norm_last_dim_f64);

    cuda_norm_last_dim_baracuda_wrapper!(layer_f32, bk::layer_norm_last_dim_f32);
    cuda_norm_last_dim_baracuda_wrapper!(layer_f16, bk::layer_norm_last_dim_f16);
    cuda_norm_last_dim_baracuda_wrapper!(layer_bf16, bk::layer_norm_last_dim_bf16);
    cuda_norm_last_dim_baracuda_wrapper!(layer_f64, bk::layer_norm_last_dim_f64);
}

/// Generate one CUDA reduce dispatch wrapper. Reduce wrappers
/// destructure `OpParams::Reduce { dims, keepdim }` and forward
/// to the baracuda multi-axis driver.
macro_rules! cuda_reduce_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            layouts: &[Layout],
            params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input, got {}"),
                    inputs.len(),
                ))
                .bt());
            }
            if outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 output, got {}"),
                    outputs.len(),
                ))
                .bt());
            }
            let (dims, keepdim) = match params {
                OpParams::Reduce { dims, keepdim } => (dims.clone(), *keepdim),
                other => {
                    return Err(Error::Msg(format!(
                        concat!(
                            stringify!($wrapper_name),
                            ": expected OpParams::Reduce, got {:?}",
                        ),
                        other,
                    ))
                    .bt());
                }
            };
            let layout = layouts.first().ok_or_else(|| {
                Error::Msg(format!(
                    concat!(
                        stringify!($wrapper_name),
                        ": reduce requires an input layout (call with layouts[0])",
                    ),
                ))
                .bt()
            })?;
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, layout, &dims, keepdim)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

// ===========================================================================
// Reduce wrappers
// ===========================================================================

pub mod reduce {
    use super::*;
    use fuel_cuda_backend::baracuda::reduce as bk;

    cuda_reduce_baracuda_wrapper!(sum_f32, bk::reduce_sum_f32);
    cuda_reduce_baracuda_wrapper!(max_f32, bk::reduce_max_f32);
    cuda_reduce_baracuda_wrapper!(min_f32, bk::reduce_min_f32);
    cuda_reduce_baracuda_wrapper!(mean_f32, bk::reduce_mean_f32);

    cuda_reduce_baracuda_wrapper!(sum_f16, bk::reduce_sum_f16);
    cuda_reduce_baracuda_wrapper!(max_f16, bk::reduce_max_f16);
    cuda_reduce_baracuda_wrapper!(min_f16, bk::reduce_min_f16);
    cuda_reduce_baracuda_wrapper!(mean_f16, bk::reduce_mean_f16);

    cuda_reduce_baracuda_wrapper!(sum_bf16, bk::reduce_sum_bf16);
    cuda_reduce_baracuda_wrapper!(max_bf16, bk::reduce_max_bf16);
    cuda_reduce_baracuda_wrapper!(min_bf16, bk::reduce_min_bf16);
    cuda_reduce_baracuda_wrapper!(mean_bf16, bk::reduce_mean_bf16);

    cuda_reduce_baracuda_wrapper!(sum_f64, bk::reduce_sum_f64);
    cuda_reduce_baracuda_wrapper!(max_f64, bk::reduce_max_f64);
    cuda_reduce_baracuda_wrapper!(min_f64, bk::reduce_min_f64);
    cuda_reduce_baracuda_wrapper!(mean_f64, bk::reduce_mean_f64);
}

// ===========================================================================
// Elementwise binary wrappers
// ===========================================================================

pub mod binary {
    use super::*;
    use fuel_cuda_backend::baracuda::binary as bk;

    cuda_binary_baracuda_wrapper!(add_f32, bk::binary_add_f32);
    cuda_binary_baracuda_wrapper!(sub_f32, bk::binary_sub_f32);
    cuda_binary_baracuda_wrapper!(mul_f32, bk::binary_mul_f32);
    cuda_binary_baracuda_wrapper!(div_f32, bk::binary_div_f32);
    cuda_binary_baracuda_wrapper!(maximum_f32, bk::binary_maximum_f32);
    cuda_binary_baracuda_wrapper!(minimum_f32, bk::binary_minimum_f32);

    cuda_binary_baracuda_wrapper!(add_f16, bk::binary_add_f16);
    cuda_binary_baracuda_wrapper!(sub_f16, bk::binary_sub_f16);
    cuda_binary_baracuda_wrapper!(mul_f16, bk::binary_mul_f16);
    cuda_binary_baracuda_wrapper!(div_f16, bk::binary_div_f16);
    cuda_binary_baracuda_wrapper!(maximum_f16, bk::binary_maximum_f16);
    cuda_binary_baracuda_wrapper!(minimum_f16, bk::binary_minimum_f16);

    cuda_binary_baracuda_wrapper!(add_bf16, bk::binary_add_bf16);
    cuda_binary_baracuda_wrapper!(sub_bf16, bk::binary_sub_bf16);
    cuda_binary_baracuda_wrapper!(mul_bf16, bk::binary_mul_bf16);
    cuda_binary_baracuda_wrapper!(div_bf16, bk::binary_div_bf16);
    cuda_binary_baracuda_wrapper!(maximum_bf16, bk::binary_maximum_bf16);
    cuda_binary_baracuda_wrapper!(minimum_bf16, bk::binary_minimum_bf16);

    cuda_binary_baracuda_wrapper!(add_f64, bk::binary_add_f64);
    cuda_binary_baracuda_wrapper!(sub_f64, bk::binary_sub_f64);
    cuda_binary_baracuda_wrapper!(mul_f64, bk::binary_mul_f64);
    cuda_binary_baracuda_wrapper!(div_f64, bk::binary_div_f64);
    cuda_binary_baracuda_wrapper!(maximum_f64, bk::binary_maximum_f64);
    cuda_binary_baracuda_wrapper!(minimum_f64, bk::binary_minimum_f64);
}

// ===========================================================================
// Elementwise unary wrappers
// ===========================================================================
//
// Manifest: one line per (op, dtype) pair. Both halves of the
// `(*_wrapper, *_kernel)` mapping live here so the file is the single
// source of truth for "baracuda's coverage of Fuel's binding table."

pub mod unary {
    use super::*;
    use fuel_cuda_backend::baracuda::elementwise as bk;

    // f32 surface
    cuda_unary_baracuda_wrapper!(neg_f32, bk::unary_neg_f32);
    cuda_unary_baracuda_wrapper!(abs_f32, bk::unary_abs_f32);
    cuda_unary_baracuda_wrapper!(sign_f32, bk::unary_sign_f32);
    cuda_unary_baracuda_wrapper!(sqr_f32, bk::unary_sqr_f32);
    cuda_unary_baracuda_wrapper!(sqrt_f32, bk::unary_sqrt_f32);
    cuda_unary_baracuda_wrapper!(rsqrt_f32, bk::unary_rsqrt_f32);
    cuda_unary_baracuda_wrapper!(recip_f32, bk::unary_recip_f32);
    cuda_unary_baracuda_wrapper!(exp_f32, bk::unary_exp_f32);
    cuda_unary_baracuda_wrapper!(log_f32, bk::unary_log_f32);
    cuda_unary_baracuda_wrapper!(sin_f32, bk::unary_sin_f32);
    cuda_unary_baracuda_wrapper!(cos_f32, bk::unary_cos_f32);
    cuda_unary_baracuda_wrapper!(tanh_f32, bk::unary_tanh_f32);
    cuda_unary_baracuda_wrapper!(relu_f32, bk::unary_relu_f32);
    cuda_unary_baracuda_wrapper!(gelu_f32, bk::unary_gelu_f32);
    cuda_unary_baracuda_wrapper!(silu_f32, bk::unary_silu_f32);
    cuda_unary_baracuda_wrapper!(sigmoid_f32, bk::unary_sigmoid_f32);

    // f16
    cuda_unary_baracuda_wrapper!(neg_f16, bk::unary_neg_f16);
    cuda_unary_baracuda_wrapper!(abs_f16, bk::unary_abs_f16);
    cuda_unary_baracuda_wrapper!(sqr_f16, bk::unary_sqr_f16);
    cuda_unary_baracuda_wrapper!(sqrt_f16, bk::unary_sqrt_f16);
    cuda_unary_baracuda_wrapper!(recip_f16, bk::unary_recip_f16);
    cuda_unary_baracuda_wrapper!(exp_f16, bk::unary_exp_f16);
    cuda_unary_baracuda_wrapper!(log_f16, bk::unary_log_f16);
    cuda_unary_baracuda_wrapper!(sin_f16, bk::unary_sin_f16);
    cuda_unary_baracuda_wrapper!(cos_f16, bk::unary_cos_f16);
    cuda_unary_baracuda_wrapper!(tanh_f16, bk::unary_tanh_f16);
    cuda_unary_baracuda_wrapper!(relu_f16, bk::unary_relu_f16);
    cuda_unary_baracuda_wrapper!(gelu_f16, bk::unary_gelu_f16);
    cuda_unary_baracuda_wrapper!(silu_f16, bk::unary_silu_f16);
    cuda_unary_baracuda_wrapper!(sigmoid_f16, bk::unary_sigmoid_f16);

    // bf16
    cuda_unary_baracuda_wrapper!(neg_bf16, bk::unary_neg_bf16);
    cuda_unary_baracuda_wrapper!(abs_bf16, bk::unary_abs_bf16);
    cuda_unary_baracuda_wrapper!(sqr_bf16, bk::unary_sqr_bf16);
    cuda_unary_baracuda_wrapper!(sqrt_bf16, bk::unary_sqrt_bf16);
    cuda_unary_baracuda_wrapper!(recip_bf16, bk::unary_recip_bf16);
    cuda_unary_baracuda_wrapper!(exp_bf16, bk::unary_exp_bf16);
    cuda_unary_baracuda_wrapper!(log_bf16, bk::unary_log_bf16);
    cuda_unary_baracuda_wrapper!(sin_bf16, bk::unary_sin_bf16);
    cuda_unary_baracuda_wrapper!(cos_bf16, bk::unary_cos_bf16);
    cuda_unary_baracuda_wrapper!(tanh_bf16, bk::unary_tanh_bf16);
    cuda_unary_baracuda_wrapper!(relu_bf16, bk::unary_relu_bf16);
    cuda_unary_baracuda_wrapper!(gelu_bf16, bk::unary_gelu_bf16);
    cuda_unary_baracuda_wrapper!(silu_bf16, bk::unary_silu_bf16);
    cuda_unary_baracuda_wrapper!(sigmoid_bf16, bk::unary_sigmoid_bf16);

    // f64
    cuda_unary_baracuda_wrapper!(neg_f64, bk::unary_neg_f64);
    cuda_unary_baracuda_wrapper!(abs_f64, bk::unary_abs_f64);
    cuda_unary_baracuda_wrapper!(sqr_f64, bk::unary_sqr_f64);
    cuda_unary_baracuda_wrapper!(sqrt_f64, bk::unary_sqrt_f64);
    cuda_unary_baracuda_wrapper!(recip_f64, bk::unary_recip_f64);
    cuda_unary_baracuda_wrapper!(exp_f64, bk::unary_exp_f64);
    cuda_unary_baracuda_wrapper!(log_f64, bk::unary_log_f64);
    cuda_unary_baracuda_wrapper!(sin_f64, bk::unary_sin_f64);
    cuda_unary_baracuda_wrapper!(cos_f64, bk::unary_cos_f64);
    cuda_unary_baracuda_wrapper!(tanh_f64, bk::unary_tanh_f64);
    cuda_unary_baracuda_wrapper!(relu_f64, bk::unary_relu_f64);
    cuda_unary_baracuda_wrapper!(gelu_f64, bk::unary_gelu_f64);
    cuda_unary_baracuda_wrapper!(silu_f64, bk::unary_silu_f64);
    cuda_unary_baracuda_wrapper!(sigmoid_f64, bk::unary_sigmoid_f64);

    // Wrappers are `pub fn` (per the macro); accessible as
    // `unary::<name>` from `register_baracuda_cuda_kernels` below.
}

/// Register every baracuda-backed CUDA kernel into the binding table
/// as an alternative at its `(OpKind, dtypes, Cuda)` decision point.
/// Sits alongside the PTX-backed `register_cuda_kernels` — both can
/// be called on the same table; step 9a's append-on-register makes
/// them coexist.
///
/// Coverage today: 53 unary entries across F32/F16/BF16/F64.
/// Subsequent commits fan out to binary / ternary / norm / softmax /
/// attention / GGUF / MoE / int-GEMM / etc.
pub fn register_baracuda_cuda_kernels(table: &mut KernelBindingTable) {
    use OpKind::*;
    let cuda = BackendId::Cuda;
    let u = |t: DType| [t, t];
    let b = |t: DType| [t, t, t];

    let f32 = DType::F32;
    let f16 = DType::F16;
    let bf16 = DType::BF16;
    let f64 = DType::F64;

    // Baracuda binary kernels ship both contig and strided variants;
    // the wrapper in fuel-cuda-backend/src/baracuda/binary.rs picks
    // per-call via `is_contiguous_zero_offset(layout)`. Advertise
    // `strided_input` so Fuel's auto-Contiguize gate stays out of the
    // way — the strided FFI is the fallback for non-contig views.
    let strided = KernelCaps::strided_input();

    // ----- F32 binary -----
    table.register_with_caps(AddElementwise,     &b(f32), cuda, binary::add_f32,     strided);
    table.register_with_caps(SubElementwise,     &b(f32), cuda, binary::sub_f32,     strided);
    table.register_with_caps(MulElementwise,     &b(f32), cuda, binary::mul_f32,     strided);
    table.register_with_caps(DivElementwise,     &b(f32), cuda, binary::div_f32,     strided);
    table.register_with_caps(MaximumElementwise, &b(f32), cuda, binary::maximum_f32, strided);
    table.register_with_caps(MinimumElementwise, &b(f32), cuda, binary::minimum_f32, strided);

    // ----- F16 / BF16 / F64 binary (net-new dtype coverage on CUDA) -----
    table.register_with_caps(AddElementwise,     &b(f16), cuda, binary::add_f16,     strided);
    table.register_with_caps(SubElementwise,     &b(f16), cuda, binary::sub_f16,     strided);
    table.register_with_caps(MulElementwise,     &b(f16), cuda, binary::mul_f16,     strided);
    table.register_with_caps(DivElementwise,     &b(f16), cuda, binary::div_f16,     strided);
    table.register_with_caps(MaximumElementwise, &b(f16), cuda, binary::maximum_f16, strided);
    table.register_with_caps(MinimumElementwise, &b(f16), cuda, binary::minimum_f16, strided);

    table.register_with_caps(AddElementwise,     &b(bf16), cuda, binary::add_bf16,     strided);
    table.register_with_caps(SubElementwise,     &b(bf16), cuda, binary::sub_bf16,     strided);
    table.register_with_caps(MulElementwise,     &b(bf16), cuda, binary::mul_bf16,     strided);
    table.register_with_caps(DivElementwise,     &b(bf16), cuda, binary::div_bf16,     strided);
    table.register_with_caps(MaximumElementwise, &b(bf16), cuda, binary::maximum_bf16, strided);
    table.register_with_caps(MinimumElementwise, &b(bf16), cuda, binary::minimum_bf16, strided);

    table.register_with_caps(AddElementwise,     &b(f64), cuda, binary::add_f64,     strided);
    table.register_with_caps(SubElementwise,     &b(f64), cuda, binary::sub_f64,     strided);
    table.register_with_caps(MulElementwise,     &b(f64), cuda, binary::mul_f64,     strided);
    table.register_with_caps(DivElementwise,     &b(f64), cuda, binary::div_f64,     strided);
    table.register_with_caps(MaximumElementwise, &b(f64), cuda, binary::maximum_f64, strided);
    table.register_with_caps(MinimumElementwise, &b(f64), cuda, binary::minimum_f64, strided);

    // ----- Reduce (single dispatch covers all axis configurations;
    //       the wrapper destructures OpParams::Reduce { dims, keepdim }) -----
    // Baracuda reduce FFI is fully stride-driven; the wrapper passes
    // `current_layout.stride()` as `stride_x` each iteration.
    table.register_with_caps(SumReduce,  &u(f32),  cuda, reduce::sum_f32,  strided);
    table.register_with_caps(MaxReduce,  &u(f32),  cuda, reduce::max_f32,  strided);
    table.register_with_caps(MinReduce,  &u(f32),  cuda, reduce::min_f32,  strided);
    table.register_with_caps(MeanReduce, &u(f32),  cuda, reduce::mean_f32, strided);

    table.register_with_caps(SumReduce,  &u(f16),  cuda, reduce::sum_f16,  strided);
    table.register_with_caps(MaxReduce,  &u(f16),  cuda, reduce::max_f16,  strided);
    table.register_with_caps(MinReduce,  &u(f16),  cuda, reduce::min_f16,  strided);
    table.register_with_caps(MeanReduce, &u(f16),  cuda, reduce::mean_f16, strided);

    table.register_with_caps(SumReduce,  &u(bf16), cuda, reduce::sum_bf16,  strided);
    table.register_with_caps(MaxReduce,  &u(bf16), cuda, reduce::max_bf16,  strided);
    table.register_with_caps(MinReduce,  &u(bf16), cuda, reduce::min_bf16,  strided);
    table.register_with_caps(MeanReduce, &u(bf16), cuda, reduce::mean_bf16, strided);

    table.register_with_caps(SumReduce,  &u(f64),  cuda, reduce::sum_f64,  strided);
    table.register_with_caps(MaxReduce,  &u(f64),  cuda, reduce::max_f64,  strided);
    table.register_with_caps(MinReduce,  &u(f64),  cuda, reduce::min_f64,  strided);
    table.register_with_caps(MeanReduce, &u(f64),  cuda, reduce::mean_f64, strided);

    // ----- Norm LastDim (RmsNorm + LayerNorm) -----
    // Wrapper now passes the input's true rank-N shape + strides to
    // baracuda's stride-driven norm FFI; auto-Contiguize skipped.
    table.register_with_caps(RmsNormLastDim,   &u(f32),  cuda, norm::rms_f32,  strided);
    table.register_with_caps(RmsNormLastDim,   &u(f16),  cuda, norm::rms_f16,  strided);
    table.register_with_caps(RmsNormLastDim,   &u(bf16), cuda, norm::rms_bf16, strided);
    table.register_with_caps(RmsNormLastDim,   &u(f64),  cuda, norm::rms_f64,  strided);

    table.register_with_caps(LayerNormLastDim, &u(f32),  cuda, norm::layer_f32,  strided);
    table.register_with_caps(LayerNormLastDim, &u(f16),  cuda, norm::layer_f16,  strided);
    table.register_with_caps(LayerNormLastDim, &u(bf16), cuda, norm::layer_bf16, strided);
    table.register_with_caps(LayerNormLastDim, &u(f64),  cuda, norm::layer_f64,  strided);

    // ----- Attention — RoPE -----
    // Baracuda alpha.31 ships a RoPE strided sibling; the wrapper
    // picks contig vs strided per-call and enforces head_dim
    // (innermost) stride == 1 on the strided path (the pair-dim
    // constraint baracuda's plan layer would enforce). BW kernels
    // exist in alpha.31 but stay unregistered until Fuel-IR grows
    // a RopeBackward OpKind.
    table.register_with_caps(Rope, &u(f32),  cuda, attention::rope_f32,  strided);
    table.register_with_caps(Rope, &u(f16),  cuda, attention::rope_f16,  strided);
    table.register_with_caps(Rope, &u(bf16), cuda, attention::rope_bf16, strided);
    table.register_with_caps(Rope, &u(f64),  cuda, attention::rope_f64,  strided);

    // ----- Softmax + LogSoftmax LastDim -----
    // Wrapper now passes the input's true rank-N shape + strides to
    // baracuda's stride-driven softmax FFI; auto-Contiguize skipped.
    table.register_with_caps(SoftmaxLastDim,    &u(f32),  cuda, softmax::softmax_f32,  strided);
    table.register_with_caps(SoftmaxLastDim,    &u(f16),  cuda, softmax::softmax_f16,  strided);
    table.register_with_caps(SoftmaxLastDim,    &u(bf16), cuda, softmax::softmax_bf16, strided);
    table.register_with_caps(SoftmaxLastDim,    &u(f64),  cuda, softmax::softmax_f64,  strided);

    table.register_with_caps(LogSoftmaxLastDim, &u(f32),  cuda, softmax::log_softmax_f32,  strided);
    table.register_with_caps(LogSoftmaxLastDim, &u(f16),  cuda, softmax::log_softmax_f16,  strided);
    table.register_with_caps(LogSoftmaxLastDim, &u(bf16), cuda, softmax::log_softmax_bf16, strided);
    table.register_with_caps(LogSoftmaxLastDim, &u(f64),  cuda, softmax::log_softmax_f64,  strided);

    // ----- IndexSelect / Gather / MaskedFill / ScatterAdd
    // Dtype keys mirror the existing CPU registrations:
    //   IndexSelect: [data, U32, data]
    //   Gather:      [data, U32, data]
    //   MaskedFill:  [data, U8,  data]
    //   ScatterAdd:  [data, U32, data, data] (base, idx, src, out — Fuel folds out into the table's per-key shape)
    let u32_dt = DType::U32;
    let u8_dt = DType::U8;
    let i32_dt = DType::I32;
    let index_select_dts = |dt: DType| [dt, u32_dt, dt];
    let gather_dts = |dt: DType| [dt, u32_dt, dt];
    let masked_dts = |dt: DType| [dt, u8_dt, dt];
    let scatter_dts = |dt: DType| [dt, u32_dt, dt, dt];

    table.register(IndexSelect, &index_select_dts(f32), cuda, indexing::index_select_f32);
    table.register(IndexSelect, &index_select_dts(f64), cuda, indexing::index_select_f64);
    table.register(IndexSelect, &index_select_dts(i32_dt), cuda, indexing::index_select_i32);

    table.register(Gather, &gather_dts(f32), cuda, indexing::gather_f32);
    table.register(Gather, &gather_dts(f64), cuda, indexing::gather_f64);
    table.register(Gather, &gather_dts(i32_dt), cuda, indexing::gather_i32);

    table.register(MaskedFill, &masked_dts(f32), cuda, indexing::masked_fill_f32);
    table.register(MaskedFill, &masked_dts(f64), cuda, indexing::masked_fill_f64);
    table.register(MaskedFill, &masked_dts(i32_dt), cuda, indexing::masked_fill_i32);

    table.register(ScatterAdd, &scatter_dts(f32), cuda, indexing::scatter_add_f32);
    table.register(ScatterAdd, &scatter_dts(f64), cuda, indexing::scatter_add_f64);

    // ----- Int-GEMM — S8/U8 RRR Identity (alpha.28; W8A8 phase 1).
    // Registers at the MatMul OpKind with the [int, int, int] key.
    let i8_dt = DType::I8;
    let u8_dt = DType::U8;
    table.register(MatMul, &[i8_dt, i8_dt, i8_dt], cuda, gemm_int::gemm_s8_rrr);
    table.register(MatMul, &[u8_dt, u8_dt, u8_dt], cuda, gemm_int::gemm_u8_rrr);

    // ----- ArgMaxDim / ArgMinDim — U32 output (alpha.28 added u32/i32 outputs).
    // Net-new dtype coverage on CUDA: PTX path is F32-only.
    let u32_dt = DType::U32;
    let arg_dts = |dt: DType| [dt, u32_dt];
    // arg_reduce wrapper passes `src_layout.stride()` as stride_x.
    table.register_with_caps(ArgMaxDim, &arg_dts(f32),  cuda, arg_reduce::argmax_dim_u32_f32,  strided);
    table.register_with_caps(ArgMinDim, &arg_dts(f32),  cuda, arg_reduce::argmin_dim_u32_f32,  strided);
    table.register_with_caps(ArgMaxDim, &arg_dts(f64),  cuda, arg_reduce::argmax_dim_u32_f64,  strided);
    table.register_with_caps(ArgMinDim, &arg_dts(f64),  cuda, arg_reduce::argmin_dim_u32_f64,  strided);
    table.register_with_caps(ArgMaxDim, &arg_dts(f16),  cuda, arg_reduce::argmax_dim_u32_f16,  strided);
    table.register_with_caps(ArgMinDim, &arg_dts(f16),  cuda, arg_reduce::argmin_dim_u32_f16,  strided);
    table.register_with_caps(ArgMaxDim, &arg_dts(bf16), cuda, arg_reduce::argmax_dim_u32_bf16, strided);
    table.register_with_caps(ArgMinDim, &arg_dts(bf16), cuda, arg_reduce::argmin_dim_u32_bf16, strided);

    // ----- PowI — integer-exponent power (alpha.28).
    // Net-new dtype coverage on CUDA for F64/F16/BF16; F32 is a sibling.
    // Baracuda alpha.31 ships strided FW siblings; the wrapper picks
    // contig vs strided per-call. BW kernels also exist in alpha.31
    // (baracuda::powi::powi_backward_*) but stay unregistered until
    // Fuel-IR grows a PowIElementwiseBackward OpKind.
    table.register_with_caps(PowIElementwise, &u(f32),  cuda, powi::powi_f32,  strided);
    table.register_with_caps(PowIElementwise, &u(f64),  cuda, powi::powi_f64,  strided);
    table.register_with_caps(PowIElementwise, &u(f16),  cuda, powi::powi_f16,  strided);
    table.register_with_caps(PowIElementwise, &u(bf16), cuda, powi::powi_bf16, strided);

    // ----- Clamp — scalar bounds → broadcast-tensor ternary clamp.
    // Net-new dtype coverage on CUDA for F64/F16/BF16; F32 is a sibling.
    // Wrapper now passes the input's true rank-N shape + strides;
    // bounds are broadcast (stride 0 on every axis).
    table.register_with_caps(ClampElementwise, &u(f32),  cuda, clamp::clamp_f32,  strided);
    table.register_with_caps(ClampElementwise, &u(f64),  cuda, clamp::clamp_f64,  strided);
    table.register_with_caps(ClampElementwise, &u(f16),  cuda, clamp::clamp_f16,  strided);
    table.register_with_caps(ClampElementwise, &u(bf16), cuda, clamp::clamp_bf16, strided);

    // ----- Concat — N-ary via chained baracuda concat2.
    // Net-new dtype coverage on CUDA for F64/F16/BF16; F32 is a sibling.
    table.register(Concat, &u(f32),  cuda, concat::concat_f32);
    table.register(Concat, &u(f64),  cuda, concat::concat_f64);
    table.register(Concat, &u(f16),  cuda, concat::concat_f16);
    table.register(Concat, &u(bf16), cuda, concat::concat_bf16);

    // ----- WriteSlice — in-place rectangular slab assign (alpha.29).
    // Byte-width-keyed kernel (b1/b2/b4/b8); per-dtype entries just
    // pick the right byte-width wrapper. Unblocks Fuel's persistent
    // KV-cache integration (Phase 7.6 step 9c E.3.3).
    table.register(WriteSlice, &u(f32),       cuda, write_slice::write_slice_b4);
    table.register(WriteSlice, &u(f64),       cuda, write_slice::write_slice_b8);
    table.register(WriteSlice, &u(f16),       cuda, write_slice::write_slice_b2);
    table.register(WriteSlice, &u(bf16),      cuda, write_slice::write_slice_b2);
    table.register(WriteSlice, &u(DType::I32),cuda, write_slice::write_slice_b4);
    table.register(WriteSlice, &u(DType::I64),cuda, write_slice::write_slice_b8);
    table.register(WriteSlice, &u(DType::U32),cuda, write_slice::write_slice_b4);
    table.register(WriteSlice, &u(DType::U8), cuda, write_slice::write_slice_b1);
    table.register(WriteSlice, &u(DType::I8), cuda, write_slice::write_slice_b1);

    // ----- Triu / Tril — triangular masks (alpha.29).
    // 7 dtypes per direction in baracuda; Fuel registers the
    // float + integer subset that the CPU path already covers.
    // bool is parked until Fuel adds Bool storage (CPU coverage today
    // also skips Bool — the kernel exists if/when needed).
    // Baracuda alpha.31 ships strided siblings for triu/tril. Wrapper
    // picks contig vs strided per-call; BW reuses FW (mask self-adjoint,
    // Phase 13.4).
    table.register_with_caps(Triu, &u(f32),  cuda, triangular::triu_f32,  strided);
    table.register_with_caps(Triu, &u(f64),  cuda, triangular::triu_f64,  strided);
    table.register_with_caps(Triu, &u(f16),  cuda, triangular::triu_f16,  strided);
    table.register_with_caps(Triu, &u(bf16), cuda, triangular::triu_bf16, strided);
    table.register_with_caps(Triu, &u(DType::I32), cuda, triangular::triu_i32, strided);
    table.register_with_caps(Triu, &u(DType::I64), cuda, triangular::triu_i64, strided);

    table.register_with_caps(Tril, &u(f32),  cuda, triangular::tril_f32,  strided);
    table.register_with_caps(Tril, &u(f64),  cuda, triangular::tril_f64,  strided);
    table.register_with_caps(Tril, &u(f16),  cuda, triangular::tril_f16,  strided);
    table.register_with_caps(Tril, &u(bf16), cuda, triangular::tril_bf16, strided);
    table.register_with_caps(Tril, &u(DType::I32), cuda, triangular::tril_i32, strided);
    table.register_with_caps(Tril, &u(DType::I64), cuda, triangular::tril_i64, strided);

    // ----- Flip — single-axis reverse. 4 float dtypes; integer dtypes
    // (u8/u32) parked until baracuda extends the symbol set (today's
    // CPU set covers u8/u32 via the dtype-agnostic byte-level kernel).
    table.register(Flip, &u(f32),  cuda, flip::flip_f32);
    table.register(Flip, &u(f64),  cuda, flip::flip_f64);
    table.register(Flip, &u(f16),  cuda, flip::flip_f16);
    table.register(Flip, &u(bf16), cuda, flip::flip_bf16);

    // ----- Roll — single-axis cyclic shift. Same 4 float dtypes as Flip.
    table.register(Roll, &u(f32),  cuda, roll::roll_f32);
    table.register(Roll, &u(f64),  cuda, roll::roll_f64);
    table.register(Roll, &u(f16),  cuda, roll::roll_f16);
    table.register(Roll, &u(bf16), cuda, roll::roll_bf16);

    // ----- CumSum — single-axis inclusive prefix sum. 4 float dtypes.
    // Backward (reverse-cumsum) is expressed upstream as Flip → CumSum →
    // Flip, so the kernel itself never needs the reverse flag.
    table.register(CumSum, &u(f32),  cuda, cumsum::cumsum_f32);
    table.register(CumSum, &u(f64),  cuda, cumsum::cumsum_f64);
    table.register(CumSum, &u(f16),  cuda, cumsum::cumsum_f16);
    table.register(CumSum, &u(bf16), cuda, cumsum::cumsum_bf16);

    // ----- Pad / PadBackward — multi-dim padding.
    // Forward: Constant/Reflect/Replicate per dtype (Circular parked
    // until fuel-graph emits it). Backward: Constant only (other
    // backwards are sum-accumulating and not shipped in baracuda
    // alpha.29 — CPU stays the only target for those).
    table.register(Pad, &u(f32),  cuda, pad::pad_f32);
    table.register(Pad, &u(f64),  cuda, pad::pad_f64);
    table.register(Pad, &u(f16),  cuda, pad::pad_f16);
    table.register(Pad, &u(bf16), cuda, pad::pad_bf16);

    table.register(PadBackward, &u(f32),  cuda, pad::pad_backward_f32);
    table.register(PadBackward, &u(f64),  cuda, pad::pad_backward_f64);
    table.register(PadBackward, &u(f16),  cuda, pad::pad_backward_f16);
    table.register(PadBackward, &u(bf16), cuda, pad::pad_backward_bf16);

    // ----- Affine — `y = mul * x + add` (scalar in OpParams::Affine).
    // Net-new dtype coverage on CUDA: PTX path is f32 only.
    // Baracuda alpha.31 ships strided siblings for all 7 dtypes; the
    // wrapper picks contig vs strided per-call.
    table.register_with_caps(Affine, &u(f32),  cuda, affine::affine_f32,  strided);
    table.register_with_caps(Affine, &u(f64),  cuda, affine::affine_f64,  strided);
    table.register_with_caps(Affine, &u(f16),  cuda, affine::affine_f16,  strided);
    table.register_with_caps(Affine, &u(bf16), cuda, affine::affine_bf16, strided);
    table.register_with_caps(Affine, &u(DType::I32), cuda, affine::affine_i32, strided);
    table.register_with_caps(Affine, &u(DType::I64), cuda, affine::affine_i64, strided);
    table.register_with_caps(Affine, &u(DType::U8),  cuda, affine::affine_u8,  strided);

    // ----- Cast — 8×8 baracuda surface less I8/I16/F8/F4 (not in Fuel).
    // U32 collapses to baracuda i32 at the FFI level (bit-identical for
    // non-negative values — same trick as IndexSelect's index dtype).
    // Mirrors the pairs Fuel's PTX cast_cuda_wrapper already registers,
    // plus a few extras (e.g. F16↔I64, BF16↔I64) that baracuda exposes.
    let cast_dtypes = [
        DType::F32, DType::F64, DType::F16, DType::BF16,
        DType::I32, DType::U32, DType::I64, DType::U8,
    ];
    for &src in &cast_dtypes {
        for &dst in &cast_dtypes {
            table.register(Cast, &[src, dst], cuda, cast::cast_baracuda_wrapper);
        }
    }

    // F8E4M3 ↔ {F32, F16, BF16} — alpha.29's CastSubBytePlan (OCP/NV FP8
    // family). The same cast_baracuda_wrapper dispatches by inspecting
    // input + output dtypes via fuel_cuda_backend::baracuda::cast::dispatch.
    //
    // Not registered: F8E4M3 ↔ {I32, I64, U8, F64, F8E4M3} (baracuda
    // alpha.29's CastSubByte surface stops at {F32, F16, BF16} for FP8
    // — these would compose via an intermediate f32 cast).
    //
    // F8E5M2 / S4 / U4 / Bool exist in baracuda alpha.29 but aren't in
    // Fuel's DType enum yet (would require the I8-style cascade through
    // every match site before any registration is possible).
    //
    // F6E2M3 / F6E3M2 / F4 / F8E8M0 are in Fuel's DType but are MX
    // (Microscaling) formats — different from baracuda's OCP/NV FP8
    // family. baracuda alpha.29's CastSubBytePlan doesn't cover them
    // (separate kernel family with scale tensors); still a real gap.
    for dst in [DType::F32, DType::F16, DType::BF16] {
        table.register(Cast, &[DType::F8E4M3, dst], cuda, cast::cast_baracuda_wrapper);
        table.register(Cast, &[dst, DType::F8E4M3], cuda, cast::cast_baracuda_wrapper);
    }

    // Baracuda unary kernels ship both contig + `<sym>_strided_run`
    // variants; the wrapper in fuel-cuda-backend/src/baracuda/elementwise.rs
    // picks per-call via `is_contiguous_zero_offset(layout)`.

    // ----- F32 unary -----
    table.register_with_caps(NegElementwise,     &u(f32), cuda, unary::neg_f32,     strided);
    table.register_with_caps(AbsElementwise,     &u(f32), cuda, unary::abs_f32,     strided);
    table.register_with_caps(SignElementwise,    &u(f32), cuda, unary::sign_f32,    strided);
    table.register_with_caps(SqrElementwise,     &u(f32), cuda, unary::sqr_f32,     strided);
    table.register_with_caps(SqrtElementwise,    &u(f32), cuda, unary::sqrt_f32,    strided);
    table.register_with_caps(RecipElementwise,   &u(f32), cuda, unary::recip_f32,   strided);
    table.register_with_caps(ExpElementwise,     &u(f32), cuda, unary::exp_f32,     strided);
    table.register_with_caps(LogElementwise,     &u(f32), cuda, unary::log_f32,     strided);
    table.register_with_caps(SinElementwise,     &u(f32), cuda, unary::sin_f32,     strided);
    table.register_with_caps(CosElementwise,     &u(f32), cuda, unary::cos_f32,     strided);
    table.register_with_caps(TanhElementwise,    &u(f32), cuda, unary::tanh_f32,    strided);
    table.register_with_caps(ReluElementwise,    &u(f32), cuda, unary::relu_f32,    strided);
    table.register_with_caps(GeluElementwise,    &u(f32), cuda, unary::gelu_f32,    strided);
    table.register_with_caps(SiluElementwise,    &u(f32), cuda, unary::silu_f32,    strided);
    table.register_with_caps(SigmoidElementwise, &u(f32), cuda, unary::sigmoid_f32, strided);

    // ----- F16 unary (net-new dtype coverage for CUDA — PTX path is
    //       f32-only today) -----
    table.register_with_caps(NegElementwise,     &u(f16), cuda, unary::neg_f16,     strided);
    table.register_with_caps(AbsElementwise,     &u(f16), cuda, unary::abs_f16,     strided);
    table.register_with_caps(SqrElementwise,     &u(f16), cuda, unary::sqr_f16,     strided);
    table.register_with_caps(SqrtElementwise,    &u(f16), cuda, unary::sqrt_f16,    strided);
    table.register_with_caps(RecipElementwise,   &u(f16), cuda, unary::recip_f16,   strided);
    table.register_with_caps(ExpElementwise,     &u(f16), cuda, unary::exp_f16,     strided);
    table.register_with_caps(LogElementwise,     &u(f16), cuda, unary::log_f16,     strided);
    table.register_with_caps(SinElementwise,     &u(f16), cuda, unary::sin_f16,     strided);
    table.register_with_caps(CosElementwise,     &u(f16), cuda, unary::cos_f16,     strided);
    table.register_with_caps(TanhElementwise,    &u(f16), cuda, unary::tanh_f16,    strided);
    table.register_with_caps(ReluElementwise,    &u(f16), cuda, unary::relu_f16,    strided);
    table.register_with_caps(GeluElementwise,    &u(f16), cuda, unary::gelu_f16,    strided);
    table.register_with_caps(SiluElementwise,    &u(f16), cuda, unary::silu_f16,    strided);
    table.register_with_caps(SigmoidElementwise, &u(f16), cuda, unary::sigmoid_f16, strided);

    // ----- BF16 unary -----
    table.register_with_caps(NegElementwise,     &u(bf16), cuda, unary::neg_bf16,     strided);
    table.register_with_caps(AbsElementwise,     &u(bf16), cuda, unary::abs_bf16,     strided);
    table.register_with_caps(SqrElementwise,     &u(bf16), cuda, unary::sqr_bf16,     strided);
    table.register_with_caps(SqrtElementwise,    &u(bf16), cuda, unary::sqrt_bf16,    strided);
    table.register_with_caps(RecipElementwise,   &u(bf16), cuda, unary::recip_bf16,   strided);
    table.register_with_caps(ExpElementwise,     &u(bf16), cuda, unary::exp_bf16,     strided);
    table.register_with_caps(LogElementwise,     &u(bf16), cuda, unary::log_bf16,     strided);
    table.register_with_caps(SinElementwise,     &u(bf16), cuda, unary::sin_bf16,     strided);
    table.register_with_caps(CosElementwise,     &u(bf16), cuda, unary::cos_bf16,     strided);
    table.register_with_caps(TanhElementwise,    &u(bf16), cuda, unary::tanh_bf16,    strided);
    table.register_with_caps(ReluElementwise,    &u(bf16), cuda, unary::relu_bf16,    strided);
    table.register_with_caps(GeluElementwise,    &u(bf16), cuda, unary::gelu_bf16,    strided);
    table.register_with_caps(SiluElementwise,    &u(bf16), cuda, unary::silu_bf16,    strided);
    table.register_with_caps(SigmoidElementwise, &u(bf16), cuda, unary::sigmoid_bf16, strided);

    // ----- F64 unary -----
    table.register_with_caps(NegElementwise,     &u(f64), cuda, unary::neg_f64,     strided);
    table.register_with_caps(AbsElementwise,     &u(f64), cuda, unary::abs_f64,     strided);
    table.register_with_caps(SqrElementwise,     &u(f64), cuda, unary::sqr_f64,     strided);
    table.register_with_caps(SqrtElementwise,    &u(f64), cuda, unary::sqrt_f64,    strided);
    table.register_with_caps(RecipElementwise,   &u(f64), cuda, unary::recip_f64,   strided);
    table.register_with_caps(ExpElementwise,     &u(f64), cuda, unary::exp_f64,     strided);
    table.register_with_caps(LogElementwise,     &u(f64), cuda, unary::log_f64,     strided);
    table.register_with_caps(SinElementwise,     &u(f64), cuda, unary::sin_f64,     strided);
    table.register_with_caps(CosElementwise,     &u(f64), cuda, unary::cos_f64,     strided);
    table.register_with_caps(TanhElementwise,    &u(f64), cuda, unary::tanh_f64,    strided);
    table.register_with_caps(ReluElementwise,    &u(f64), cuda, unary::relu_f64,    strided);
    table.register_with_caps(GeluElementwise,    &u(f64), cuda, unary::gelu_f64,    strided);
    table.register_with_caps(SiluElementwise,    &u(f64), cuda, unary::silu_f64,    strided);
    table.register_with_caps(SigmoidElementwise, &u(f64), cuda, unary::sigmoid_f64, strided);
}
