//! Dispatch wrappers + registration for baracuda-kernels-sys-backed
//! kernels. Sibling to `dispatch::register_cuda_kernels` (PTX path) —
//! each kernel here registers as an alternative at the same
//! `(op_kind, dtypes, BackendId::Cuda)` key. Phase 7.6 step 9a's
//! append-on-register semantics keep them composable; step 9b's
//! route picker ranks by `PrecisionGuarantee` + telemetry.
//!
//! The boilerplate-explosion in this file (50+ unary kinds × 4
//! dtypes, plus binary / ternary / etc.) is generated by per-family
//! macros — adding a new (op, dtype) entry is one manifest line
//! here + one matching line in `fuel-cuda-backend::baracuda`.

#![cfg(feature = "cuda")]

use std::sync::{Arc, RwLock};

use fuel_core_types::{Layout, Error, Result, probe::BackendId};
use fuel_core_types::dispatch::OpKind;
use fuel_core_types::DType;

use crate::kernel::{KernelBindingTable, OpParams};
use crate::Storage;

// Re-use the storage-helpers from dispatch.rs so we read/write
// CudaStorageBytes the same way the PTX wrappers do.
use crate::dispatch::{cuda_input, cuda_output, read_storage, write_storage};

/// Generate one CUDA unary dispatch wrapper that adapts a baracuda
/// `fn(&CudaStorageBytes, Option<&Layout>) -> Result<CudaStorageBytes>`
/// kernel into the `KernelRef` signature the binding table expects.
///
/// Arguments:
/// - `$wrapper_name` — the function symbol to emit.
/// - `$baracuda_fn` — fully-qualified path to the baracuda kernel
///   function (e.g. `fuel_cuda_backend::baracuda::elementwise::unary_neg_f32`).
macro_rules! cuda_unary_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            layouts: &[Layout],
            _params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 input, got {}"),
                    inputs.len(),
                ))
                .bt());
            }
            if outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 output, got {}"),
                    outputs.len(),
                ))
                .bt());
            }
            let layout = layouts.first();
            let in_guard = read_storage(&inputs[0])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let src_cuda = cuda_input(&in_guard)?;
            let result = $baracuda_fn(src_cuda, layout)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

/// Generate one CUDA binary dispatch wrapper.
macro_rules! cuda_binary_baracuda_wrapper {
    ($wrapper_name:ident, $baracuda_fn:path) => {
        pub fn $wrapper_name(
            inputs: &[Arc<RwLock<Storage>>],
            outputs: &mut [Arc<RwLock<Storage>>],
            layouts: &[Layout],
            _params: &OpParams,
        ) -> Result<()> {
            if inputs.len() != 2 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 2 inputs, got {}"),
                    inputs.len(),
                ))
                .bt());
            }
            if outputs.len() != 1 {
                return Err(Error::Msg(format!(
                    concat!(stringify!($wrapper_name), ": expected 1 output, got {}"),
                    outputs.len(),
                ))
                .bt());
            }
            let lhs_layout = layouts.first();
            let rhs_layout = layouts.get(1);
            let lhs_guard = read_storage(&inputs[0])?;
            let rhs_guard = read_storage(&inputs[1])?;
            let mut out_guard = write_storage(&outputs[0])?;
            let lhs_cuda = cuda_input(&lhs_guard)?;
            let rhs_cuda = cuda_input(&rhs_guard)?;
            let result = $baracuda_fn(lhs_cuda, rhs_cuda, lhs_layout, rhs_layout)?;
            let out_cuda = cuda_output(&mut out_guard)?;
            *out_cuda = result;
            Ok(())
        }
    };
}

// ===========================================================================
// Elementwise binary wrappers
// ===========================================================================

pub mod binary {
    use super::*;
    use fuel_cuda_backend::baracuda::binary as bk;

    cuda_binary_baracuda_wrapper!(add_f32, bk::binary_add_f32);
    cuda_binary_baracuda_wrapper!(sub_f32, bk::binary_sub_f32);
    cuda_binary_baracuda_wrapper!(mul_f32, bk::binary_mul_f32);
    cuda_binary_baracuda_wrapper!(div_f32, bk::binary_div_f32);
    cuda_binary_baracuda_wrapper!(maximum_f32, bk::binary_maximum_f32);
    cuda_binary_baracuda_wrapper!(minimum_f32, bk::binary_minimum_f32);

    cuda_binary_baracuda_wrapper!(add_f16, bk::binary_add_f16);
    cuda_binary_baracuda_wrapper!(sub_f16, bk::binary_sub_f16);
    cuda_binary_baracuda_wrapper!(mul_f16, bk::binary_mul_f16);
    cuda_binary_baracuda_wrapper!(div_f16, bk::binary_div_f16);
    cuda_binary_baracuda_wrapper!(maximum_f16, bk::binary_maximum_f16);
    cuda_binary_baracuda_wrapper!(minimum_f16, bk::binary_minimum_f16);

    cuda_binary_baracuda_wrapper!(add_bf16, bk::binary_add_bf16);
    cuda_binary_baracuda_wrapper!(sub_bf16, bk::binary_sub_bf16);
    cuda_binary_baracuda_wrapper!(mul_bf16, bk::binary_mul_bf16);
    cuda_binary_baracuda_wrapper!(div_bf16, bk::binary_div_bf16);
    cuda_binary_baracuda_wrapper!(maximum_bf16, bk::binary_maximum_bf16);
    cuda_binary_baracuda_wrapper!(minimum_bf16, bk::binary_minimum_bf16);

    cuda_binary_baracuda_wrapper!(add_f64, bk::binary_add_f64);
    cuda_binary_baracuda_wrapper!(sub_f64, bk::binary_sub_f64);
    cuda_binary_baracuda_wrapper!(mul_f64, bk::binary_mul_f64);
    cuda_binary_baracuda_wrapper!(div_f64, bk::binary_div_f64);
    cuda_binary_baracuda_wrapper!(maximum_f64, bk::binary_maximum_f64);
    cuda_binary_baracuda_wrapper!(minimum_f64, bk::binary_minimum_f64);
}

// ===========================================================================
// Elementwise unary wrappers
// ===========================================================================
//
// Manifest: one line per (op, dtype) pair. Both halves of the
// `(*_wrapper, *_kernel)` mapping live here so the file is the single
// source of truth for "baracuda's coverage of Fuel's binding table."

pub mod unary {
    use super::*;
    use fuel_cuda_backend::baracuda::elementwise as bk;

    // f32 surface
    cuda_unary_baracuda_wrapper!(neg_f32, bk::unary_neg_f32);
    cuda_unary_baracuda_wrapper!(abs_f32, bk::unary_abs_f32);
    cuda_unary_baracuda_wrapper!(sign_f32, bk::unary_sign_f32);
    cuda_unary_baracuda_wrapper!(sqr_f32, bk::unary_sqr_f32);
    cuda_unary_baracuda_wrapper!(sqrt_f32, bk::unary_sqrt_f32);
    cuda_unary_baracuda_wrapper!(rsqrt_f32, bk::unary_rsqrt_f32);
    cuda_unary_baracuda_wrapper!(recip_f32, bk::unary_recip_f32);
    cuda_unary_baracuda_wrapper!(exp_f32, bk::unary_exp_f32);
    cuda_unary_baracuda_wrapper!(log_f32, bk::unary_log_f32);
    cuda_unary_baracuda_wrapper!(sin_f32, bk::unary_sin_f32);
    cuda_unary_baracuda_wrapper!(cos_f32, bk::unary_cos_f32);
    cuda_unary_baracuda_wrapper!(tanh_f32, bk::unary_tanh_f32);
    cuda_unary_baracuda_wrapper!(relu_f32, bk::unary_relu_f32);
    cuda_unary_baracuda_wrapper!(gelu_f32, bk::unary_gelu_f32);
    cuda_unary_baracuda_wrapper!(silu_f32, bk::unary_silu_f32);
    cuda_unary_baracuda_wrapper!(sigmoid_f32, bk::unary_sigmoid_f32);

    // f16
    cuda_unary_baracuda_wrapper!(neg_f16, bk::unary_neg_f16);
    cuda_unary_baracuda_wrapper!(abs_f16, bk::unary_abs_f16);
    cuda_unary_baracuda_wrapper!(sqr_f16, bk::unary_sqr_f16);
    cuda_unary_baracuda_wrapper!(sqrt_f16, bk::unary_sqrt_f16);
    cuda_unary_baracuda_wrapper!(recip_f16, bk::unary_recip_f16);
    cuda_unary_baracuda_wrapper!(exp_f16, bk::unary_exp_f16);
    cuda_unary_baracuda_wrapper!(log_f16, bk::unary_log_f16);
    cuda_unary_baracuda_wrapper!(sin_f16, bk::unary_sin_f16);
    cuda_unary_baracuda_wrapper!(cos_f16, bk::unary_cos_f16);
    cuda_unary_baracuda_wrapper!(tanh_f16, bk::unary_tanh_f16);
    cuda_unary_baracuda_wrapper!(relu_f16, bk::unary_relu_f16);
    cuda_unary_baracuda_wrapper!(gelu_f16, bk::unary_gelu_f16);
    cuda_unary_baracuda_wrapper!(silu_f16, bk::unary_silu_f16);
    cuda_unary_baracuda_wrapper!(sigmoid_f16, bk::unary_sigmoid_f16);

    // bf16
    cuda_unary_baracuda_wrapper!(neg_bf16, bk::unary_neg_bf16);
    cuda_unary_baracuda_wrapper!(abs_bf16, bk::unary_abs_bf16);
    cuda_unary_baracuda_wrapper!(sqr_bf16, bk::unary_sqr_bf16);
    cuda_unary_baracuda_wrapper!(sqrt_bf16, bk::unary_sqrt_bf16);
    cuda_unary_baracuda_wrapper!(recip_bf16, bk::unary_recip_bf16);
    cuda_unary_baracuda_wrapper!(exp_bf16, bk::unary_exp_bf16);
    cuda_unary_baracuda_wrapper!(log_bf16, bk::unary_log_bf16);
    cuda_unary_baracuda_wrapper!(sin_bf16, bk::unary_sin_bf16);
    cuda_unary_baracuda_wrapper!(cos_bf16, bk::unary_cos_bf16);
    cuda_unary_baracuda_wrapper!(tanh_bf16, bk::unary_tanh_bf16);
    cuda_unary_baracuda_wrapper!(relu_bf16, bk::unary_relu_bf16);
    cuda_unary_baracuda_wrapper!(gelu_bf16, bk::unary_gelu_bf16);
    cuda_unary_baracuda_wrapper!(silu_bf16, bk::unary_silu_bf16);
    cuda_unary_baracuda_wrapper!(sigmoid_bf16, bk::unary_sigmoid_bf16);

    // f64
    cuda_unary_baracuda_wrapper!(neg_f64, bk::unary_neg_f64);
    cuda_unary_baracuda_wrapper!(abs_f64, bk::unary_abs_f64);
    cuda_unary_baracuda_wrapper!(sqr_f64, bk::unary_sqr_f64);
    cuda_unary_baracuda_wrapper!(sqrt_f64, bk::unary_sqrt_f64);
    cuda_unary_baracuda_wrapper!(recip_f64, bk::unary_recip_f64);
    cuda_unary_baracuda_wrapper!(exp_f64, bk::unary_exp_f64);
    cuda_unary_baracuda_wrapper!(log_f64, bk::unary_log_f64);
    cuda_unary_baracuda_wrapper!(sin_f64, bk::unary_sin_f64);
    cuda_unary_baracuda_wrapper!(cos_f64, bk::unary_cos_f64);
    cuda_unary_baracuda_wrapper!(tanh_f64, bk::unary_tanh_f64);
    cuda_unary_baracuda_wrapper!(relu_f64, bk::unary_relu_f64);
    cuda_unary_baracuda_wrapper!(gelu_f64, bk::unary_gelu_f64);
    cuda_unary_baracuda_wrapper!(silu_f64, bk::unary_silu_f64);
    cuda_unary_baracuda_wrapper!(sigmoid_f64, bk::unary_sigmoid_f64);

    // Wrappers are `pub fn` (per the macro); accessible as
    // `unary::<name>` from `register_baracuda_cuda_kernels` below.
}

/// Register every baracuda-backed CUDA kernel into the binding table
/// as an alternative at its `(OpKind, dtypes, Cuda)` decision point.
/// Sits alongside the PTX-backed `register_cuda_kernels` — both can
/// be called on the same table; step 9a's append-on-register makes
/// them coexist.
///
/// Coverage today: 53 unary entries across F32/F16/BF16/F64.
/// Subsequent commits fan out to binary / ternary / norm / softmax /
/// attention / GGUF / MoE / int-GEMM / etc.
pub fn register_baracuda_cuda_kernels(table: &mut KernelBindingTable) {
    use OpKind::*;
    let cuda = BackendId::Cuda;
    let u = |t: DType| [t, t];
    let b = |t: DType| [t, t, t];

    let f32 = DType::F32;
    let f16 = DType::F16;
    let bf16 = DType::BF16;
    let f64 = DType::F64;

    // ----- F32 binary -----
    table.register(AddElementwise,     &b(f32), cuda, binary::add_f32);
    table.register(SubElementwise,     &b(f32), cuda, binary::sub_f32);
    table.register(MulElementwise,     &b(f32), cuda, binary::mul_f32);
    table.register(DivElementwise,     &b(f32), cuda, binary::div_f32);
    table.register(MaximumElementwise, &b(f32), cuda, binary::maximum_f32);
    table.register(MinimumElementwise, &b(f32), cuda, binary::minimum_f32);

    // ----- F16 / BF16 / F64 binary (net-new dtype coverage on CUDA) -----
    table.register(AddElementwise,     &b(f16), cuda, binary::add_f16);
    table.register(SubElementwise,     &b(f16), cuda, binary::sub_f16);
    table.register(MulElementwise,     &b(f16), cuda, binary::mul_f16);
    table.register(DivElementwise,     &b(f16), cuda, binary::div_f16);
    table.register(MaximumElementwise, &b(f16), cuda, binary::maximum_f16);
    table.register(MinimumElementwise, &b(f16), cuda, binary::minimum_f16);

    table.register(AddElementwise,     &b(bf16), cuda, binary::add_bf16);
    table.register(SubElementwise,     &b(bf16), cuda, binary::sub_bf16);
    table.register(MulElementwise,     &b(bf16), cuda, binary::mul_bf16);
    table.register(DivElementwise,     &b(bf16), cuda, binary::div_bf16);
    table.register(MaximumElementwise, &b(bf16), cuda, binary::maximum_bf16);
    table.register(MinimumElementwise, &b(bf16), cuda, binary::minimum_bf16);

    table.register(AddElementwise,     &b(f64), cuda, binary::add_f64);
    table.register(SubElementwise,     &b(f64), cuda, binary::sub_f64);
    table.register(MulElementwise,     &b(f64), cuda, binary::mul_f64);
    table.register(DivElementwise,     &b(f64), cuda, binary::div_f64);
    table.register(MaximumElementwise, &b(f64), cuda, binary::maximum_f64);
    table.register(MinimumElementwise, &b(f64), cuda, binary::minimum_f64);

    // ----- F32 unary -----
    table.register(NegElementwise,    &u(f32), cuda, unary::neg_f32);
    table.register(AbsElementwise,    &u(f32), cuda, unary::abs_f32);
    table.register(SignElementwise,   &u(f32), cuda, unary::sign_f32);
    table.register(SqrElementwise,    &u(f32), cuda, unary::sqr_f32);
    table.register(SqrtElementwise,   &u(f32), cuda, unary::sqrt_f32);
    table.register(RecipElementwise,  &u(f32), cuda, unary::recip_f32);
    table.register(ExpElementwise,    &u(f32), cuda, unary::exp_f32);
    table.register(LogElementwise,    &u(f32), cuda, unary::log_f32);
    table.register(SinElementwise,    &u(f32), cuda, unary::sin_f32);
    table.register(CosElementwise,    &u(f32), cuda, unary::cos_f32);
    table.register(TanhElementwise,   &u(f32), cuda, unary::tanh_f32);
    table.register(ReluElementwise,   &u(f32), cuda, unary::relu_f32);
    table.register(GeluElementwise,   &u(f32), cuda, unary::gelu_f32);
    table.register(SiluElementwise,   &u(f32), cuda, unary::silu_f32);
    table.register(SigmoidElementwise, &u(f32), cuda, unary::sigmoid_f32);

    // ----- F16 unary (net-new dtype coverage for CUDA — PTX path is
    //       f32-only today) -----
    table.register(NegElementwise,    &u(f16), cuda, unary::neg_f16);
    table.register(AbsElementwise,    &u(f16), cuda, unary::abs_f16);
    table.register(SqrElementwise,    &u(f16), cuda, unary::sqr_f16);
    table.register(SqrtElementwise,   &u(f16), cuda, unary::sqrt_f16);
    table.register(RecipElementwise,  &u(f16), cuda, unary::recip_f16);
    table.register(ExpElementwise,    &u(f16), cuda, unary::exp_f16);
    table.register(LogElementwise,    &u(f16), cuda, unary::log_f16);
    table.register(SinElementwise,    &u(f16), cuda, unary::sin_f16);
    table.register(CosElementwise,    &u(f16), cuda, unary::cos_f16);
    table.register(TanhElementwise,   &u(f16), cuda, unary::tanh_f16);
    table.register(ReluElementwise,   &u(f16), cuda, unary::relu_f16);
    table.register(GeluElementwise,   &u(f16), cuda, unary::gelu_f16);
    table.register(SiluElementwise,   &u(f16), cuda, unary::silu_f16);
    table.register(SigmoidElementwise, &u(f16), cuda, unary::sigmoid_f16);

    // ----- BF16 unary -----
    table.register(NegElementwise,    &u(bf16), cuda, unary::neg_bf16);
    table.register(AbsElementwise,    &u(bf16), cuda, unary::abs_bf16);
    table.register(SqrElementwise,    &u(bf16), cuda, unary::sqr_bf16);
    table.register(SqrtElementwise,   &u(bf16), cuda, unary::sqrt_bf16);
    table.register(RecipElementwise,  &u(bf16), cuda, unary::recip_bf16);
    table.register(ExpElementwise,    &u(bf16), cuda, unary::exp_bf16);
    table.register(LogElementwise,    &u(bf16), cuda, unary::log_bf16);
    table.register(SinElementwise,    &u(bf16), cuda, unary::sin_bf16);
    table.register(CosElementwise,    &u(bf16), cuda, unary::cos_bf16);
    table.register(TanhElementwise,   &u(bf16), cuda, unary::tanh_bf16);
    table.register(ReluElementwise,   &u(bf16), cuda, unary::relu_bf16);
    table.register(GeluElementwise,   &u(bf16), cuda, unary::gelu_bf16);
    table.register(SiluElementwise,   &u(bf16), cuda, unary::silu_bf16);
    table.register(SigmoidElementwise, &u(bf16), cuda, unary::sigmoid_bf16);

    // ----- F64 unary -----
    table.register(NegElementwise,    &u(f64), cuda, unary::neg_f64);
    table.register(AbsElementwise,    &u(f64), cuda, unary::abs_f64);
    table.register(SqrElementwise,    &u(f64), cuda, unary::sqr_f64);
    table.register(SqrtElementwise,   &u(f64), cuda, unary::sqrt_f64);
    table.register(RecipElementwise,  &u(f64), cuda, unary::recip_f64);
    table.register(ExpElementwise,    &u(f64), cuda, unary::exp_f64);
    table.register(LogElementwise,    &u(f64), cuda, unary::log_f64);
    table.register(SinElementwise,    &u(f64), cuda, unary::sin_f64);
    table.register(CosElementwise,    &u(f64), cuda, unary::cos_f64);
    table.register(TanhElementwise,   &u(f64), cuda, unary::tanh_f64);
    table.register(ReluElementwise,   &u(f64), cuda, unary::relu_f64);
    table.register(GeluElementwise,   &u(f64), cuda, unary::gelu_f64);
    table.register(SiluElementwise,   &u(f64), cuda, unary::silu_f64);
    table.register(SigmoidElementwise, &u(f64), cuda, unary::sigmoid_f64);
}
